/**
 * Wave 60.98-FE — /cam-nang pillar index page.
 *
 * Consumes the public worker endpoint `/content/public/pillars` (no auth,
 * 24h CDN cache at the edge — see backend/infra/cloudflare/workers/
 * api-gateway/src/content/routes.ts handlePublicContentRoute). Each pillar
 * is one of the 10 audience-route SEO articles generated by the Wave 60.98
 * multi-LLM engine (Claude + GPT + Gemini → judge → publish).
 *
 * The page is server-rendered + revalidated every 5 minutes so newly
 * published pillars surface within 5 minutes of founder hitting Publish
 * in /admin/content/:id.
 */

import type { Metadata } from 'next';
import Link from 'next/link';
import { BookOpen, ArrowRight } from 'lucide-react';
import { SiteNav } from '@/components/home/SiteNav';
import { SiteFooter } from '@/components/home/SiteFooter';
import { StickyMobileCta } from '@/components/marketing/StickyMobileCta';
import { JsonLd } from '@/components/seo/JsonLd';
import { breadcrumb, webPage } from '@/lib/seo/jsonld';

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? 'https://api.hieu.asia';

export const revalidate = 300; // 5 minutes — newly published pillars surface fast

export const metadata: Metadata = {
  title: 'Cẩm nang hieu.asia — Tử Vi, Bát Tự, MBTI, Thần Số Học',
  description:
    'Cẩm nang chuyên đề về Tử Vi, Bát Tự, MBTI và Thần Số Học — viết dễ hiểu, đối chiếu nhiều nguồn và biên tập tay, nói thẳng giới hạn thay vì phán số mệnh.',
  alternates: { canonical: 'https://hieu.asia/cam-nang' },
  openGraph: {
    title: 'Cẩm nang hieu.asia',
    description: 'Chuyên đề Tử Vi, Bát Tự, MBTI, Thần Số Học cho người Việt.',
    url: 'https://hieu.asia/cam-nang',
    type: 'website',
    images: [{ url: 'https://hieu.asia/og-image.jpg', width: 1200, height: 630, alt: 'Cẩm nang hieu.asia — Tử Vi, Bát Tự, MBTI, Thần Số Học' }],
  },
  twitter: { card: 'summary_large_image', images: ['https://hieu.asia/og-image.jpg'] },
};

interface PillarSummary {
  slug: string;
  topic: string;
  published_at: string | null;
  updated_at: string;
}

interface ListResponse {
  ok?: boolean;
  pillars?: PillarSummary[];
  error?: string;
}

async function fetchPillars(): Promise<PillarSummary[]> {
  try {
    const r = await fetch(`${API_BASE}/content/public/pillars`, {
      next: { revalidate: 300, tags: ['pillars'] },
    });
    if (!r.ok) return [];
    const data = (await r.json()) as ListResponse;
    return data.pillars ?? [];
  } catch {
    return [];
  }
}

function formatDate(iso: string | null): string {
  if (!iso) return '';
  try {
    const d = new Date(iso);
    return `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}/${d.getFullYear()}`;
  } catch {
    return '';
  }
}

export default async function CamNangIndexPage() {
  const pillars = await fetchPillars();

  return (
    <>
      <SiteNav />
      <JsonLd
        data={[
          webPage({
            name: 'Cẩm nang hieu.asia — Tử Vi, Bát Tự, MBTI, Thần Số Học',
            description:
              'Cẩm nang chuyên đề về Tử Vi, Bát Tự, MBTI và Thần Số Học — viết dễ hiểu, đối chiếu nhiều nguồn và biên tập tay, nói thẳng giới hạn thay vì phán số mệnh.',
            url: '/cam-nang',
          }),
          breadcrumb([
            { name: 'Trang chủ', url: '/' },
            { name: 'Cẩm nang', url: '/cam-nang' },
          ]),
        ]}
      />
      <main id="main-content" className="min-h-screen bg-background text-foreground pt-16">
        <section className="mx-auto max-w-4xl px-6 py-16">
          <div className="flex items-start gap-3">
            <div className="mt-1 rounded-md border border-gold/20 bg-gradient-to-br from-gold/15 to-gold/0 p-2 text-gold">
              <BookOpen className="h-5 w-5" aria-hidden />
            </div>
            <div>
              <p className="font-mono text-eyebrow uppercase tracking-[0.12em] text-gold-700">
                Cẩm nang · hieu.asia
              </p>
              <h1 className="mt-2 font-heading text-3xl font-bold leading-tight text-foreground sm:text-4xl">
                Chuyên đề Tử Vi, Bát Tự &amp; tâm lý hiện đại
              </h1>
              <p className="mt-4 max-w-2xl text-base leading-relaxed text-muted-foreground">
                Mỗi bài đối chiếu nhiều nguồn để hạn chế thiên lệch, rồi founder
                biên tập tay từng câu — nói rõ đâu là kiến thức cổ học, đâu là
                quan niệm tham khảo, thay vì phán chắc nịch.
              </p>
            </div>
          </div>

          <div className="mt-12 space-y-4">
              {pillars.length === 0 ? (
                <div className="rounded-card-editorial border border-border bg-card p-8 text-center text-sm text-muted-foreground">
                  <p>
                    Chưa có bài cẩm nang nào được xuất bản. Quay lại sau —
                    founder đang biên tập đợt đầu.
                  </p>
                </div>
              ) : (
                pillars.map((p) => (
                  <Link
                    key={p.slug}
                    href={`/cam-nang/${p.slug}`}
                    className="group flex items-start justify-between gap-4 rounded-card-editorial border border-border bg-card p-6 transition-colors hover:border-gold/30 hover:bg-card/80"
                  >
                    <div className="min-w-0 flex-1">
                      <h2 className="font-heading text-xl font-semibold text-foreground group-hover:text-gold">
                        {p.topic}
                      </h2>
                      <div className="mt-2 flex items-center gap-3 font-mono text-xs text-muted-foreground">
                        <code>/{p.slug}</code>
                        {p.published_at && <span>· {formatDate(p.published_at)}</span>}
                      </div>
                    </div>
                    <ArrowRight
                      className="mt-1 h-4 w-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-gold"
                      aria-hidden
                    />
                  </Link>
                ))
              )}
          </div>
        </section>
      </main>
      <SiteFooter />
      <StickyMobileCta trackId="cam-nang" />
    </>
  );
}
