// This file has been automatically migrated to valid ESM format by Storybook.
import { fileURLToPath } from "node:url";
import type { StorybookConfig } from '@storybook/nextjs-vite';
import path, { dirname } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Wave 60.42 — Storybook config for visual regression testing.
 *
 * Stories live in two places:
 *  1. `packages/ui/src/components/**` — shared design system (Button, Card, …)
 *  2. `apps/web/src/components/**` — app-specific (TrustStrip, OrnamentDivider, …)
 *
 * Framework `@storybook/nextjs-vite` reuses the web app's Next.js config (PostCSS
 * with `@tailwindcss/postcss`, tsconfig paths, transpilePackages for
 * `@hieu-asia/ui`). Stories import from the shared globals.css so brand
 * tokens and dark-mode CSS vars match what production renders.
 */
const config: StorybookConfig = {
  stories: [
    '../src/**/*.stories.@(ts|tsx|mdx)',
    '../../../packages/ui/src/**/*.stories.@(ts|tsx|mdx)',
  ],
  // Wave 60.51.b — use string package names (not getAbsolutePath helper) for Storybook 10
  // strict ESM resolution. SB 10 internally appends /preset to the path; the absolute
  // dir-path returned by getAbsolutePath caused ERR_MODULE_NOT_FOUND (preset vs preset.js).
  //
  // Wave 60.95.j P2-#17 — viewport addon is NOT listed here because Storybook 10
  // ships viewport inside the core `storybook` package (`storybook/viewport`); no
  // separate `@storybook/addon-viewport` package is published for v10. Custom
  // viewports are registered in `.storybook/preview.ts` via `parameters.viewport.options`.
  addons: ["@storybook/addon-themes", "@storybook/addon-docs"],
  framework: {
    name: "@storybook/nextjs-vite",
    options: {
      // Point to the web app's next.config.ts so Storybook inherits the same
      // PostCSS pipeline (Tailwind v4 beta), webpack tweaks, and image
      // remotePatterns.
      nextConfigPath: path.resolve(__dirname, '../next.config.ts'),
    },
  },
  typescript: {
    // Keep build fast — `reactDocgen: false` skips type-introspection for
    // controls. Re-enable once we need autogenerated controls in stories.
    reactDocgen: false,
  },
  staticDirs: ['../public'],
};

export default config;

function getAbsolutePath(value: string): any {
  return dirname(fileURLToPath(import.meta.resolve(`${value}/package.json`)));
}
