import type { StorybookConfig } from '@storybook/nextjs';
import path from 'node:path';

/**
 * Wave 60.42 — Storybook config for visual regression testing.
 *
 * Stories live in two places:
 *  1. `packages/ui/src/components/**` — shared design system (Button, Card, …)
 *  2. `apps/web/src/components/**` — app-specific (TrustStrip, OrnamentDivider, …)
 *
 * Framework `@storybook/nextjs` reuses the web app's Next.js config (PostCSS
 * with `@tailwindcss/postcss`, tsconfig paths, transpilePackages for
 * `@hieu-asia/ui`). Stories import from the shared globals.css so brand
 * tokens and dark-mode CSS vars match what production renders.
 */
const config: StorybookConfig = {
  stories: [
    '../src/**/*.stories.@(ts|tsx|mdx)',
    '../../../packages/ui/src/**/*.stories.@(ts|tsx|mdx)',
  ],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-themes',
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {
      // Point to the web app's next.config.ts so Storybook inherits the same
      // PostCSS pipeline (Tailwind v4 beta), webpack tweaks, and image
      // remotePatterns.
      nextConfigPath: path.resolve(__dirname, '../next.config.ts'),
    },
  },
  typescript: {
    // Keep build fast — `reactDocgen: false` skips type-introspection for
    // controls. Re-enable once we need autogenerated controls in stories.
    reactDocgen: false,
  },
  staticDirs: ['../public'],
};

export default config;
