// hieu.asia — Nội dung trang ý nghĩa 64 quẻ Kinh Dịch (nâng cấp dữ liệu mỏng 2026-06).
// Trước đây mỗi quẻ chỉ có 1 dòng nghĩa trong engine backend (/tools/iching);
// đây là dữ liệu BIÊN TẬP viết thật từng quẻ cho thư viện trang tĩnh.
// id/name/nameVi/binary COPY CHÍNH XÁC từ bảng King Wen của backend
// (backend/infra/cloudflare/workers/api-gateway/src/tools/iching.ts) — đừng sửa lệch.
// binary: 6 ký tự đọc từ hào 6 (đỉnh) xuống hào 1 (đáy); 1 = dương (liền), 0 = âm (đứt).
// Giọng: phản tư, không phán — quẻ mô tả THẾ CỤC, người hỏi giữ quyết định.

export interface QueKinhDich {
  id: number; // 1–64 theo trình tự King Wen
  slug: string;
  name: string; // tên Hán-Việt ngắn ("Càn", "Truân"…)
  nameVi: string; // tên đầy đủ ("Thuần Càn", "Thủy Lôi Truân"…)
  binary: string; // hào 6 → hào 1
  keyTags: string[]; // 2–3 từ khóa
  tuong: string; // hình tượng quẻ (ý Đại Tượng truyện) — 1–2 câu
  core: string; // ý chính của thế cục — 3–4 câu, nghĩa hiện đại
  advice: string; // gợi ý ứng xử trong thế cục này
  love: string; // góc tình cảm – quan hệ
  work: string; // góc công việc – tiền bạc
  reflect: string[]; // câu hỏi tự soi
}

/** 8 quái cơ bản — tra từ 3 bit ("111" = Càn…). Dùng để render cấu trúc quẻ + hình hào. */
export const TRIGRAMS: Record<string, { ten: string; tuong: string }> = {
  '111': { ten: 'Càn', tuong: 'Trời' },
  '000': { ten: 'Khôn', tuong: 'Đất' },
  '001': { ten: 'Chấn', tuong: 'Sấm' },
  '010': { ten: 'Khảm', tuong: 'Nước' },
  '100': { ten: 'Cấn', tuong: 'Núi' },
  '011': { ten: 'Đoài', tuong: 'Đầm' },
  '101': { ten: 'Ly', tuong: 'Lửa' },
  '110': { ten: 'Tốn', tuong: 'Gió' },
};

export const QUE_PAGES: QueKinhDich[] = [
  {
    id: 1,
    slug: 'thuan-can',
    name: 'Càn',
    nameVi: 'Thuần Càn',
    binary: '111111',
    keyTags: ['sức sáng tạo', 'tự cường', 'khởi xướng'],
    tuong: 'Sáu hào đều dương — trời vận hành mạnh mẽ không ngừng nghỉ. Người quân tử nhìn tượng ấy mà tự cường không nghỉ.',
    core: 'Thuần Càn là thế cục của năng lượng khởi xướng thuần khiết: mọi điều kiện bên trong bạn — ý chí, sức lực, sự sáng rõ — đang ở mức cao nhất. Đây là quẻ của người dẫn đầu, của việc dám đứng ra mở đường. Nhưng truyền thống cũng cài sẵn lời nhắc ở hào trên cùng: rồng bay quá cao sẽ hối — mạnh mà thiếu điểm dừng thì chính sức mạnh quay lại làm hại mình.',
    advice: 'Thuận thế mà khởi xướng việc lớn, nhưng giữ nhịp bền thay vì đốt cháy: mạnh nhất không phải lúc bốc nhất, mà là lúc đều nhất.',
    love: 'Chủ động bày tỏ, dẫn dắt mối quan hệ — nhưng nhớ người kia cần một người đồng hành, không cần một mặt trời lúc nào cũng chói.',
    work: 'Thời điểm tốt để khởi sự, nhận vai đầu tàu, đặt mục tiêu lớn. Cẩn thận duy nhất: đừng ôm trọn mọi vai vì thấy mình đang khỏe.',
    reflect: ['Sức lực dồi dào hiện tại của bạn đang được rót vào việc xứng đáng nhất chưa?', 'Đâu là "điểm dừng của rồng" mà bạn nên định trước khi bay?'],
  },
  {
    id: 2,
    slug: 'thuan-khon',
    name: 'Khôn',
    nameVi: 'Thuần Khôn',
    binary: '000000',
    keyTags: ['nhu thuận', 'bao dung', 'đi sau mà tới'],
    tuong: 'Sáu hào đều âm — đất dày nâng đỡ vạn vật không phân biệt. Người quân tử nhìn tượng ấy mà lấy đức dày để chở người.',
    core: 'Thuần Khôn là sức mạnh kiểu đất: không tranh đi trước mà bền bỉ nâng đỡ, không phát sáng mà làm chỗ cho mọi thứ mọc lên. Thế cục này bảo: lúc này vai trò của bạn là người hỗ trợ, người giữ nền — và đó không phải vai phụ. Lời quẻ có hình ảnh rất thực: con ngựa cái đi sau đầu đàn thì thuận, cố vượt lên trước thì lạc đường.',
    advice: 'Theo trước, dẫn sau: quan sát kỹ rồi mới bước, hỗ trợ hết mình cho việc chung, và để kết quả tự nói thay.',
    love: 'Sự dịu dàng và bao dung của bạn đang là chất keo của mối quan hệ. Chỉ canh một điều: bao dung khác với tự xóa mình.',
    work: 'Hợp vai vận hành, nâng đội, hoàn thiện việc người khác khởi xướng. Thành tích kiểu đất ít tiếng vỗ tay nhưng ai tinh đều thấy.',
    reflect: ['Bạn đang nâng đỡ ai/việc gì — và có để mình được nâng lại không?', 'Có chỗ nào bạn đang cố dẫn đầu trong khi thế cục cần bạn giữ nền?'],
  },
  {
    id: 3,
    slug: 'thuy-loi-truan',
    name: 'Truân',
    nameVi: 'Thủy Lôi Truân',
    binary: '010001',
    keyTags: ['khởi đầu gian nan', 'xây nền', 'tìm người giúp'],
    tuong: 'Mây trên sấm dưới — trời đất đang chuyển dạ, vạn vật sinh ra trong chật vật. Cỏ non đội đất mà lên: khó, nhưng là cái khó của sự sống.',
    core: 'Truân là quẻ của mọi sự bắt đầu: dự án mới, cuộc sống mới, vai trò mới — hỗn độn, thiếu thốn, va vấp. Kinh Dịch không coi đó là điềm xấu mà là pha tất yếu: hạt nảy mầm bao giờ cũng khó hơn cây đã lớn. Lời quẻ dặn hai điều: đừng vội tiến nhanh, và nên "dựng hầu" — tìm người đồng minh, người đỡ đầu, đừng gồng một mình.',
    advice: 'Chấp nhận giai đoạn lộn xộn như một phần của khởi đầu; ưu tiên dựng nền và tìm đồng minh thay vì đòi kết quả sớm.',
    love: 'Mối quan hệ mới chớm có thể vụng về, hiểu lầm vặt — bình thường. Kiên nhẫn với nhau ở đoạn này chính là khoản đầu tư.',
    work: 'Dự án đang ở pha gây dựng: chuẩn hóa từng thứ nhỏ, tuyển đúng một hai người, đừng mở rộng vội.',
    reflect: ['Cái khó hiện tại là khó của nảy mầm hay khó của sai hướng — phân biệt được không?', 'Ai là "người hầu tước" bạn nên mời vào cuộc thay vì tự gồng?'],
  },
  {
    id: 4,
    slug: 'son-thuy-mong',
    name: 'Mông',
    nameVi: 'Sơn Thủy Mông',
    binary: '100010',
    keyTags: ['mông muội', 'học hỏi', 'cần thầy'],
    tuong: 'Suối nguồn chảy ra dưới chân núi — nước mới sinh chưa biết đường, phải dò theo địa hình mà đi. Tượng của người mới học.',
    core: 'Mông là thế cục "chưa biết": bạn (hoặc việc của bạn) đang ở vùng mình chưa hiểu rõ. Quẻ này quý ở chỗ nó coi không-biết là điểm xuất phát tử tế, miễn là dám học. Lời quẻ có nguyên tắc nổi tiếng: không phải thầy tìm trò, mà trò phải tìm thầy — và hỏi một lần với lòng thành thì được trả lời, hỏi đi hỏi lại kiểu thử thách thì không ai đáp nữa.',
    advice: 'Nhận mình đang ở vùng mù, tìm đúng người đi trước mà hỏi — và hỏi với sự thành thật, không phải để kiểm tra người ta.',
    love: 'Đừng đoán mò ý nhau — hỏi thẳng, học cách hiểu người kia như học một môn mới: khiêm tốn và kiên nhẫn.',
    work: 'Giai đoạn học việc, nhận vùng mới: tìm mentor, đọc tài liệu gốc, làm bài tập nhỏ. Giả vờ biết là cách chậm nhất để giỏi.',
    reflect: ['Điều gì bạn đang giả vờ hiểu mà thật ra chưa hiểu?', 'Ai là người thầy bạn nên gõ cửa — và câu hỏi thành thật nhất bạn muốn hỏi là gì?'],
  },
  {
    id: 5,
    slug: 'thuy-thien-nhu',
    name: 'Nhu',
    nameVi: 'Thủy Thiên Nhu',
    binary: '010111',
    keyTags: ['chờ đúng thời', 'nuôi sức', 'không nóng vội'],
    tuong: 'Mây đã kéo lên trời nhưng mưa chưa rơi — người quân tử nhìn tượng ấy mà ăn uống yến vui, nuôi sức trong lúc chờ.',
    core: 'Nhu là nghệ thuật chờ đợi chủ động: điều kiện chưa chín, ép cũng không chín nhanh hơn. Khác với trì hoãn (trốn việc), chờ kiểu quẻ Nhu là biết rõ mình chờ cái gì, trong lúc đó vẫn ăn ngủ điều độ, vẫn mài công cụ, vẫn giữ niềm tin. Mây dày thế kia thì mưa chắc chắn rơi — việc của bạn là còn đủ sức lúc mưa xuống.',
    advice: 'Đặt tên rõ điều mình đang chờ (tín hiệu gì, mốc nào), rồi dùng thời gian chờ để nuôi sức và chuẩn bị — không phải để sốt ruột.',
    love: 'Tình cảm cần thêm thời gian chín — đừng ép một câu trả lời sớm. Sự hiện diện đều đặn thuyết phục hơn sự thúc giục.',
    work: 'Deal chưa chốt, quyết định chưa ra — theo dõi sát nhưng đừng đốt quan hệ bằng việc hối liên tục. Chuẩn bị sẵn để bật ngay khi có đèn xanh.',
    reflect: ['Bạn đang chờ tín hiệu cụ thể nào — nói ra được thành một câu không?', 'Thời gian chờ hiện tại đang nuôi bạn hay đang bào bạn?'],
  },
  {
    id: 6,
    slug: 'thien-thuy-tung',
    name: 'Tụng',
    nameVi: 'Thiên Thủy Tụng',
    binary: '111010',
    keyTags: ['tranh chấp', 'nên hòa giải', 'biết dừng'],
    tuong: 'Trời đi lên, nước chảy xuống — hai đằng ngược hướng ngay từ gốc. Tượng của bất đồng thành kiện tụng.',
    core: 'Tụng mô tả thế cục mâu thuẫn đã thành tranh chấp: hai bên ngược hướng từ nền tảng, càng đi càng xa. Lời quẻ thực tế đến lạnh: theo kiện đến cùng thì dù thắng cũng hung — cái giá của việc "ăn thua đủ" thường lớn hơn phần thắng. Khôn nhất trong thế này là dừng ở giữa chừng, tìm người công tâm đứng ra dàn xếp.',
    advice: 'Đừng leo thang. Xác định sớm điều mình thật sự cần (khác với điều mình muốn thắng), tìm bên trung gian uy tín, và chừa đường cho cả hai.',
    love: 'Cuộc cãi đang biến thành cuộc kiện — ai cũng thu thập "bằng chứng" về lỗi của người kia. Dừng lại: hai bạn cùng phe hay khác phe?',
    work: 'Tranh chấp hợp đồng, quyền lợi: ưu tiên thương lượng có văn bản, nhờ trung gian, và tính cả chi phí thời gian – quan hệ vào giá của việc theo đuổi.',
    reflect: ['Nếu thắng trọn vẹn cuộc tranh chấp này, bạn được gì — và mất gì không lấy lại được?', 'Ai là người đủ công tâm mà cả hai bên cùng nể?'],
  },
  {
    id: 7,
    slug: 'dia-thuy-su',
    name: 'Sư',
    nameVi: 'Địa Thủy Sư',
    binary: '000010',
    keyTags: ['kỷ luật', 'tổ chức', 'người cầm quân chính trực'],
    tuong: 'Nước chứa trong lòng đất — như quân đội ẩn trong dân. Sức mạnh tập thể chỉ phát huy khi được tổ chức và có chính nghĩa.',
    core: 'Sư là thế cục cần huy động lực lượng cho một việc lớn: dự án nhiều người, chiến dịch dài hơi, một "trận đánh" của đời. Quẻ này đặt hai điều kiện sòng phẳng: kỷ luật (quân không nghiêm thì đông mấy cũng loạn) và người cầm quân xứng đáng (giao việc lớn cho người nhỏ mọn thì chở thây mà về — lời hào nói thẳng vậy). Danh chính rồi mới ngôn thuận.',
    advice: 'Trước khi xuất quân: mục tiêu chính đáng chưa, người chỉ huy đúng chưa, kỷ luật đặt chưa? Đủ ba thứ mới đi.',
    love: 'Hai người đang cùng "ra trận" (mua nhà, cưới xin, nuôi con nhỏ) — phân vai rõ ràng và tôn trọng vai của nhau là một nửa chiến thắng.',
    work: 'Hợp lúc tổ chức lại đội nhóm, đặt quy tắc, chọn trưởng nhóm theo năng lực thay vì theo nể nang.',
    reflect: ['"Trận đánh" hiện tại của bạn có mục tiêu chính đáng đủ để mọi người theo không?', 'Việc lớn nào đang được giao cho người chưa xứng tầm — kể cả khi người đó là chính bạn?'],
  },
  {
    id: 8,
    slug: 'thuy-dia-ty',
    name: 'Tỷ',
    nameVi: 'Thủy Địa Tỷ',
    binary: '010000',
    keyTags: ['gắn kết', 'chọn chỗ tựa', 'đến sớm'],
    tuong: 'Nước trên mặt đất — nước với đất thân nhau không kẽ hở. Tượng của sự quy tụ quanh một trung tâm.',
    core: 'Tỷ là thế cục kết liên minh: người người đang tìm chỗ tựa, các nhóm đang hình thành. Quẻ nhắc một quy luật xã hội ít ai nói: vào sớm thì là đồng đội sáng lập, vào muộn thì mãi là người đến sau — lời quẻ gọi thẳng "kẻ đến muộn, hung". Và trước khi gắn bó, hãy xét kỹ trung tâm mình định tựa có xứng không.',
    advice: 'Chọn liên minh bằng câu hỏi kép: người/tổ chức ấy có chính trực không, và mình đến với họ đủ sớm – đủ thành không?',
    love: 'Giai đoạn xác lập gắn bó: rõ ràng về cam kết sớm tốt hơn lửng lơ kéo dài. Người đáng tựa là người nhất quán, không phải người ngọt nhất.',
    work: 'Chọn công ty, chọn phe trong tái cấu trúc, chọn đối tác: xét đạo đức của "trung tâm" trước, quyền lợi sau.',
    reflect: ['Bạn đang tựa vào ai/cái gì — và nó có xứng để tựa không?', 'Cơ hội gắn bó nào đang mở mà bạn cứ chần chừ cho tới lúc thành kẻ đến muộn?'],
  },
  {
    id: 9,
    slug: 'phong-thien-tieu-suc',
    name: 'Tiểu Súc',
    nameVi: 'Phong Thiên Tiểu Súc',
    binary: '110111',
    keyTags: ['tích lũy nhỏ', 'kìm nhẹ', 'chưa mưa'],
    tuong: 'Gió bay trên trời — mây dày mà chưa mưa. Sức chứa còn nhỏ, chỉ kìm được tạm, chưa giải quyết được tận gốc.',
    core: 'Tiểu Súc là thế cục "gần được mà chưa": nguồn lực của bạn mới đủ kìm hãm, điều chỉnh việc nhỏ, chưa đủ xoay chuyển cục diện. Cảm giác bứt rứt "mây dày thế mà chưa mưa" chính là tâm trạng của quẻ. Kinh Dịch khuyên giai đoạn này đừng cố làm cú lớn — hãy tích từng chút: từng kỹ năng, từng đồng vốn, từng mối quan hệ, từng chỉnh sửa nhỏ.',
    advice: 'Hạ kỳ vọng từ "thay đổi cục diện" xuống "tốt hơn 1% mỗi ngày". Việc lớn chưa đến hạn — việc nhỏ đang rất sẵn.',
    love: 'Chưa phải lúc ép chuyện lớn (cưới hỏi, ra mắt, chuyển giai đoạn) — vun từng bữa cơm, từng thói quen tốt trước.',
    work: 'Nguồn lực mỏng: tối ưu cái đang có, cải tiến quy trình nhỏ, để dành đạn cho thời điểm chín.',
    reflect: ['Bạn đang sốt ruột với "cơn mưa" nào — và trong lúc chờ, tích được gì mỗi ngày?', 'Cú lớn bạn định làm: nguồn lực hiện tại gánh nổi chưa, hay cần thêm một mùa tích lũy?'],
  },
  {
    id: 10,
    slug: 'thien-trach-ly',
    name: 'Lý',
    nameVi: 'Thiên Trạch Lý',
    binary: '111011',
    keyTags: ['đi trên băng mỏng', 'đúng lễ', 'cẩn trọng mà vẫn tiến'],
    tuong: 'Đầm dưới trời cao — kẻ dưới đi sau cọp dữ. Giẫm lên đuôi hổ mà hổ không cắn: nhờ bước đi đúng phép.',
    core: 'Lý là thế cục đi qua vùng nguy hiểm có quyền lực lớn hơn mình: sếp khó, đối tác mạnh, luật lệ nghiêm, dư luận dữ. Điều đáng quý của quẻ: nó KHÔNG khuyên quay đầu — đường vẫn đi được, miễn đúng cách. "Đúng lễ" ở đây là hiểu vai của mình, tôn trọng ranh giới của bên mạnh hơn, nói năng đúng mực — không phải khúm núm, mà là khéo có nguyên tắc.',
    advice: 'Tiến tiếp, nhưng soi từng bước: chỗ nào là "đuôi hổ" (điểm nhạy cảm của người/hệ thống có quyền), tránh giẫm vào đó là đi qua an toàn.',
    love: 'Đang ở giai đoạn nhạy cảm (ra mắt gia đình khó tính, hàn gắn sau tổn thương): chân thành + đúng mực thắng mọi chiến thuật.',
    work: 'Làm việc với cấp trên quyền lực, khách hàng lớn, cơ quan quản lý: chuẩn bị kỹ, đúng quy trình, lời nói giữ phép — vẫn giữ được lập trường.',
    reflect: ['"Đuôi hổ" trong tình huống của bạn nằm chính xác ở đâu?', 'Cẩn trọng của bạn đang là khéo léo có nguyên tắc, hay đã thành sợ sệt đánh mất mình?'],
  },
  {
    id: 11,
    slug: 'dia-thien-thai',
    name: 'Thái',
    nameVi: 'Địa Thiên Thái',
    binary: '000111',
    keyTags: ['hanh thông', 'âm dương giao hòa', 'thời thuận'],
    tuong: 'Đất trên trời dưới — khí trời bốc lên, khí đất lắng xuống, hai bên giao nhau. Vạn vật nhờ giao hòa mà thông suốt.',
    core: 'Thái là thế cục thuận nhất trong 64 quẻ: trên dưới hiểu nhau, trong ngoài thông nhau, việc nhỏ ra đi việc lớn kéo về. Khi gặp quẻ này, điều cần làm không phải là hỏi "có tốt không" mà là tận dụng thời thuận để làm những việc khó nhất — hòa giải mối căng cũ, khởi động dự án lớn, nói lời khó nói. Và một lời tỉnh táo cài sẵn: không có mặt đất nào bằng mãi, không có sự đi nào không trở lại — thịnh cực sẽ chuyển, nên xây đệm ngay trong lúc thịnh.',
    advice: 'Dùng thời thuận cho việc khó: những cuộc trò chuyện, quyết định, khởi đầu mà lúc khó khăn bạn không dám làm. Đồng thời để dành một phần thành quả làm đệm.',
    love: 'Giai đoạn ấm và thông — đúng lúc bàn chuyện lớn, gặp hai nhà, hàn gắn điều cũ. Đừng phung phí thời ấm vào sự chủ quan.',
    work: 'Mọi thứ trơn tru: chốt deal lớn, mở rộng, đề bạt. Trích một phần lợi nhuận/thành quả làm quỹ phòng khi gió đổi.',
    reflect: ['Việc khó nào bạn đã hoãn lâu — mà thời thuận này chính là lúc làm?', 'Bạn đang xây "đệm" gì cho lúc chu kỳ đổi chiều?'],
  },
  {
    id: 12,
    slug: 'thien-dia-bi',
    name: 'Bĩ',
    nameVi: 'Thiên Địa Bĩ',
    binary: '111000',
    keyTags: ['bế tắc', 'trên dưới không thông', 'thu mình giữ đức'],
    tuong: 'Trời cứ ở trên, đất cứ ở dưới — hai khí không giao nhau, vạn vật tắc nghẽn. Người quân tử lúc này thu đức vào trong, tránh phô trương.',
    core: 'Bĩ là ảnh ngược của Thái: kênh liên lạc đứt, trên nói dưới không nghe, thật giả lẫn lộn, kẻ xấu đắc thế. Kinh Dịch không bảo bạn "cố lên" trong thế này — nó bảo: nhận diện đúng rằng đây là mùa tắc, thu mình lại, giữ phẩm chất, đừng đem điều quý ra phơi giữa chợ loạn. Bĩ cực thái lai — chính lời quẻ cũng hứa thế tắc không kéo dài mãi; việc của bạn là còn nguyên vẹn khi trời đất giao lại.',
    advice: 'Ngừng cố thuyết phục những kênh đã tắc. Rút năng lượng về: củng cố sức khỏe, kỹ năng, tiền dự phòng, vài quan hệ thật — và chờ chuyển mùa.',
    love: 'Nói mãi không thông thì tạm ngừng tranh luận, giữ tử tế tối thiểu. Có những bế tắc chỉ tan khi cả hai bớt nói và thời điểm đổi.',
    work: 'Môi trường trì trệ, đề xuất nào cũng chìm: đừng đốt mình để chứng minh. Làm tốt phần mình, học thêm, và quan sát cửa khác.',
    reflect: ['Đâu là phần bạn đổi được trong thế tắc này — và đâu là phần chỉ thời gian đổi được?', 'Nếu mùa tắc kéo dài 6 tháng nữa, bạn muốn bước ra khỏi nó với thứ gì còn nguyên?'],
  },
  {
    id: 13,
    slug: 'thien-hoa-dong-nhan',
    name: 'Đồng Nhân',
    nameVi: 'Thiên Hỏa Đồng Nhân',
    binary: '111101',
    keyTags: ['đồng tâm', 'hợp tác rộng', 'việc chung trên việc riêng'],
    tuong: 'Lửa bốc lên cùng hướng với trời — sáng mà cùng chiều. Kết giao giữa nơi đồng rộng, không phải trong xó nhà: sự đồng lòng quang minh.',
    core: 'Đồng Nhân là thế cục hợp tác đúng nghĩa: những người khác nhau cùng nhìn về một việc chung lớn hơn lợi riêng từng người. Quẻ nhấn chữ "ở đồng rộng" — liên minh bền phải mở và quang minh; kết bè trong bóng tối, theo phe cánh họ hàng thân hữu thì lời quẻ chê thẳng là "đồng nhân trong tông tộc, hối tiếc". Cùng chí hướng quan trọng hơn cùng phe.',
    advice: 'Tìm đồng minh bằng mục tiêu chung công khai, không bằng quan hệ riêng. Việc chung minh bạch từ đầu — tiền bạc, công sức, danh phận.',
    love: 'Hai người là một đội trước thế giới: cùng nhìn một hướng quan trọng hơn nhìn nhau mãi. Xây một "việc chung" để cùng làm.',
    work: 'Thời điểm tốt cho liên doanh, hợp tác liên phòng ban, dự án cộng đồng. Nguyên tắc: minh bạch sớm để khỏi tố nhau muộn.',
    reflect: ['Liên minh của bạn đang đứng trên mục tiêu chung hay trên sự thân quen?', 'Điều gì cần được minh bạch ngay bây giờ để 6 tháng nữa không thành mâu thuẫn?'],
  },
  {
    id: 14,
    slug: 'hoa-thien-dai-huu',
    name: 'Đại Hữu',
    nameVi: 'Hỏa Thiên Đại Hữu',
    binary: '101111',
    keyTags: ['sở hữu lớn', 'thịnh mà khiêm', 'dùng của đúng chỗ'],
    tuong: 'Lửa sáng trên trời cao — mặt trời giữa thiên không, soi khắp, vạn vật phơi bày. Của cải và danh tiếng đang ở độ sáng.',
    core: 'Đại Hữu là thế cục "có lớn": tài sản, danh tiếng, ảnh hưởng đang về tay bạn. Quẻ này không cảnh báo sự giàu — nó cảnh báo cách cầm sự giàu: mặt trời soi mọi thứ thì chính bạn cũng đang bị soi. Càng có nhiều, một chút kiêu hay một chút mờ ám càng bị nhìn thấy rõ. Người giữ được Đại Hữu là người "át điều dữ, dương điều lành" — dùng vị thế của mình để chặn cái xấu và nâng cái tốt quanh mình.',
    advice: 'Cầm sự thịnh bằng hai tay: một tay minh bạch (mọi thứ chịu được ánh sáng), một tay rộng rãi (của lớn phải chảy, không phải chất đống).',
    love: 'Đời sống đủ đầy dễ che một câu hỏi: hai người còn giàu thời gian cho nhau không? Của cải nên là nền cho tình cảm, không phải lớp cách âm.',
    work: 'Đang ở đỉnh nguồn lực: đầu tư cho người, chia quyền lợi sòng phẳng, xây uy tín dài hạn. Mọi khoản mờ ám lúc này đắt gấp mười lúc khó.',
    reflect: ['Nếu mọi việc bạn làm tuần này bị phơi giữa nắng, có việc nào bạn muốn giấu?', 'Sự dư dả hiện tại đang chảy đi đâu — có nhánh nào chảy về người khác không?'],
  },
  {
    id: 15,
    slug: 'dia-son-khiem',
    name: 'Khiêm',
    nameVi: 'Địa Sơn Khiêm',
    binary: '000100',
    keyTags: ['khiêm tốn', 'núi trong đất', 'đức bền nhất'],
    tuong: 'Núi cao mà chịu nằm dưới đất — có thực lực lớn nhưng không phô. Quẻ duy nhất trong 64 quẻ mà cả sáu hào đều không xấu.',
    core: 'Khiêm là quẻ được Kinh Dịch ưu ái nhất: hào nào cũng lành. Lý do rất đời: người có thực lực mà không phô thì ai cũng muốn nâng, không ai muốn hạ — trời đất quỷ thần lẫn người đời đều "ghét đầy mà ưa vơi". Nhưng chú ý: Khiêm là NÚI trong đất — phải có núi thật rồi mới nói chuyện giấu núi. Khiêm tốn không phải tự hạ thấp, mà là có thật và không cần khoe.',
    advice: 'Cứ làm cho giỏi thật, rồi để người khác phát hiện ra bạn. Nhận ít hơn phần mình một chút trong chia chác nhỏ — và nhận được lòng người trong cuộc lớn.',
    love: 'Người biết nhận sai trước, biết nói "mình chưa hiểu hết" — là người giữ được quan hệ lâu. Khiêm với người thương không bao giờ là lỗ.',
    work: 'Sau thành tích, ghi công cho đội trước khi nhận về mình. Trong thương lượng, để đối tác giữ thể diện — bạn giữ được hợp đồng sau.',
    reflect: ['"Núi" thật của bạn là gì — và bạn có đang cần phô nó ra không?', 'Lần gần nhất bạn nhường công khai và được lại âm thầm là khi nào?'],
  },
  {
    id: 16,
    slug: 'loi-dia-du',
    name: 'Dự',
    nameVi: 'Lôi Địa Dự',
    binary: '001000',
    keyTags: ['hứng khởi', 'chuẩn bị trước', 'thuận đà mà động'],
    tuong: 'Sấm vang trên mặt đất — khí xuân bừng dậy, lòng người phấn chấn. Người xưa nhìn tượng này mà đặt nhạc, tế lễ: khơi niềm vui chung đúng cách.',
    core: 'Dự là thế cục hứng khởi: có đà, có khí thế, lòng người đang lên. Quẻ này dạy dùng niềm vui làm lực kéo — việc gì thuận lòng người thì khởi động dễ như sấm đầu xuân. Nhưng chữ Dự còn nghĩa thứ hai: dự bị. Niềm vui không có chuẩn bị thì thành vui miệng; hứng khởi nhất là lúc dễ hứa bừa, tiêu bừa, quyết bừa nhất.',
    advice: 'Tận dụng khí thế để khởi động việc cần đông người ủng hộ — nhưng viết kế hoạch TRƯỚC khi tuyên bố, đừng để cơn hứng viết thay.',
    love: 'Giai đoạn vui vẻ phấn khởi — đẹp để tạo kỷ niệm chung. Chỉ đừng để lời hứa lúc cao hứng thành món nợ lúc bình thường.',
    work: 'Ra mắt, kick-off, truyền thông nội bộ — thiên thời. Cài một người "gác thực tế" trong nhóm để khí thế không thổi bay ngân sách.',
    reflect: ['Cơn hứng hiện tại đang đứng trên kế hoạch nào — hay đứng trên chính nó?', 'Bạn đang chuẩn bị gì cho ngày thứ 30, khi khí thế ban đầu nguội?'],
  },
  {
    id: 17,
    slug: 'trach-loi-tuy',
    name: 'Tùy',
    nameVi: 'Trạch Lôi Tùy',
    binary: '011001',
    keyTags: ['thuận theo thời', 'biết theo đúng người', 'linh hoạt'],
    tuong: 'Sấm nằm trong đầm — mùa thu sấm rút về nghỉ, thuận theo mùa. Mạnh mà biết nằm xuống đúng lúc: đó là theo thời.',
    core: 'Tùy là nghệ thuật đi theo: theo thời thế, theo người xứng đáng, theo dòng chảy đang mạnh hơn mình. Văn hóa đề cao "làm chủ" khiến chữ "theo" mang tiếng oan — nhưng Kinh Dịch chỉ rõ: biết theo đúng lúc đúng người là một năng lực, kẻ gì cũng muốn dẫn thì gãy. Điều kiện của Tùy: theo với con mắt mở (chọn điều chính đáng mà theo) chứ không nhắm mắt xuôi dòng.',
    advice: 'Xác định ai/xu hướng nào đang đáng theo trong việc của bạn — rồi theo cho trọn, đừng theo nửa vời kiểu vừa theo vừa cản.',
    love: 'Có giai đoạn nên để người kia dẫn — chọn nhà, chọn hướng đi — và sự tin tưởng ấy chính là một món quà. Theo nhau luân phiên là nhịp của đôi bền.',
    work: 'Xu hướng ngành đang rõ: thuận theo và học nhanh thắng cố thủ cách cũ. Theo leader giỏi một chặng cũng là chiến lược, không phải thua kém.',
    reflect: ['Bạn đang cản dòng nào chỉ vì muốn giữ cảm giác làm chủ?', 'Ai/điều gì quanh bạn đang xứng đáng được bạn theo hết mình một chặng?'],
  },
  {
    id: 18,
    slug: 'son-phong-co',
    name: 'Cổ',
    nameVi: 'Sơn Phong Cổ',
    binary: '100110',
    keyTags: ['sửa điều hư', 'dọn tồn đọng', 'gánh việc cũ'],
    tuong: 'Gió quẩn dưới chân núi — không khí tù đọng lâu ngày sinh mục ruỗng. Cái bát để lâu sinh mọt: đến lúc phải dọn.',
    core: 'Cổ là thế cục dọn dẹp di sản hỏng: việc tồn đọng lâu năm, thói quen mục từ đời nào, hệ thống rệu rã do người trước (hoặc chính mình của ngày trước) để lại. Quẻ này có hai tin: tin xấu là mục ruỗng không tự lành; tin tốt là lời quẻ nói "Cổ, nguyên hanh" — dám bắt tay sửa thì rất hanh thông, vì mọi thứ đã xấu đến mức chỉ còn đường tốt lên. Sửa việc cha để lại không phải bất hiếu — là nối tiếp có trách nhiệm.',
    advice: 'Chọn một đống tồn đọng cụ thể, đặt lịch dọn dứt điểm. Trước khi sửa, hiểu vì sao nó hỏng ("trước giáp ba ngày"); sau khi sửa, theo dõi đủ lâu ("sau giáp ba ngày").',
    love: 'Mối quan hệ có "kho tồn đọng" — chuyện cũ chưa nói hết, hờn xưa chưa tháo. Mở kho ra dọn cùng nhau, từng món một, đừng dọn một lần cả kho.',
    work: 'Nợ kỹ thuật, quy trình lỗi thời, hồ sơ tồn: nhận diện thẳng, lập danh sách, xử theo ưu tiên. Người dám dọn đống cũ thường được tin giao việc mới.',
    reflect: ['Đống tồn đọng nào bạn đã quen sống chung đến mức quên nó đang mục?', 'Nếu chỉ dọn được một thứ trong quý này, dọn thứ gì thì các thứ khác dễ theo?'],
  },
  {
    id: 19,
    slug: 'dia-trach-lam',
    name: 'Lâm',
    nameVi: 'Địa Trạch Lâm',
    binary: '000011',
    keyTags: ['vận đang lên', 'tới gần', 'thịnh có hạn kỳ'],
    tuong: 'Đất cao nhìn xuống đầm — người trên đến gần kẻ dưới, dương khí đang lớn dần. Thế đi lên, như tháng giêng tháng hai của năm.',
    core: 'Lâm là thế cục đang lên: ảnh hưởng của bạn lan rộng, người tìm đến, cơ hội xếp hàng. Quẻ khuyên "đến gần": thời này càng sát thực tế, sát con người càng tốt — đừng lãnh đạo từ xa, đừng yêu từ xa, đừng quản lý qua báo cáo. Và một lời nhắc hiếm có trong Kinh Dịch — quẻ ghi rõ hạn kỳ: "đến tháng tám thì hung", nghĩa là thế thịnh nào cũng có mùa, dùng mùa xuân của mình cho đáng.',
    advice: 'Xuống hiện trường, gặp người thật, nghe chuyện thật. Vận đang lên là lúc gieo những hạt cần nhiều năm — vì đủ nắng.',
    love: 'Tình cảm đang nồng: hiện diện thật nhiều (thời gian, da thịt, bữa cơm) thay vì tin nhắn. Nồng độ hôm nay là vốn cho mùa nguội sau này.',
    work: 'Đà tốt: mở rộng quan hệ khách, đào tạo lớp kế cận, đi thực địa. Đặt lịch "kiểm mùa" sau 6 tháng — thế nào rồi cũng đổi.',
    reflect: ['Bạn đang "đến gần" hay đang điều hành mọi thứ từ xa?', 'Nếu thế thuận này còn đúng một mùa, bạn ưu tiên gieo hạt nào?'],
  },
  {
    id: 20,
    slug: 'phong-dia-quan',
    name: 'Quán',
    nameVi: 'Phong Địa Quán',
    binary: '110000',
    keyTags: ['quan sát', 'nhìn lại mình', 'làm gương'],
    tuong: 'Gió thổi trên mặt đất — đi qua khắp nơi, chạm mọi thứ mà soi xét. Người đứng trên đài cao: nhìn xuống để hiểu, và bị nhìn lên để noi.',
    core: 'Quán là thế cục dừng-để-nhìn: trước khi hành động tiếp, cần một vòng quan sát tử tế — nhìn đại cục, nhìn người, và khó nhất là nhìn lại chính mình ("quán ngã sinh" — xem đời sống của ta). Quẻ còn một tầng nữa: ở vị trí có người nhìn vào, chính sự đứng đắn của bạn là lời dạy không cần nói. Lời quẻ tả cảnh tế lễ vừa rửa tay xong, chưa dâng lễ vật — khoảnh khắc nghiêm trang nhất: giữ được sự nghiêm cẩn ấy thì người dưới tự ngưỡng vọng.',
    advice: 'Lùi lại một nhịp lấy tầm nhìn: dữ liệu nói gì, người im lặng đang nghĩ gì, và chính mình đang sống có khớp điều mình nói không.',
    love: 'Quan sát người kia một tuần như mới gặp: họ đang vui khổ vì điều gì? Nhiều mối quan hệ thiếu không phải tình — thiếu sự nhìn thấy.',
    work: 'Trước quyết định lớn: một vòng thực địa, một vòng số liệu, một vòng tự vấn. Ở vai quản lý: đội của bạn đang học từ hành vi của bạn nhiều hơn từ lời bạn.',
    reflect: ['Nếu tự quan sát mình như người ngoài một ngày, bạn sẽ thấy gì lệch giữa nói và làm?', 'Ai đang âm thầm nhìn bạn làm gương — và tấm gương đang chiếu gì?'],
  },
  {
    id: 21,
    slug: 'hoa-loi-phe-hap',
    name: 'Phệ Hạp',
    nameVi: 'Hỏa Lôi Phệ Hạp',
    binary: '101001',
    keyTags: ['cắn vỡ vật cản', 'xử lý dứt điểm', 'công minh'],
    tuong: 'Sấm và chớp gặp nhau — uy và sáng cùng lúc. Như hàm răng cắn vỡ vật cứng kẹt giữa: phải cắn xuyên qua thì hai hàm mới khép lại được.',
    core: 'Phệ Hạp là thế cục có vật cản cứng nằm chình ình giữa đường: một người phá đám, một khúc mắc pháp lý, một ung nhọt trong tổ chức, một thói nghiện trong chính mình. Quẻ nói thẳng: thứ này không tự tan — phải cắn vỡ, tức xử lý trực diện và dứt điểm. Nhưng "cắn" phải kèm "sáng": xử đúng người đúng tội đúng mức, công khai minh bạch — uy không có minh thì thành bạo.',
    advice: 'Gọi tên chính xác vật cản, xử một lần cho xong với chứng cứ và quy tắc rõ ràng. Cắn nửa miệng rồi nhả là cách làm vật cản cứng thêm.',
    love: 'Có một "vật kẹt" giữa hai người (người thứ ba, món nợ, một lời nói dối cũ) — nó cần được xử dứt điểm, không phải được im lặng bọc lại.',
    work: 'Nhân sự độc hại, hợp đồng mập mờ, sai phạm kéo dài: xử theo quy trình, đủ bằng chứng, không trì hoãn. Kỷ luật công minh là bảo vệ người tốt.',
    reflect: ['Vật cản nào bạn đã "ngậm" lâu mà không cắn — và nó đang làm mọi thứ không khép lại được?', 'Cách xử của bạn đủ cả uy lẫn minh chưa, hay đang thiếu một vế?'],
  },
  {
    id: 22,
    slug: 'son-hoa-bi',
    name: 'Bí',
    nameVi: 'Sơn Hỏa Bí',
    binary: '100101',
    keyTags: ['trang sức', 'hình thức vừa độ', 'đẹp phục vụ chất'],
    tuong: 'Lửa cháy dưới chân núi — ánh lửa tô điểm cho núi thêm đẹp lúc hoàng hôn, nhưng không soi xa được. Vẻ đẹp có giới hạn của nó.',
    core: 'Bí là quẻ của hình thức: bao bì, trang phục, lễ nghi, cách trình bày. Kinh Dịch không khinh cái đẹp — quẻ nói "Bí, hanh": chăm chút hình thức là việc thông suốt, vì người đời gặp nhau qua lớp ngoài trước. Nhưng nó giới hạn ngay: "việc nhỏ thì nên" — trang sức làm đẹp cái có thật, không thay được cái thật. Đỉnh cao của quẻ nằm ở hào trên: "trang sức bằng màu trắng" — đẹp nhất là khi gần như không trang điểm nữa.',
    advice: 'Đầu tư cho trình bày — hồ sơ, sản phẩm, hình ảnh — đến mức "tử tế", rồi dừng. Mỗi giờ đánh bóng thêm hãy đổi bằng một giờ làm dày phần ruột.',
    love: 'Những nghi thức nhỏ (hẹn đẹp, lời chúc, quà tinh tế) nuôi cảm xúc thật. Nhưng nếu phải diễn hạnh phúc cho người ngoài xem — đó là Bí đã lấn chất.',
    work: 'Pitch, thương hiệu, giao diện: đáng đầu tư đúng mức. Câu kiểm: nếu lột hết lớp đẹp, sản phẩm còn đứng được không?',
    reflect: ['Thứ gì của bạn đang đẹp vỏ hơn ruột — và ngược lại, ruột tốt nào đang bị vỏ xuềnh xoàng làm thiệt?', 'Bạn đang trang trí để tôn cái thật, hay để che cái thiếu?'],
  },
  {
    id: 23,
    slug: 'son-dia-bac',
    name: 'Bác',
    nameVi: 'Sơn Địa Bác',
    binary: '100000',
    keyTags: ['tiêu mòn', 'giữ hạt giống', 'không nên hành động'],
    tuong: 'Núi đứng trơ trên đất bằng — chân núi bị xói dần, từng lớp lở xuống. Năm hào âm ăn lên, chỉ còn một hào dương trên đỉnh: quả cuối cùng trên cây.',
    core: 'Bác là thế cục tiêu mòn: cái cũ đang lở từng mảng — vị thế, sức khỏe, một mối quan hệ, một mô hình làm ăn. Quẻ nói rất thật: "không lợi đi đâu cả" — trong thế lở, càng vùng vẫy càng sụt nhanh. Nhưng Kinh Dịch cài một hình ảnh cứu rỗi ở hào cuối: "thạc quả bất thực" — quả lớn không bị ăn, tức còn một hạt giống. Việc của bạn lúc này không phải cứu cả mùa đã hỏng, mà là nhận diện và giữ cho được hạt giống ấy.',
    advice: 'Ngừng đổ thêm nguồn lực vào phần đang lở. Kiểm kê: thứ gì là "quả cuối" đáng giữ (kỹ năng lõi, vốn liếng, người tri kỷ, sức khỏe) — dồn hết về đó.',
    love: 'Nếu một mối quan hệ đang mòn từng lớp, câu hỏi không phải "cứu thế nào" mà là "hạt giống nào còn thật" — có khi là tình bạn, có khi là bài học mang đi.',
    work: 'Mô hình cũ đang hết thời: thu hẹp có trật tự, giữ tài sản lõi, đừng bơm tiền cứu phần không cứu được. Mùa sau gieo từ hạt đã giữ.',
    reflect: ['Phần nào trong đời bạn đang lở mà bạn vẫn bơm sức vào vì tiếc?', '"Quả cuối cùng" của bạn là gì — nó đã được cất chỗ an toàn chưa?'],
  },
  {
    id: 24,
    slug: 'dia-loi-phuc',
    name: 'Phục',
    nameVi: 'Địa Lôi Phục',
    binary: '000001',
    keyTags: ['hồi phục', 'dương khí trở lại', 'bắt đầu lại từ gốc'],
    tuong: 'Sấm nằm trong lòng đất — đông chí, ngày ngắn nhất, nhưng chính hôm ấy dương khí bắt đầu sinh trở lại. Một hào dương mọc dưới năm hào âm.',
    core: 'Phục là tin mừng sau quẻ Bác: chu kỳ đã chạm đáy và quay đầu. Sức khỏe nhúc nhích hồi, lòng tin nhen lại, cơ hội đầu tiên ló sau chuỗi ngày xám. Quẻ dặn cách ứng xử với mầm non: ngày đông chí người xưa đóng cửa ải, nghỉ buôn bán — nghĩa là che chắn cho cái mới sinh, đừng bắt nó gánh việc nặng ngay. Và nét đẹp nhất của Phục: "bất viễn phục" — lạc đường mà quay lại sớm thì không lỗi gì; quay đầu chính là một dạng dũng cảm.',
    advice: 'Nhận diện mầm hồi phục và nuôi nó nhỏ nhẹ: thói quen 15 phút, đơn hàng đầu tiên, buổi nói chuyện tử tế đầu tiên. Đừng tăng tải vội.',
    love: 'Sau giai đoạn lạnh, một tín hiệu ấm vừa nhen — đáp lại nó dịu dàng và đừng đào chuyện cũ ngay. Lửa mới nhóm sợ nhất gió to.',
    work: 'Đáy đã qua: khởi động lại bằng phiên bản nhỏ của kế hoạch, đo từng tuần. Sai thì quay đầu sớm — chi phí quay đầu rẻ nhất ở đoạn này.',
    reflect: ['Tín hiệu hồi phục nào vừa ló mà bạn suýt bỏ qua vì còn mải nhìn đống đổ?', 'Có con đường nào bạn biết là lạc mà chưa quay đầu — càng để lâu càng đắt?'],
  },
  {
    id: 25,
    slug: 'thien-loi-vo-vong',
    name: 'Vô Vọng',
    nameVi: 'Thiên Lôi Vô Vọng',
    binary: '111001',
    keyTags: ['không vọng tưởng', 'thuận tự nhiên', 'thành thật trước thời'],
    tuong: 'Sấm vang dưới trời — vạn vật theo mùa mà sinh trưởng, không vật nào "ăn gian" được tiến trình của trời.',
    core: 'Vô Vọng nghĩa là không càn bậy, không vọng tưởng: làm đúng việc của mình, theo đúng lẽ, không mưu cầu kết quả vượt quá phần thật của mình. Quẻ hứa "nguyên hanh" cho người sống kiểu ấy — và cảnh báo tai họa cho kẻ rời chính đạo. Riêng quẻ này có một góc an ủi đặc biệt: "vô vọng chi tai" — tai bay vạ gió đến với cả người không làm gì sai (như trâu buộc bị khách qua đường dắt mất); gặp chuyện ấy thì đừng tự dằn vặt tìm lỗi mình, cũng đừng chữa lung tung — giữ nếp cũ rồi nó tự qua.',
    advice: 'Làm hết phần mình một cách ngay thẳng rồi để kết quả theo nhịp của nó. Gặp vạ không do mình: không hoảng, không tự trách, không "uống thuốc bừa".',
    love: 'Yêu không kịch bản: chân thật về mình ngay từ đầu, không diễn vai để được chọn. Người đến vì vai diễn sẽ đi khi vãn tuồng.',
    work: 'Làm đúng chuyên môn, báo đúng số liệu, hứa đúng khả năng. Khủng hoảng không do mình gây: minh bạch và giữ nhịp, đừng đổi chiến lược trong hoảng loạn.',
    reflect: ['Kỳ vọng nào của bạn đang vượt quá phần việc bạn thật sự làm?', 'Chuyện không may gần đây: bao nhiêu phần do bạn, bao nhiêu phần chỉ là trâu buộc gặp khách qua đường?'],
  },
  {
    id: 26,
    slug: 'son-thien-dai-suc',
    name: 'Đại Súc',
    nameVi: 'Sơn Thiên Đại Súc',
    binary: '100111',
    keyTags: ['tích lũy lớn', 'nén để bật xa', 'học từ người xưa'],
    tuong: 'Trời bị chứa trong núi — sức mạnh khổng lồ được nén giữ trong khuôn vững. Năng lượng lớn cộng kỷ luật lớn.',
    core: 'Đại Súc là tích lũy ở tầm lớn: không phải để dành vài đồng, mà là nén cả một nguồn lực mạnh — tài năng, vốn, tham vọng — vào khuôn kỷ luật để sau này bật xa. Quẻ có lời khuyên lạ: "không ăn ở nhà thì tốt" — nuôi chí lớn thì phải ra khỏi vùng quen, dấn vào việc lớn ("lợi vượt sông lớn"). Và một nguồn tích lũy hay bị quên: "học lời nói, việc làm của người xưa để nuôi đức mình" — đọc người đi trước cũng là tích vốn.',
    advice: 'Giai đoạn nén lò xo: luyện kỹ năng khó, gom vốn dày, đọc sâu. Chấp nhận chưa bung ngay — nén đủ thì một cú bật bằng người khác đi mười bước.',
    love: 'Xây gốc dày cho quan hệ: hiểu gia đình nhau, thống nhất chuyện tiền, rèn cách cãi nhau tử tế. Cặp có "vốn tích" dày chịu được giông lớn.',
    work: 'Đầu tư dài: bằng cấp khó, sản phẩm gốc, hạ tầng. Ra khỏi vùng an toàn để học việc lớn — đừng quanh quẩn "ăn ở nhà".',
    reflect: ['Bạn đang nén lò xo hay đang để nguồn lực rò rỉ qua trăm việc vặt?', 'Người đi trước nào đáng được bạn "đọc" kỹ như một cuốn sách tích vốn?'],
  },
{
    id: 27,
    slug: 'son-loi-di',
    name: 'Di',
    nameVi: 'Sơn Lôi Di',
    binary: '100001',
    keyTags: ['nuôi dưỡng', 'cẩn thận miệng', 'nuôi đúng thứ'],
    tuong: 'Núi trên sấm dưới — hình chiếc miệng mở (hai hào dương ngoài, bốn hào âm trong). Người quân tử nhìn tượng mà thận trọng lời nói, chừng mực ăn uống.',
    core: 'Di là quẻ của sự nuôi: nuôi thân (ăn uống, ngủ nghỉ), nuôi tâm (điều mình đọc, người mình gần), và nuôi người khác. Quẻ đặt câu hỏi gốc: bạn đang nuôi mình bằng gì — và nuôi ai? "Xem cách nuôi của người ta thì biết người ta" — nhìn vào thứ một người nạp vào miệng và lời người ấy thả ra khỏi miệng là đủ hiểu. Hai cánh cửa cùng một chỗ: thứ đi vào (ăn, đọc, xem) và thứ đi ra (lời nói) đều cần gác.',
    advice: 'Rà lại "thực đơn" của thân và tâm: thứ gì đang nuôi bạn lớn, thứ gì đang nuôi bạn bệnh. Và gác cổng miệng — bớt một lời nóng là tránh mười việc rối.',
    love: 'Nuôi quan hệ bằng khẩu phần hằng ngày: lời tử tế, bữa cơm chung. Lời cay nói lúc giận là món độc mà người kia phải tiêu hóa rất lâu.',
    work: 'Nuôi kỹ năng bằng nguồn vào chất lượng (tài liệu gốc, người giỏi) thay vì lướt vụn vặt. Trong họp: nói ít hơn nghĩ một bậc.',
    reflect: ['Một tuần qua, bạn đã nạp gì vào đầu — nếu in ra thành thực đơn, bạn có dám ăn tiếp?', 'Lời nào bạn hay buột miệng mà sau đó thường phải dọn dẹp?'],
  },
  {
    id: 28,
    slug: 'trach-phong-dai-qua',
    name: 'Đại Quá',
    nameVi: 'Trạch Phong Đại Quá',
    binary: '011110',
    keyTags: ['quá tải lớn', 'cột nóc cong', 'thời phi thường'],
    tuong: 'Đầm nước dâng ngập cả cây — bốn hào dương dồn giữa, hai hào âm hai đầu: cột nóc nặng giữa mà yếu hai đầu, đang oằn.',
    core: 'Đại Quá là thế cục vượt ngưỡng: gánh trên vai đã quá sức kết cấu — việc quá nhiều, cam kết quá lớn, một mình đỡ quá nhiều người. Quẻ không bảo buông hết; nó nói đây là "thời phi thường": hoặc gia cố gấp hai đầu cột (thêm người đỡ, bớt tải, giãn hạn), hoặc dám làm việc phi thường mà thời này đòi hỏi — một quyết định lớn, một cuộc thay đổi cấu trúc. Đứng yên giữa lúc cột cong là lựa chọn tệ nhất.',
    advice: 'Thừa nhận quá tải là chuyện kết cấu, không phải chuyện cố thêm. Hành động ngay: bớt tải, thêm trụ, hoặc thay hẳn cách dựng cột.',
    love: 'Một người đang gồng cả mối quan hệ — tài chính, cảm xúc, đối nội đối ngoại. Nói thật về sức mình trước khi cột gãy thành đổ vỡ to.',
    work: 'Deadline chồng deadline, một người làm vai ba người: đàm phán lại phạm vi ngay tuần này. Hệ thống dựa trên một người gồng là hệ thống đã hỏng.',
    reflect: ['"Cột nóc" của bạn đang cong ở điểm nào — và hai đầu trụ yếu là gì?', 'Việc phi thường mà tình thế này thật sự đòi hỏi là gì: bớt, thêm, hay đổi hẳn?'],
  },
  {
    id: 29,
    slug: 'thuan-kham',
    name: 'Khảm',
    nameVi: 'Thuần Khảm',
    binary: '010010',
    keyTags: ['hiểm chồng hiểm', 'giữ lòng tin', 'qua từng vực một'],
    tuong: 'Nước chồng lên nước — hết vực này tới vực khác. Nhưng nước có nết đáng học: đầy chỗ trũng này rồi mới chảy tiếp, không bao giờ mất bản tính của mình.',
    core: 'Thuần Khảm là quẻ khó nói giảm: hiểm nguy nối tiếp nhau — khó khăn tài chính chồng chuyện sức khỏe, việc rối chồng nhà rối. Kinh Dịch không hứa lối tắt; nó chỉ vào hào dương giữa lòng quẻ: giữa hiểm vẫn có một lõi vững — lòng tin và sự thành thật của chính bạn. Cách qua của nước: không nhảy cóc, đầy từng vực một rồi chảy tiếp; và dù qua bao ghềnh, nước vẫn là nước.',
    advice: 'Đừng cố giải hết mọi vực cùng lúc. Chọn vực trước mặt, "đổ đầy" nó bằng việc làm được hôm nay. Giữ vài kỷ luật nhỏ làm phao: giờ ngủ, bữa ăn, một người để nói thật.',
    love: 'Cùng nhau qua đoạn hiểm: chia sẻ thật trạng thái của mình thay vì gồng cười. Hai người thay phiên làm bờ cho nhau là cách qua vực nhanh nhất.',
    work: 'Khủng hoảng nhiều mặt trận: lập danh sách vực theo thứ tự sống còn, xử từng cái. Truyền thông minh bạch với người liên quan — sự thành thật giữa hiểm là uy tín rẻ nhất mua được.',
    reflect: ['Vực nào trước mặt cần đổ đầy TRƯỚC — và việc đổ hôm nay là gì?', 'Giữa chuỗi khó này, "bản tính nước" nào của bạn nhất quyết không để mất?'],
  },
  {
    id: 30,
    slug: 'thuan-ly',
    name: 'Ly',
    nameVi: 'Thuần Ly',
    binary: '101101',
    keyTags: ['sáng tỏ', 'bám đúng chỗ', 'cháy có nhiên liệu'],
    tuong: 'Lửa chồng lên lửa — sáng rực, nhưng lửa không tự đứng được: nó phải bám vào củi. Sáng đôi, soi khắp bốn phương.',
    core: 'Thuần Ly là quẻ của sự sáng và sự bám: trí tuệ, danh tiếng, sự rực rỡ — tất cả đều như lửa, chỉ tồn tại khi có chỗ bám và có nhiên liệu. Câu hỏi quẻ đặt: ánh sáng của bạn đang bám vào đâu — vào năng lực thật, giá trị thật, hay vào sự chú ý của đám đông (thứ củi cháy nhanh nhất)? Lời quẻ khuyên "nuôi trâu cái thì tốt" — rực rỡ bên ngoài phải đi đôi với nuôi sự nhu thuận, điềm đạm bên trong, kẻo lửa to mà ruột rỗng.',
    advice: 'Kiểm tra nhiên liệu: thứ đang cho bạn năng lượng và danh tiếng có bền không? Đầu tư lại vào củi gộc (năng lực lõi, quan hệ thật) thay vì rơm rạ (sự chú ý).',
    love: 'Tình cảm đang nồng — đẹp; nhưng lửa đôi cần củi đôi: cả hai cùng bỏ vào, không phải một người làm củi cho người kia cháy.',
    work: 'Đang được chú ý: tận dụng để chốt thành quả thật. Người sáng nhất phòng phải là người có củi dày nhất, không phải người phát sáng to nhất.',
    reflect: ['Ánh sáng hiện tại của bạn bám vào củi gì — củi đó còn được bao lâu?', 'Bên trong cái rực rỡ, phần "trâu cái nhu thuận" của bạn có đang được nuôi?'],
  },
  {
    id: 31,
    slug: 'trach-son-ham',
    name: 'Hàm',
    nameVi: 'Trạch Sơn Hàm',
    binary: '011100',
    keyTags: ['cảm ứng', 'rung động chân thành', 'trống lòng để nhận'],
    tuong: 'Đầm nước trên đỉnh núi — núi chịu hạ mình cho nước thấm xuống, nước chịu lắng cho núi nâng lên. Người quân tử lấy sự trống lòng mà tiếp nhận người.',
    core: 'Hàm là quẻ mở phần Hạ Kinh — phần nói về con người và quan hệ — và nó mở bằng rung động: sự cảm nhau chân thật giữa hai bên. Cốt lõi của Hàm nằm ở chữ "hư thụ nhân" — trống lòng mà nhận: muốn cảm được ai, phải dọn bớt định kiến, tính toán, kịch bản trong đầu. Rung động thật không ép được, không diễn được; nó chỉ đến giữa hai khoảng lòng còn chỗ trống.',
    advice: 'Trước cuộc gặp quan trọng, dọn lòng: bớt định kiến sẵn, bớt mưu tính sẵn. Lắng nghe để cảm, không phải để chờ tới lượt nói.',
    love: 'Rung động mới chớm hoặc nhịp cảm cũ đang quay lại — tin vào nó, đi chậm cùng nó. Hôn nhân lâu năm: hẹn hò lại như thuở chưa biết hết về nhau.',
    work: 'Thuyết phục bằng cộng hưởng: hiểu điều đối tác thật sự bận tâm trước khi trình bày điều mình muốn. Người mua cảm trước, gật sau.',
    reflect: ['Lòng bạn còn chỗ trống để cảm người khác không — hay đã chật kín kết luận sẵn?', 'Ai gần đây làm bạn rung động (một ý tưởng, một con người) — bạn đã đáp lại tín hiệu ấy chưa?'],
  },
  {
    id: 32,
    slug: 'loi-phong-hang',
    name: 'Hằng',
    nameVi: 'Lôi Phong Hằng',
    binary: '001110',
    keyTags: ['bền lâu', 'giữ đạo thường', 'đổi mà không dời gốc'],
    tuong: 'Sấm và gió đi cùng nhau — hai thứ chuyển động không ngừng mà lại thành tượng của sự bền. Bền không phải đứng yên; bền là chuyển động theo quy luật không đổi.',
    core: 'Hằng là quẻ của sự lâu dài: hôn nhân, sự nghiệp một đời, thói quen mấy chục năm. Cái nhìn sâu của quẻ: trường tồn không phải bất động — mặt trời lặn mọc, bốn mùa thay nhau, chính nhờ ĐỔI đều đặn mà thành KHÔNG ĐỔI. Một mối quan hệ bền là mối quan hệ biết làm mới theo chu kỳ; một sự nghiệp bền là sự nghiệp đổi cách làm mà giữ nguyên giá trị lõi. Lời quẻ chê hai thái cực: đòi kết quả bền ngay lập tức (hào 1) và bất an đổi chỗ liên tục (hào trên).',
    advice: 'Xác định đâu là gốc không đổi (giá trị, cam kết) và đâu là phần phải đổi theo mùa (cách làm, nhịp sống). Giữ gốc, mềm ngọn.',
    love: 'Bền lâu là một thực hành hằng ngày, không phải lời thề một lần. Làm mới đều đặn những điều nhỏ — đó là cách giữ nguyên điều lớn.',
    work: 'Nghề bền: giá trị lõi giữ chặt, công cụ và phương pháp đổi không tiếc tay. Đứng yên mười năm không phải là thâm niên — là một năm kinh nghiệm lặp mười lần.',
    reflect: ['Trong đời bạn, gốc nào nhất quyết không đổi — và ngọn nào đáng lẽ phải đổi từ lâu?', 'Sự "chung thủy" của bạn với điều gì đó đang là bền vững, hay là ngại thay đổi?'],
  },
  {
    id: 33,
    slug: 'thien-son-don',
    name: 'Độn',
    nameVi: 'Thiên Sơn Độn',
    binary: '111100',
    keyTags: ['lui đúng lúc', 'rút có trật tự', 'giữ mình'],
    tuong: 'Trời lùi xa khỏi đỉnh núi — núi cao mấy cũng không chạm được trời. Người quân tử lánh kẻ tiểu nhân không bằng ghét bỏ, mà bằng sự nghiêm trang giữ khoảng cách.',
    core: 'Độn là nghệ thuật rút lui: thế cục đang xấu đi, phe đối nghịch đang mạnh lên, ở lại cố đấu chỉ thiệt. Kinh Dịch coi rút lui đúng lúc là một chiến công — "Độn mà hanh" — vì lui có trật tự bảo toàn được lực lượng cho ngày quay lại. Điểm tinh tế: lui không phải trốn biệt hay tuyệt giao ồn ào; là từ tốn giãn ra, giữ phép lịch sự, không cho kẻ xấu cớ bám theo. Lui sớm thì ung dung; lui muộn thì thành tháo chạy.',
    advice: 'Nhận diện sớm trận không đáng đánh và rút khi còn chủ động: bàn giao gọn, giữ quan hệ tối thiểu, mang theo bài học và danh dự.',
    love: 'Có những cuộc cãi nên rời khỏi phòng (hẹn quay lại nói khi nguội), có những mối quan hệ độc hại nên giãn dần thay vì tuyên chiến. Khoảng cách cũng là một câu trả lời.',
    work: 'Môi trường xấu đi không cứu được: chuẩn bị bến mới âm thầm, rời đi chuyên nghiệp. Đừng đốt cầu — ngành nào rồi cũng gặp lại nhau.',
    reflect: ['Trận nào bạn đang ở lại chỉ vì sợ mang tiếng bỏ chạy?', 'Nếu phải rút trong 3 tháng tới, hôm nay nên bắt đầu chuẩn bị gì để cuộc rút ấy ung dung?'],
  },
  {
    id: 34,
    slug: 'loi-thien-dai-trang',
    name: 'Đại Tráng',
    nameVi: 'Lôi Thiên Đại Tráng',
    binary: '001111',
    keyTags: ['sức mạnh lớn', 'mạnh phải chính', 'kiêng húc bừa'],
    tuong: 'Sấm vang trên trời — uy thế lừng lẫy. Người quân tử lúc mạnh nhất lại càng không bước ra ngoài khuôn lễ: phi lễ phất lý.',
    core: 'Đại Tráng là thế cục sức mạnh đang dâng: quyền trong tay, tiền trong két, lý lẽ trong miệng, đám đông sau lưng. Quẻ chúc mừng — và lập tức ghìm cương: "lợi trinh" — mạnh chỉ tốt khi chính đáng. Hình ảnh cảnh báo nổi tiếng của quẻ: con dê đực cậy khỏe húc giậu, sừng mắc kẹt vào giậu — tiến không được, lui không xong. Sức mạnh thiếu kiềm chế tự biến mình thành kẻ mắc kẹt.',
    advice: 'Dùng đà mạnh cho việc chính đáng và đã tính kỹ. Trước mỗi cú "húc", hỏi: đây là hàng rào cần húc, hay chỉ là thứ khiến mình ngứa sừng?',
    love: 'Đang ở thế trên (được yêu nhiều hơn, kiếm nhiều hơn): càng phải mềm. Lấy thế mạnh ép người thương là cách nhanh nhất biến tình thành nợ.',
    work: 'Vị thế đang mạnh: đàm phán được giá tốt, nhưng đừng ép đối tác vào đường cùng — kẻ bị ép hôm nay là liên minh chống bạn ngày mai.',
    reflect: ['Sức mạnh hiện tại của bạn đang được dùng vào việc chính đáng cỡ nào?', 'Cú húc nào bạn đang định làm mà nếu kẹt sừng thì rất khó gỡ?'],
  },
  {
    id: 35,
    slug: 'hoa-dia-tan',
    name: 'Tấn',
    nameVi: 'Hỏa Địa Tấn',
    binary: '101000',
    keyTags: ['thăng tiến', 'mặt trời lên', 'tiến trong sáng'],
    tuong: 'Mặt trời mọc lên khỏi mặt đất — càng lên càng sáng, soi rõ vạn vật. Người quân tử nhìn tượng mà tự làm sáng cái đức sáng của mình.',
    core: 'Tấn là quẻ thăng tiến đẹp nhất bộ Dịch: được cấp trên tin, được ban thưởng hậu, "một ngày tiếp kiến ba lần". Điều làm Tấn khác các kiểu lên khác: mặt trời lên KHỎI mặt đất — tiến công khai, đường hoàng, ai cũng thấy, không cần cửa sau. Quẻ nhắc người đang lên hai điều: thứ nhất, lên cùng đội (mặt trời soi vạn vật chứ không soi riêng mình); thứ hai, càng lên cao càng minh bạch, vì bóng của người đứng cao đổ rất xa.',
    advice: 'Nhận đà thăng tiến một cách đường hoàng: làm rõ thành tích, nói cảm ơn đúng người, kéo theo vài người xứng đáng. Tuyệt đối không đi cửa tối trong lúc đang được cửa sáng.',
    love: 'Mối quan hệ đang "lên hạng" — công khai hơn, sâu hơn. Tiến theo nhịp sáng: rõ ràng với nhau và với những người liên quan.',
    work: 'Cửa thăng chức/danh tiếng đang mở: chuẩn bị hồ sơ thành tích thật, nhận vai to hơn. Người cùng lên với đội sẽ đứng lâu hơn người lên một mình.',
    reflect: ['Đà đang lên của bạn có phần nào phải dựa vào sự mờ ám không — nếu có, dừng được không?', 'Ai xứng đáng được bạn kéo lên cùng trong cú tiến này?'],
  },
  {
    id: 36,
    slug: 'dia-hoa-minh-di',
    name: 'Minh Di',
    nameVi: 'Địa Hỏa Minh Di',
    binary: '000101',
    keyTags: ['giấu sáng', 'thời tối', 'giữ lửa trong'],
    tuong: 'Mặt trời lặn vào lòng đất — ánh sáng bị thương. Người quân tử sống giữa đám đông thời tối: dùng sự mờ bên ngoài mà giữ sự sáng bên trong.',
    core: 'Minh Di là thế cục người sáng sống trong thời tối: môi trường không dung người giỏi, nói thật bị ghét, làm đúng bị nghi. Quẻ dạy một kỹ năng sinh tồn cổ xưa: giấu sáng — không phô tài năng và chính kiến ra giữa chỗ nguy, bên ngoài hòa cùng mọi người, bên trong lửa không tắt. Đây không phải sống giả: là biết thời. Văn Vương bị giam vẫn diễn Dịch; Cơ Tử giả điên mà giữ đạo — lời quẻ nhắc đích danh hai con người ấy.',
    advice: 'Trong môi trường chưa an toàn cho sự thẳng: bớt phát ngôn, không tắt chính kiến — ghi chép, rèn nghề, chờ thời. Tìm vài người cùng tần số để lửa có bạn.',
    love: 'Có giai đoạn không nên phơi hết nỗi niềm với người chưa đáng tin trong vòng quen. Chọn đúng một hai người để thật — còn lại giữ sự tử tế vừa phải.',
    work: 'Sếp mới khó lường, văn hóa đấu đá: làm tốt phận sự, tránh thành ngọn cờ, lưu mọi thứ bằng văn bản. Sáng quá giữa thời tối là tự thành bia.',
    reflect: ['Môi trường hiện tại có an toàn cho sự thẳng thắn của bạn không — bằng chứng đâu?', 'Bạn đang giấu sáng để giữ lửa, hay đang để thời tối dập lửa thật?'],
  },
  {
    id: 37,
    slug: 'phong-hoa-gia-nhan',
    name: 'Gia Nhân',
    nameVi: 'Phong Hỏa Gia Nhân',
    binary: '110101',
    keyTags: ['đạo trong nhà', 'trong ấm ngoài êm', 'lời có vật việc có thường'],
    tuong: 'Gió thổi ra từ lửa — hơi ấm trong bếp lan thành gió ra ngoài. Mọi ảnh hưởng ra thế giới đều bắt nguồn từ trong nhà.',
    core: 'Gia Nhân là quẻ của gia đạo: nhà là gốc của mọi thứ khác. Cái nhìn của quẻ rất cấu trúc: nhà yên khi mỗi người đúng vai và ranh giới rõ — không phải vai theo giới tính cứng nhắc, mà là ai gánh gì phải tỏ tường, kỷ cương có mà tình cũng có. Lời Đại Tượng đắt nhất cho thời nay: "lời nói phải có vật, việc làm phải có thường" — trong nhà, nói gì phải có thật, làm gì phải có nếp. Gió ngoài cửa chỉ ấm khi lửa trong bếp thật.',
    advice: 'Muốn chỉnh việc ngoài, soi việc trong trước: vai trong nhà đã rõ chưa, lời trong nhà có thật không, nếp trong nhà có đều không.',
    love: 'Phân vai bằng thỏa thuận chứ không bằng mặc định: tiền ai quản, con ai đưa đón, tết nội ngoại thế nào. Mỗi mặc định không nói ra là một mầm cãi sau này.',
    work: 'Đội nhóm cũng là một "nhà": vai rõ, lời thật, nếp đều. Người quản gia giỏi của một nhóm nhỏ sẽ được giao căn nhà lớn hơn.',
    reflect: ['Trong nhà bạn, vai nào đang mơ hồ và đè lệch lên một người?', 'Lời nói trong nhà bạn dạo này có "có vật" không — hay nhiều lời cho qua chuyện?'],
  },
  {
    id: 38,
    slug: 'hoa-trach-khue',
    name: 'Khuê',
    nameVi: 'Hỏa Trạch Khuê',
    binary: '101011',
    keyTags: ['khác biệt', 'đồng mà dị', 'việc nhỏ thì lành'],
    tuong: 'Lửa bốc lên, đầm lắng xuống — hai chị em ở chung nhà mà chí hướng ngược nhau. Trái nhau, nhưng cùng một mái.',
    core: 'Khuê là thế cục lệch pha: hai người, hai phe, hai hệ giá trị nhìn nhau thấy "sai sai" — vợ chồng khác nết, đồng nghiệp khác não, thế hệ khác sóng. Kinh Dịch không đòi xóa khác biệt; nó chỉ ra "trời đất khác nhau mà cùng làm nên vạn vật" — khác là chất liệu của hợp tác, miễn tìm được điểm giao. Lời khuyên thực dụng của quẻ: thời lệch pha thì "việc nhỏ lành" — đừng đòi thống nhất tư tưởng lớn, hãy hợp tác từ việc nhỏ cụ thể; và cảnh giác ảo giác nhìn-lầm: trong thế Khuê, người ngay dễ bị nhìn thành kẻ gian.',
    advice: 'Ngừng cố cải hóa nhau về một quan điểm. Tìm một việc nhỏ cả hai cùng cần rồi làm chung — sự tin nhau xây từ việc, không từ tranh luận.',
    love: 'Khác nhau không phải án tử của tình — án tử là khinh sự khác của nhau. Đổi câu "sao anh/em lại thế" thành "kể em/anh nghe cách anh/em nhìn".',
    work: 'Hai phòng ban nghịch nhau: bắt đầu bằng một dự án nhỏ chung có lợi đôi bên. Đừng họp để thống nhất triết lý — họp để chia việc cụ thể.',
    reflect: ['Ai đang bị bạn nhìn qua lăng kính "kẻ sai" — và nếu họ ngay thật thì sao?', 'Việc nhỏ nào có thể làm chung với "phe bên kia" ngay tuần này?'],
  },
  {
    id: 39,
    slug: 'thuy-son-kien',
    name: 'Kiển',
    nameVi: 'Thủy Sơn Kiển',
    binary: '010100',
    keyTags: ['đường nghẽn', 'biết dừng trước hiểm', 'quay về tu mình'],
    tuong: 'Nước hiểm trước mặt, núi cao sau lưng — chân khập khiễng giữa đường khó. Người quân tử gặp thế ấy thì quay về sửa mình.',
    core: 'Kiển là thế cục nghẽn đường: tiến gặp hiểm, lùi vướng núi, chân lại đang khập khiễng. Quẻ dạy ba việc theo thứ tự: một — biết dừng (thấy hiểm mà dừng được là trí, không phải nhát); hai — "phản thân tu đức": thời gian nghẽn là thời gian quay vào sửa chính mình, vì ngoài kia không nhúc nhích được thì trong này còn cả công trường; ba — tìm trợ lực: quẻ nói "lợi kiến đại nhân" và lợi hướng tây nam (hướng bằng phẳng, phe đồng minh) — đường khó không phải đường để đi một mình.',
    advice: 'Ngừng húc vào chỗ nghẽn. Chuyển lực về hai việc: sửa phần mình còn yếu, và tìm người đỡ đúng tầm. Khi đường thông, bạn bước ra với đôi chân khác.',
    love: 'Bế tắc kéo dài: tạm ngừng truy vấn nhau, mỗi người quay về sửa phần mình một thời gian — có khi nút thắt tự lỏng vì hai đầu dây đều đổi.',
    work: 'Dự án nghẽn mọi ngả: dừng đốt nguồn lực, nâng cấp nội lực (kỹ năng, quy trình, dữ liệu), tìm cố vấn từng qua đúng đoạn nghẽn ấy.',
    reflect: ['Chỗ nghẽn hiện tại: phần nào của nó nằm trong chính bạn?', 'Ai là "đại nhân" từng đi qua đoạn này mà bạn chưa hỏi?'],
  },
{
    id: 40,
    slug: 'loi-thuy-giai',
    name: 'Giải',
    nameVi: 'Lôi Thủy Giải',
    binary: '001010',
    keyTags: ['tháo gỡ', 'tan băng', 'tha lỗi nhẹ gánh'],
    tuong: 'Sấm động trên mưa — cơn giông nổ ra rồi trời quang, khí bí bách được xả. Người quân tử nhân tượng ấy mà tha lỗi nhỏ, khoan hồng kẻ trót sai.',
    core: 'Giải là khoảnh khắc nút thắt lỏng ra: chuyện căng dịu xuống, bệnh lui, nợ giãn, hiểu lầm có lối thoát. Quẻ dạy hai động tác cho thời điểm này: thứ nhất, làm NHANH — "có chỗ phải đến thì đến sớm tốt hơn": cơ hội tháo gỡ không mở mãi, dây đang lỏng phải gỡ ngay; thứ hai, gỡ xong thì BUÔNG — về lại nhịp thường, đừng ôn nghèo kể khổ, đừng truy cứu tội cũ. Giông đã nổ thì để trời quang; người cứ ở lại trong cơn giông cũ là người tự chọn ướt.',
    advice: 'Liệt kê các nút đang lỏng (món nợ thương lượng được, hiểu lầm giải thích được) và gỡ ngay tuần này. Gỡ xong, tuyên bố đóng hồ sơ — với người khác và với chính mình.',
    love: 'Sau trận cãi lớn là cửa làm lành — bước qua cửa ấy sớm. Và đã tha thì tha hẳn: không lưu "án treo" để dùng lại trong trận sau.',
    work: 'Khủng hoảng vừa qua đỉnh: xử lý tồn đọng dứt điểm, ghi bài học, rồi cho đội ngũ về nhịp bình thường. Đừng để cả công ty sống mãi trong "chế độ khẩn cấp".',
    reflect: ['Nút nào vừa lỏng mà bạn chưa gỡ — chờ gì nữa?', 'Bạn đang giữ "án treo" nào với ai mà đáng lẽ đã đóng hồ sơ?'],
  },
  {
    id: 41,
    slug: 'son-trach-ton',
    name: 'Tổn',
    nameVi: 'Sơn Trạch Tổn',
    binary: '100011',
    keyTags: ['bớt để cân', 'hy sinh có nghĩa', 'giảm mà thành tăng'],
    tuong: 'Đầm tự vơi nước để núi thêm cao — bớt chỗ dưới bồi chỗ trên. Người quân tử nhìn tượng mà bớt giận, chặn dục.',
    core: 'Tổn nghĩa là giảm — và Kinh Dịch nói thẳng một nghịch lý: có những cái giảm làm đời tăng. Giảm chi tiêu để tăng tự do; giảm cam kết để tăng chất lượng; giảm cái tôi để tăng quan hệ; lời Đại Tượng chỉ đích danh hai thứ đáng giảm nhất: cơn giận và lòng ham. Điều kiện của Tổn là chữ THÀNH: bớt với lòng thành — tự nguyện, đúng chỗ, có mục đích — thì "hai giỏ cơm cũng đủ dâng lễ"; bớt kiểu gồng ép, hà tiện vô lối thì chỉ là khổ dồn.',
    advice: 'Chọn chủ động một thứ để giảm trong tháng này (một khoản chi, một cam kết, một thói quen ngốn giờ) và quan sát thứ gì tăng lên nhờ nó.',
    love: 'Bớt một phần "cái đúng của mình" trong cãi vã — quan hệ tăng liền. Hy sinh nhỏ tự nguyện là chất keo; hy sinh để kể công là chất nổ chậm.',
    work: 'Cắt dòng sản phẩm phụ để nuôi dòng chính, bớt họp để tăng giờ làm sâu. Mọi chiến lược giỏi đều là một danh sách những thứ KHÔNG làm.',
    reflect: ['Thứ gì bạn bớt đi mà đời chắc chắn tăng — sao chưa bớt?', 'Cơn giận hay lòng ham nào đang ngốn của bạn nhiều "nước trong đầm" nhất?'],
  },
  {
    id: 42,
    slug: 'phong-loi-ich',
    name: 'Ích',
    nameVi: 'Phong Lôi Ích',
    binary: '110001',
    keyTags: ['tăng ích', 'trên rót xuống dưới', 'thấy tốt thì theo ngay'],
    tuong: 'Gió và sấm cùng chiều — gió mạnh thì sấm vang, sấm vang thì gió giật: hai bên làm lợi cho nhau. Người quân tử thấy điều thiện thì dời theo, có lỗi thì sửa liền.',
    core: 'Ích là quẻ của sự bồi đắp: thời mà việc cho đi tạo vòng xoáy lợi chung — bớt chỗ trên bồi chỗ dưới, người mạnh đỡ người yếu, và lạ thay chính người cho lại lớn nhanh nhất. Đây là thời thuận hiếm có để làm việc lớn ("lợi vượt sông lớn") và đầu tư cho người. Phản xạ mà quẻ luyện cho ta nằm ở Đại Tượng: thấy điều tốt — bắt chước NGAY; thấy mình lỗi — sửa NGAY. Tăng trưởng kép của một con người nằm ở tốc độ hai phản xạ ấy.',
    advice: 'Đang thời được bồi: nhận với lòng biết ơn và lập tức mở vòi chảy tiếp — dạy lại, chia lại, đầu tư xuống. Nước chảy thì trong, ao tù thì đục.',
    love: 'Thời tốt để đầu tư lớn cho nhau: học chung một thứ, xây chung một quỹ, đỡ nhau một chặng nghề. Cho nhau mượn vai thời này, lãi về sau rất dày.',
    work: 'Xin được nguồn lực, gặp được quý nhân: dùng đòn bẩy ấy cho việc dài hạn. Và chia cơ hội cho người dưới — đội lớn thì bệ phóng của bạn lớn.',
    reflect: ['Bạn vừa thấy ai làm một điều rất hay — đã "dời theo" chưa hay chỉ khen rồi thôi?', 'Nguồn lực đang rót vào bạn — bạn rót tiếp đi đâu?'],
  },
  {
    id: 43,
    slug: 'trach-thien-quai',
    name: 'Quải',
    nameVi: 'Trạch Thiên Quải',
    binary: '011111',
    keyTags: ['quyết trừ', 'công khai cảnh báo', 'không cậy vũ lực'],
    tuong: 'Đầm nước dâng lên tận trời — vỡ đê đến nơi. Năm hào dương cùng đẩy hào âm cuối cùng ra: cái xấu chỉ còn một mẩu, nhưng mẩu ấy ở vị trí cao nhất.',
    core: 'Quải là thế cục quyết liệt cuối cùng: điều xấu (một thói quen độc, một kẻ phá hoại, một khối u trong tổ chức) đã suy yếu, chỉ còn một chân đứng — nhưng đứng ở chỗ cao và dai. Quẻ dạy cách trừ nó văn minh: tuyên bố CÔNG KHAI giữa "sân vua" (minh bạch, đúng quy trình, có chứng lý), tự răn mình trước, và tuyệt đối "không lợi tức nhung" — không cậy bạo lực, không dùng thủ đoạn của chính cái xấu để trừ cái xấu. Diệt gần xong là đoạn dễ chủ quan nhất: một mẩu âm còn sót có thể mọc lại cả mùa.',
    advice: 'Trừ dứt điểm bằng quy trình sáng: nêu vấn đề công khai, đủ bằng chứng, đúng kênh. Và đi đến cùng — 90% của việc cai/cắt/trừ là chưa xong.',
    love: 'Một mầm độc trong quan hệ (lời xúc phạm "quen miệng", một liên hệ mập mờ) cần được gọi tên thẳng và chấm dứt hẳn — thỏa hiệp với nó là nuôi nó.',
    work: 'Sai phạm đã rõ: xử công khai đúng quy trình, không dàn xếp ngầm. Dùng thủ đoạn để diệt thủ đoạn là tự thành phiên bản kế tiếp của nó.',
    reflect: ['Cái xấu nào trong đời bạn đang ở mức "còn 10% cuối" — và bạn có đang định buông tha nó vì mệt?', 'Cách bạn định trừ nó có sạch không, hay đang nhiễm chính chất của nó?'],
  },
  {
    id: 44,
    slug: 'thien-phong-cau',
    name: 'Cấu',
    nameVi: 'Thiên Phong Cấu',
    binary: '111110',
    keyTags: ['gặp gỡ bất ngờ', 'mầm nhỏ dưới chân', 'cảnh giác từ sớm'],
    tuong: 'Gió luồn dưới gầm trời — đi khắp nơi, chạm mọi vật. Một hào âm vừa sinh dưới đáy năm hào dương: nhỏ xíu, nhưng đang lớn dần lên.',
    core: 'Cấu là quẻ của cuộc gặp không hẹn: người mới xuất hiện, cơ hội tự gõ cửa, một ý tưởng lạ chen vào đời. Kinh Dịch không bảo đóng cửa — gặp gỡ là cách trời đất giao nhau, "thiên hạ nhờ thế mà văn minh". Nhưng quẻ cảnh báo bằng chính cấu trúc của nó: thứ vừa len vào còn rất nhỏ — và mọi thứ lớn đều từng rất nhỏ. Lời quẻ "gái cứng quá, chớ cưới" nghĩa rộng là: thứ mới đến mà bộc lộ sự lấn lướt ngay từ đầu thì đừng gắn bó lâu dài. Đón cuộc gặp với cửa mở và mắt mở.',
    advice: 'Cứ gặp, cứ nghe — nhưng kiểm tra gốc gác trước khi trao chìa khóa: người mới quen chưa vội hùn vốn, ý tưởng hay chưa vội đặt cược lớn. Quan sát mầm từ lúc nó còn dưới chân.',
    love: 'Cuộc gặp định mệnh có thể thật — nhưng "định mệnh" cần thời gian kiểm chứng như mọi thứ khác. Đi chậm với người tiến quá nhanh.',
    work: 'Đối tác/nhân sự/deal tự tìm đến: đáng mừng và đáng thẩm định. Mầm rủi ro (điều khoản lạ, thói quen xấu nhỏ) phải chặn từ vòng đầu — sau này đắt gấp trăm.',
    reflect: ['Điều gì vừa len vào đời bạn mà bạn chưa kiểm tra gốc gác?', 'Mầm xấu nhỏ nào bạn đang thấy mà tặc lưỡi "có tí xíu, kệ"?'],
  },
  {
    id: 45,
    slug: 'trach-dia-tuy',
    name: 'Tụy',
    nameVi: 'Trạch Địa Tụy',
    binary: '011000',
    keyTags: ['tụ họp', 'gom về một mối', 'phòng bị khi đông'],
    tuong: 'Đầm nước trên mặt đất — nước trăm ngả gom về một chỗ trũng. Người quân tử nhân tượng ấy mà sửa khí giới, phòng việc bất ngờ.',
    core: 'Tụy là thế cục quy tụ: người về một mối, tiền về một quỹ, lòng về một hướng — lễ lớn, hội lớn, đội lớn đang hình thành. Quẻ chỉ hai điều kiện cho cuộc tụ bền: có TRUNG TÂM xứng đáng (vua vào miếu — việc tụ phải có lý do thiêng liêng/chính đáng, không tụ quanh hư danh), và có PHÒNG BỊ — chỗ đông người là chỗ dễ sinh chuyện: va chạm, tranh giành, kẻ xấu trà trộn; "sửa khí giới" thời nay là chuẩn bị quy chế, dự phòng, kịch bản xấu trước khi đông đủ.',
    advice: 'Muốn gom người/vốn/lực: làm rõ "ngôi miếu" — mục đích chính đáng mà mọi bên cùng kính. Và viết luật chơi TRƯỚC khi đông, đừng đợi loạn rồi mới đặt.',
    love: 'Hai gia đình về một mối (cưới, về chung): cần một trung tâm giá trị chung và vài luật rõ từ sớm — tiền, tết, con cái. Tụ có chuẩn bị là tụ bền.',
    work: 'Gây quỹ, tuyển ồ ạt, sáp nhập: chuẩn hóa quy trình và pháp lý trước khi quy mô phình. Đám đông không quy chế tự khắc sinh phe.',
    reflect: ['Cuộc tụ bạn đang xây quay quanh "ngôi miếu" nào — nó có xứng không?', 'Kịch bản xấu nào của đám đông bạn chưa chuẩn bị?'],
  },
  {
    id: 46,
    slug: 'dia-phong-thang',
    name: 'Thăng',
    nameVi: 'Địa Phong Thăng',
    binary: '000110',
    keyTags: ['đi lên từ từ', 'tích nhỏ thành cao', 'lên có gốc'],
    tuong: 'Cây mọc lên giữa lòng đất — không ai thấy nó nhích từng ngày, mà một mùa ngoảnh lại đã thành tán. Người quân tử thuận đức, chứa việc nhỏ để thành cao lớn.',
    core: 'Thăng là kiểu đi lên đáng tin nhất: từ dưới lên, từ từ, có gốc rễ — như cây, không như pháo hoa. Thế cục này nói: con đường thăng tiến của bạn đang mở, nhưng nó thuộc loại "mọc" chứ không phải loại "nhảy"; mỗi tầng cao thêm phải đổi bằng một tầng rễ sâu thêm. Quẻ khuyên chủ động: "dụng kiến đại nhân, chớ lo" — thời này nên đi gặp người lớn hơn mình (xin việc, xin học, trình kế hoạch), cứ mạnh dạn về phương trước mà tiến.',
    advice: 'Đặt một nhịp tăng trưởng đều và nhỏ (mỗi tuần một bậc kỹ năng, mỗi quý một vòng quan hệ) thay vì chờ một cú nhảy. Và đừng ngại gõ cửa người trên — thời này cửa mở.',
    love: 'Quan hệ đang lớn dần theo kiểu cây: thêm rễ chung (kỷ niệm, thói quen, dự định). Đừng sốt ruột vì thiếu "bước ngoặt drama" — cây không cần drama để cao.',
    work: 'Thăng tiến tuần tự: nhận thêm trách nhiệm vừa sức, ghi nhận thành tích đều, trình bày nguyện vọng với cấp trên một cách đường hoàng.',
    reflect: ['Tầng rễ nào phải sâu thêm trước khi bạn lên tầng cao kế tiếp?', '"Đại nhân" nào bạn cứ ngại gặp — trong khi thời điểm đang thuận để gõ cửa?'],
  },
  {
    id: 47,
    slug: 'trach-thuy-khon',
    name: 'Khốn',
    nameVi: 'Trạch Thủy Khốn',
    binary: '011010',
    keyTags: ['khốn cùng', 'cạn nguồn', 'giữ chí khi lời không được tin'],
    tuong: 'Đầm mà nước rút cạn xuống dưới — cá mắc trên bãi khô. Người quân tử gặp thế ấy: liều mệnh giữ chí.',
    core: 'Khốn là một trong bốn thế khó nhất bộ Dịch: cạn nguồn — hết tiền, hết sức, hết người nghe; lời quẻ tả cảnh đau nhất của nó: "có nói cũng không ai tin". Nhưng chính quẻ này mở đầu bằng chữ "hanh" — khốn mà vẫn thông, vì sao? Vì khốn cảnh lột hết lớp vỏ, chỉ còn lại đúng cái lõi người: ai giữ được vui trong tâm và chí trong ngực giữa lúc kiệt thì chính sự bền ấy là đường thông. Thời Khốn: bớt thanh minh (nói nhiều càng mất giá), làm nhiều, sống sót trước đã.',
    advice: 'Ngừng cố thuyết phục thế giới bằng lời — thời này lời nhẹ hơn gió. Co cụm chi tiêu, giữ sức khỏe, làm những việc nhỏ chứng minh bằng kết quả. Và giữ một niềm vui tối thiểu mỗi ngày làm củi cho chí.',
    love: 'Giai đoạn cả hai cạn (tiền, sức, kiên nhẫn): hạ kỳ vọng xuống mức sống sót, đừng ra quyết định lớn về nhau trong lúc đói mệt. Qua mùa cạn rồi hãy đánh giá lại.',
    work: 'Cụt vốn, cụt niềm tin của sếp/khách: làm việc nhỏ thật chắc để gây lại tín nhiệm từng đồng. Đừng hứa to — thời này chỉ kết quả mới có giọng nói.',
    reflect: ['Trong cảnh cạn này, "chí" mà bạn nhất quyết giữ là gì — gọi tên được không?', 'Niềm vui tối thiểu nào nuôi được bạn qua từng ngày của mùa này?'],
  },
  {
    id: 48,
    slug: 'thuy-phong-tinh',
    name: 'Tỉnh',
    nameVi: 'Thủy Phong Tỉnh',
    binary: '010110',
    keyTags: ['giếng nước', 'nguồn nuôi chung', 'tu sửa nguồn'],
    tuong: 'Nước được kéo lên từ lòng đất bằng gàu — làng đổi tên, ấp dời chỗ, riêng cái giếng đứng nguyên. Giếng không vì ai múc nhiều mà cạn, không vì ai bỏ quên mà đầy thêm.',
    core: 'Tỉnh là quẻ về NGUỒN: thứ nuôi sống bạn và mọi người quanh bạn — nghề lõi, sức khỏe, tri thức, một cộng đồng tử tế. Quẻ dạy ba luật của giếng: một, giếng phải được DÙNG — nguồn lực bỏ quên thì "giếng bùn không ai uống"; hai, giếng phải được TU SỬA định kỳ — vét bùn, xếp lại thành (nâng cấp kỹ năng, bảo dưỡng sức khỏe); ba, bi kịch lớn nhất là "giếng trong mà không ai múc" — tài năng đã sẵn mà không được dùng, và dây gàu đứt ở mét cuối: gần xong mà bỏ thì kể như chưa từng làm.',
    advice: 'Xác định "giếng" của đời mình rồi đặt lịch tu sửa định kỳ như việc thiêng. Và kéo gàu lên TỚI MIỆNG giếng — đừng buông dây ở mét cuối.',
    love: 'Mối quan hệ là giếng chung: phải cùng vét bùn định kỳ (nói thật những điều lắng đọng) thì nước mới trong để cả hai uống lâu dài.',
    work: 'Nghề lõi của bạn là giếng: đầu tư bảo dưỡng nó trước mọi nghề tay trái. Trong tổ chức: tri thức chung (tài liệu, quy trình) là giếng làng — ai cũng múc thì ai đó phải vét.',
    reflect: ['Giếng của bạn lần cuối được vét bùn là bao giờ?', 'Việc nào của bạn đang ở "mét dây cuối" — và bạn định buông hay kéo nốt?'],
  },
  {
    id: 49,
    slug: 'trach-hoa-cach',
    name: 'Cách',
    nameVi: 'Trạch Hỏa Cách',
    binary: '011101',
    keyTags: ['thay đổi lớn', 'đổi đúng ngày', 'tin trước rồi mới đổi'],
    tuong: 'Lửa trong lòng đầm — nước với lửa diệt nhau, không thể ở chung mãi: phải có một cuộc thay đổi. Người quân tử nhân tượng mà làm lịch, tỏ rõ thời.',
    core: 'Cách nghĩa là lột xác — chữ gốc là tấm da thú được thuộc thành da mới. Đây là quẻ của những thay đổi lớn: đổi nghề, đổi mô hình, cải tổ, cách mạng một thói quen đời. Kinh Dịch ủng hộ thay đổi nhưng đặt ba chốt an toàn: một, đổi khi MÂU THUẪN ĐÃ CHÍN (nước lửa hết ở chung được — không phải đổi vì chán); hai, đổi ĐÚNG NGÀY ("kỷ nhật nãi phu" — chọn thời điểm, chuẩn bị đủ, không đổi trong cơn bốc); ba, đổi sao cho NGƯỜI TA TIN — thay đổi thành công khi những người liên quan thấy lý do chính đáng, "tin rồi mới đổi" chứ không bị đổi úp mặt.',
    advice: 'Kiểm ba chốt trước cú thay đổi lớn: mâu thuẫn chín chưa — ngày giờ/chuẩn bị đủ chưa — người liên quan đã được thuyết phục chưa. Đủ ba thì đổi dứt khoát, "hối hận tự tiêu".',
    love: 'Quan hệ cần một cuộc cách tân thật (cách sống chung, cách chia việc, cách cãi nhau) — làm như một dự án chung có bàn bạc, không phải một tối hậu thư.',
    work: 'Tái cấu trúc, pivot, chuyển nghề: viết rõ "vì sao bắt buộc đổi", chọn thời điểm, truyền thông trước. Đổi mà dân tin thì nửa việc đã xong.',
    reflect: ['Mâu thuẫn trong việc bạn định đổi đã chín thật chưa, hay mới là cơn chán?', 'Ai cần TIN cuộc thay đổi này trước khi bạn bấm nút — và họ đã được nghe chưa?'],
  },
  {
    id: 50,
    slug: 'hoa-phong-dinh',
    name: 'Đỉnh',
    nameVi: 'Hỏa Phong Đỉnh',
    binary: '101110',
    keyTags: ['dựng cái mới', 'nấu chín nuôi người', 'đổi vạc giữ lửa'],
    tuong: 'Lửa cháy trên gỗ — hình cái vạc ba chân đang nấu. Sau cuộc lột xác (quẻ Cách) là lúc bắc vạc mới: nấu chín đồ sống, nuôi người hiền.',
    core: 'Đỉnh là nửa sau của thay đổi — phần ít ai làm trọn: dựng trật tự MỚI cho tử tế. Cách là phá vạc cũ; Đỉnh là đúc vạc mới, và vạc để NẤU CHÍN: biến nguyên liệu sống (ý tưởng, người mới, quy trình mới) thành bữa ăn thật nuôi được người. Quẻ nhắc hình ảnh ba chân vạc — cái mới phải đứng trên thế vững (tài chính, con người, quy chế), gãy một chân là "đổ cả nồi cháo của vua". Đổi mới mà không có hệ nuôi dưỡng theo sau thì chỉ là đập phá có cảm hứng.',
    advice: 'Sau mỗi cú thay đổi, dành gấp đôi công sức cho phần "nấu": quy trình mới chạy thật, người mới được dạy thật, thói quen mới đủ 90 ngày. Kiểm ba chân vạc trước khi nổi lửa to.',
    love: 'Giai đoạn mới của quan hệ (cưới, con đầu, nhà mới) cần "vạc mới": nếp mới, lịch mới, vai mới — ngồi đúc cùng nhau thay vì mang nếp cũ ra dùng tạm.',
    work: 'Hậu tái cấu trúc: chuẩn hóa, đào tạo, nuôi người giỏi ở lại. Ba chân vạc của tổ chức: dòng tiền, con người, văn hóa — soi chân nào đang lung lay.',
    reflect: ['Cuộc đổi mới gần nhất của bạn đã có "vạc" nấu chưa, hay vẫn ăn sống nuốt tươi?', 'Ba chân vạc của việc bạn đang dựng: chân nào yếu nhất?'],
  },
  {
    id: 51,
    slug: 'thuan-chan',
    name: 'Chấn',
    nameVi: 'Thuần Chấn',
    binary: '001001',
    keyTags: ['chấn động', 'sợ mà tỉnh', 'giữ được mình giữa sấm'],
    tuong: 'Sấm chồng lên sấm — tiếng nổ dậy trăm dặm, ai nấy giật mình. Mà người chủ tế giữa đền vẫn không rớt giọt rượu cúng trên tay.',
    core: 'Chấn là cú sốc: tin dữ ập đến, biến cố nổ ra, mặt đất quen thuộc rung lên. Kinh Dịch nhìn cú sốc bằng con mắt lạ: "sấm đến hích hích, rồi cười nói ha ha" — chấn động làm ta sợ, và chính nỗi sợ ấy là liều thuốc tỉnh: sau sấm, người ta soi lại mình, sửa lỗi, sống nghiêm cẩn hơn. Thước đo bản lĩnh mà quẻ đưa ra là hình ảnh đẹp nhất bộ Dịch: giữa tiếng sấm trăm dặm, không đánh rơi chén rượu tế — giữ được việc thiêng liêng cốt lõi của mình qua cơn chấn động.',
    advice: 'Khi sốc ập đến: cho phép mình giật mình, rồi hỏi ngay "chén rượu tế của mình là gì" — việc cốt lõi nào phải giữ vững qua cơn này. Sau sấm, dùng nỗi sợ làm bài kiểm tra: nó phơi ra lỗ hổng nào để sửa?',
    love: 'Biến cố làm cả hai rúng động: ưu tiên giữ "chén rượu" của quan hệ — sự tử tế tối thiểu với nhau — trong lúc mọi thứ rung. Đổ lỗi giữa cơn sấm là đánh rơi chén.',
    work: 'Khủng hoảng nổ: bảo vệ nghiệp vụ lõi và khách hàng lõi trước tiên, mọi thứ khác tính sau. Sau cơn, tổ chức diễn tập — sấm lần hai không được phép bất ngờ như lần một.',
    reflect: ['"Chén rượu tế" của bạn — thứ nhất quyết không đánh rơi dù sấm cỡ nào — là gì?', 'Cú sốc gần nhất đã phơi ra lỗ hổng nào mà bạn chưa vá?'],
  },
  {
    id: 52,
    slug: 'thuan-can-nui',
    name: 'Cấn',
    nameVi: 'Thuần Cấn',
    binary: '100100',
    keyTags: ['dừng đúng chỗ', 'tĩnh tại', 'nghĩ không vượt vị'],
    tuong: 'Núi chồng lên núi — đứng yên, dày, vững. Dừng ở lưng (nơi không có mắt nhìn ham muốn), đi giữa sân không thấy người: tĩnh đến mức quên cả cái tôi.',
    core: 'Cấn là quẻ của sự DỪNG — kỹ năng bị đánh giá thấp nhất thời nay. Triết lý của quẻ gói trong một câu: "thời dừng thì dừng, thời đi thì đi" — dừng không phải đối lập với chuyển động, nó là một nửa của chuyển động đúng. Dừng kiểu Cấn có địa chỉ cụ thể: dừng ham muốn lúc nó chớm (dừng ở lưng — nơi chưa nhìn thấy món hàng), dừng lời lúc sắp quá đà, dừng suy nghĩ khỏi lan man ("nghĩ không vượt ra ngoài vị trí mình"). Tâm biết dừng thì như núi: gió thổi mây bay trên đỉnh, núi vẫn là núi.',
    advice: 'Tập ba cái dừng nhỏ: dừng mua lúc tay chạm nút, dừng nói lúc câu nóng lên lưỡi, dừng lo lúc nghĩ lấn sang việc không thuộc phần mình. Mỗi cú dừng đúng là một lần làm chủ.',
    love: 'Biết dừng cuộc cãi đúng câu, dừng kỳ vọng đúng ranh giới của người kia. Có những im lặng đúng lúc đáng giá hơn ngàn lời phân giải.',
    work: 'Dừng dự án đã hết lý do, dừng mở rộng khi vận hành chưa vững, dừng trả lời tin nhắn ngoài giờ thiêng của gia đình. Chiến lược = chọn chỗ dừng.',
    reflect: ['Bạn giỏi đi hơn hay giỏi dừng hơn — và đời đang đòi bạn kỹ năng nào?', 'Suy nghĩ của bạn hay "vượt vị" sang vùng nào — vùng đó có thuộc quyền bạn không?'],
  },
{
    id: 53,
    slug: 'phong-son-tiem',
    name: 'Tiệm',
    nameVi: 'Phong Sơn Tiệm',
    binary: '110100',
    keyTags: ['tiến dần', 'đúng trình tự', 'chậm mà chắc chỗ đứng'],
    tuong: 'Cây mọc trên núi cao — lớn chậm hơn cây đồng bằng, nhưng mỗi tấc cao đều bám đá mà đứng, thành dáng mà cả vùng nhìn lên.',
    core: 'Tiệm là quẻ của sự tiến có trình tự: như chim hồng nhạn di cư — từ bến nước lên ghềnh đá, lên đất bằng, lên cành cây, lên gò cao — mỗi chặng đậu vững rồi mới bay tiếp. Lời quẻ lấy việc cưới hỏi làm mẫu ("nữ quy cát"): chuyện trọng đại phải đi đủ lễ, đủ bước, đủ thời gian — chính cái CHẬM CÓ TRÌNH TỰ ấy tạo ra sự chính danh và bền vững. Thời nay gọi là: đi từng vòng — thử việc rồi chính thức, hẹn hò rồi ra mắt, bản nháp rồi bản chính. Nhảy cóc một bước, trả giá ba bước.',
    advice: 'Vẽ rõ các chặng của việc lớn đang làm và tôn trọng thứ tự: chặng nào chưa "đậu vững" thì chưa bay chặng sau. Sốt ruột là kẻ thù số một của thứ cần chính danh.',
    love: 'Tình cảm bền đi theo nhịp hồng nhạn: quen — hiểu — gặp gia đình — cam kết. Mỗi bước đậu cho vững; bước nào bị nhảy qua sẽ quay lại đòi nợ.',
    work: 'Thăng tiến/mở rộng theo trình tự: chứng minh ở quy mô nhỏ rồi mới nhận quy mô lớn. Danh tiếng xây kiểu Tiệm thì khủng hoảng khó đánh đổ.',
    reflect: ['Việc lớn của bạn đang ở chặng nào — và chặng đó đã "đậu vững" thật chưa?', 'Bạn đang muốn nhảy cóc bước nào — và cái giá ba bước của nó là gì?'],
  },
  {
    id: 54,
    slug: 'loi-trach-quy-muoi',
    name: 'Quy Muội',
    nameVi: 'Lôi Trạch Quy Muội',
    binary: '001011',
    keyTags: ['danh phận lệch', 'vào cuộc thế yếu', 'biết phận mà giữ giá trị'],
    tuong: 'Sấm động trên đầm — niềm vui bồng bột chạy theo chuyển động. Em gái theo về nhà chồng trong vị thế lẽ mọn: cuộc gắn bó khởi đầu đã lệch danh phận.',
    core: 'Quy Muội là quẻ cảnh báo về những cuộc dấn thân sai vị thế: vào một mối quan hệ, một thương vụ, một công việc mà ngay từ đầu mình đã ở chiếu dưới, danh không chính, quyền không rõ — vì nóng vội, vì ham, vì sợ lỡ. Lời quẻ nói thẳng hậu quả: "chinh hung, vô du lợi" — cứ thế dấn tới thì xấu. Nhưng quẻ không chỉ biết chê: nếu đã ở trong thế ấy, hãy học hào 5 — nàng công chúa lấy chồng dưới vị thế mà "tay áo không đẹp bằng người hầu": tự trọng nằm ở phẩm chất, không ở danh phận; giữ giá trị thật của mình thì thế yếu cũng thành chỗ đứng.',
    advice: 'Trước khi vào bất kỳ cuộc nào: hỏi rõ danh phận — vai gì, quyền gì, giấy tờ đâu. Đã lỡ trong thế lệch: đừng bù bằng cách hạ mình thêm; nâng giá trị thật và đàm phán lại danh phận từng bước.',
    love: 'Mối quan hệ mập mờ không danh phận, "yêu trước tính sau" kéo dài: người chịu thiệt là người không dám hỏi. Hỏi rõ không phải đòi hỏi — là tự trọng.',
    work: 'Nhận việc không chức danh, hùn vốn không giấy tờ, làm trước hứa sau: dừng lại ký cho rõ. Thế yếu nhưng nghề cứng thì sớm muộn cũng đổi được thế.',
    reflect: ['Cuộc nào bạn đang ở trong mà danh phận chưa từng được nói rõ?', 'Nếu không thể đổi danh phận ngay, giá trị thật nào của bạn cần được nâng để tự nó đổi thế?'],
  },
  {
    id: 55,
    slug: 'loi-hoa-phong',
    name: 'Phong',
    nameVi: 'Lôi Hỏa Phong',
    binary: '001101',
    keyTags: ['cực thịnh', 'mặt trời giữa trưa', 'thịnh là để chiếu sáng'],
    tuong: 'Sấm và chớp cùng đến — uy lẫn sáng đều cực đại. Mặt trời đứng giữa trưa: sáng nhất, và từ giây sau bắt đầu xế.',
    core: 'Phong là đỉnh thịnh: thành quả lớn, danh tiếng lớn, mọi thứ đầy ắp. Kinh Dịch chúc mừng kèm một câu lạ: "chớ lo, nên như mặt trời giữa trưa" — nghĩa là biết rõ trưa rồi sẽ xế (trăng đầy rồi khuyết, đó là phép trời) nhưng KHÔNG vì thế mà u sầu; việc của mặt trời giữa trưa là CHIẾU SÁNG HẾT CỠ trong chính giờ trưa của nó. Thịnh là để dùng: quyết những việc chỉ lúc thịnh mới quyết nổi, chia ánh sáng cho người đang trong bóng, xử các vụ tồn đọng (sấm + chớp = uy + minh, thời xử án tốt nhất).',
    advice: 'Đang trưa của đời mình: dùng nó dứt khoát — chốt việc lớn, trả ơn, dựng người, xử tồn đọng. Đồng thời chấp nhận quy luật xế chiều một cách thanh thản: làm sẵn kế hoạch "sau trưa" mà không sống trong lo sợ nó.',
    love: 'Giai đoạn viên mãn nhất: tạo những ký ức to (chuyến đi, lễ kỷ niệm, lời cảm ơn trịnh trọng) — chúng là kho ánh sáng cho những mùa ít nắng sau này.',
    work: 'Doanh thu/danh tiếng đỉnh: chốt hợp đồng dài hạn, tuyển người giỏi, chuẩn hóa — những việc chỉ làm được lúc đang có thế. Đỉnh không phải lúc nghỉ; là lúc gặt và gieo cùng lúc.',
    reflect: ['Việc gì chỉ "giờ trưa" này của bạn mới làm nổi — và bạn đang làm chưa?', 'Ánh sáng đang dư của bạn chiếu cho ai ngoài chính mình?'],
  },
  {
    id: 56,
    slug: 'hoa-son-lu',
    name: 'Lữ',
    nameVi: 'Hỏa Sơn Lữ',
    binary: '101100',
    keyTags: ['đất khách', 'khiêm cẩn nơi lạ', 'hành lý gọn'],
    tuong: 'Lửa cháy trên núi — cháy lan không ở yên một chỗ, như người lữ khách nay đây mai đó, dừng chân mà không có rễ.',
    core: 'Lữ là thế cục người xa xứ: làm việc nơi đất lạ, sống ở vùng chưa quen, vào môi trường mình là người mới — không thân thích, không thế lực, mọi vốn liếng chỉ là bản thân và hành lý mang theo. Quẻ dạy bộ quy tắc sinh tồn của lữ khách: khiêm cẩn (đất khách không phải chỗ thể hiện cái tôi), gọn nhẹ (giữ thân, giữ tiền, giữ giấy tờ — đừng bày biện), tử tế đều với mọi người (lữ khách sống bằng thiện cảm của dân bản xứ), và đặc biệt đừng gây chuyện — lời hào cảnh báo kẻ lữ khách kiêu căng "đốt tổ chim, cười trước khóc sau". Tạm bợ không có nghĩa là sống ẩu: chính nơi đất khách, tư cách là tấm hộ chiếu thật.',
    advice: 'Ở vùng mới (công ty mới, thành phố mới, ngành mới): ba tháng đầu nghe nhiều nói ít, học luật chơi bản địa, xây vài thiện cảm thật. Giữ mình gọn — cam kết ít, nợ nần không.',
    love: 'Yêu xa hoặc theo người về xứ lạ: tôn trọng "luật bản địa" của thế giới người ấy (gia đình, bạn bè, nếp cũ) trước khi đòi đổi nó theo mình.',
    work: 'Mới chuyển việc/thị trường: thành tích nhỏ + khiêm tốn lớn = công thức của quý đầu. Đừng phê phán "ở đây làm lạ thế" — hiểu trước, góp ý sau.',
    reflect: ['Ở vùng đất mới hiện tại, bạn đang là lữ khách khiêm cẩn hay đang "đốt tổ chim"?', 'Hành lý của bạn (cam kết, đồ đạc, cái tôi) đã đủ gọn cho giai đoạn di chuyển này chưa?'],
  },
  {
    id: 57,
    slug: 'thuan-ton',
    name: 'Tốn',
    nameVi: 'Thuần Tốn',
    binary: '110110',
    keyTags: ['thấm như gió', 'mềm mà tới nơi', 'lệnh nhắc hai lần'],
    tuong: 'Gió nối theo gió — không ồn như sấm, không gắt như lửa, nhưng len vào mọi khe hở và lay được cả rừng cây. Người quân tử nhân tượng mà nhắc mệnh lệnh nhiều lần cho thấm.',
    core: 'Tốn là sức mạnh của sự thấm: thay đổi người và việc không bằng cú đập mà bằng sự lặp lại nhẹ nhàng, đều đặn, đúng khe hở. Muốn đội ngũ đổi thói quen? Nhắc mềm mười lần thắng quát một lần. Muốn người thân đổi nếp? Gió thổi mỗi ngày một chút. Quẻ cũng dặn giới hạn của gió: mềm phải có HƯỚNG ("lợi hữu du vãng") và có CHỦ ("lợi kiến đại nhân") — gió không hướng là gió loạn; người mềm không lập trường là người ba phải, lời hào cuối chê kẻ "nhún đến chui xuống gầm giường, mất cả của lẫn búa".',
    advice: 'Việc khó lay: đổi chiến thuật từ "một cú lớn" sang "trăm cú nhỏ cùng hướng" — tin nhắn nhắc đều, ví dụ làm mẫu đều, sự hiện diện đều. Nhưng giữ một lập trường cứng làm trục cho mọi cái mềm.',
    love: 'Góp ý người thương kiểu gió: đúng lúc mềm, lặp lại kiên nhẫn, không bới quá khứ. Mưa dầm thấm lâu — nhưng mềm đến mất ranh giới thì không còn là gió, là hơi.',
    work: 'Thay đổi văn hóa nhóm: truyền thông lặp lại nhiều kênh, làm gương đều đặn. "Nhắc lại lần thứ ba" không phải thất bại của lệnh — nó là cách lệnh thấm.',
    reflect: ['Việc gì bạn đã thử "đập một cú" mà hỏng — giờ thử trăm cú gió nhỏ được không?', 'Sự mềm mỏng của bạn đang có trục cứng chưa, hay đang nhún tới gầm giường?'],
  },
  {
    id: 58,
    slug: 'thuan-doai',
    name: 'Đoái',
    nameVi: 'Thuần Đoái',
    binary: '011011',
    keyTags: ['niềm vui', 'nói chuyện cùng học', 'vui mà chính'],
    tuong: 'Hai đầm nước liền nhau — nước bên này thông bên kia, cùng đầy cùng mát. Người quân tử nhân tượng mà họp bạn giảng tập: niềm vui lớn nhất là cùng bạn bè trau dồi.',
    core: 'Đoái là quẻ của niềm vui và lời nói — miệng cười, miệng nói, sự giao tiếp làm người gần người. Kinh Dịch phân loại vui rất sắc: vui từ sự thật và điều chính ("hòa duyệt mà trinh") thì cảm hóa được người, dân quên cả nhọc mà theo; còn vui kiểu nịnh nọt, mua vui, dụ dỗ ("lai duyệt" — niềm vui đến từ việc chiều theo cái sai) thì hung. Hai đầm thông nhau là hình ảnh đẹp về tình bạn đúng nghĩa: trao đổi làm cả hai cùng đầy — khác hồ nước tù chỉ một bên cho.',
    advice: 'Nuôi những cuộc vui có chất: học nhóm, bạn nghề, bữa cơm có chuyện tử tế. Và kiểm chất niềm vui của mình: nó đứng trên điều thật hay đứng trên sự chiều lòng?',
    love: 'Cười với nhau mỗi ngày là chỉ số sức khỏe của quan hệ. Nhưng vui lòng nhau khác chiều lòng nhau — đôi nào không dám nói điều mất lòng là đôi đang tích nợ.',
    work: 'Văn hóa vui mà thật: phản hồi thẳng trong không khí lành. Đội cười nhiều mà không ai dám nói thật là đội đang diễn.',
    reflect: ['Niềm vui dạo này của bạn thuộc loại nào: cùng đầy lên, hay một bên cạn dần?', 'Có sự thật nào bạn đang nuốt để giữ không khí vui — và cái giá đang tích là gì?'],
  },
  {
    id: 59,
    slug: 'phong-thuy-hoan',
    name: 'Hoán',
    nameVi: 'Phong Thủy Hoán',
    binary: '110010',
    keyTags: ['tan rã', 'thổi tan khối cứng', 'tụ lại bằng việc thiêng'],
    tuong: 'Gió thổi trên mặt nước — băng giá tan ra, sóng gợn lan đi. Cái đang đóng cứng được làm cho tan; cái đang rã rời cần được gom về.',
    core: 'Hoán có hai mặt của cùng một hơi gió: mặt sáng — nó thổi TAN những khối đóng cứng (hiểu lầm đóng băng, cái tôi co cụm, sự ích kỷ bè nhóm); mặt tối — nó cũng là thế cục lòng người TẢN MÁT: đội ngũ rã đám, gia đình mỗi người một ngả, cộng đồng nguội lạnh. Phép trị của quẻ rất cổ mà rất đúng: "vua tới miếu" — muốn gom lòng người đang tan, cần một điều thiêng liêng chung để cùng hướng về: một sứ mệnh, một nghi lễ, một dự án lớn hơn mọi cá nhân. Hào đẹp nhất nói "hoán kỳ quần" — dám giải tán cả phe nhóm riêng của mình vì cái chung: tan cái nhỏ để tụ cái lớn.',
    advice: 'Thứ gì đang đóng cứng — thổi gió vào (một cuộc gặp, một lời mở). Lòng người đang tán — dựng "ngôi miếu": mục tiêu chung đủ lớn, nghi thức chung đủ đều (bữa cơm, buổi họp, chuyến đi).',
    love: 'Hai người đang nguội và tản (mỗi người một màn hình): cần một điều thiêng chung định kỳ — bữa tối không điện thoại, chuyến đi mỗi năm. Nghi thức là keo của thời tản mát.',
    work: 'Đội remote/đa vùng đang rời rạc: sứ mệnh nói lại cho rõ, nhịp họp có nghi thức, một dự án chung kéo các phe khỏi góc riêng. Dám xóa "đặc khu" của chính mình trước.',
    reflect: ['Cái gì trong đời bạn đang đóng băng cần gió — và cái gì đang tán mát cần miếu?', '"Phe nhóm riêng" nào của bạn đáng được giải tán vì cái chung lớn hơn?'],
  },
  {
    id: 60,
    slug: 'thuy-trach-tiet',
    name: 'Tiết',
    nameVi: 'Thủy Trạch Tiết',
    binary: '010011',
    keyTags: ['chừng mực', 'đặt ngưỡng', 'tiết chế dễ chịu mới bền'],
    tuong: 'Nước trong đầm — đầm có bờ nên nước có chừng: đầy quá thì tràn, vơi quá thì cạn. Người quân tử nhân tượng mà đặt ra số đo, mức độ.',
    core: 'Tiết là quẻ của giới hạn tự đặt: ngân sách, giờ giấc, khẩu phần, ranh giới quan hệ. Triết lý của nó đi trước thời đại: tự do thật không nằm ở vô hạn mà nằm ở ngưỡng hợp lý — như đầm nhờ có bờ mà thành đầm, nhạc nhờ có nhịp mà thành nhạc. Nhưng quẻ cài một cảnh báo hiếm thấy về chính chủ đề của mình: "khổ tiết, bất khả trinh" — tiết chế đến mức cay đắng thì không giữ được lâu; kỷ luật bền là kỷ luật còn dễ thở ("cam tiết" — tiết chế ngọt). Nhịn kiểu hành xác chỉ sinh cú bùng ngược.',
    advice: 'Đặt ngưỡng cho thứ đang tràn (chi tiêu, màn hình, lời hứa) — nhưng đặt ở mức giữ được 365 ngày, không phải mức anh hùng 7 ngày. Ngưỡng tốt là ngưỡng có chỗ thở.',
    love: 'Ranh giới rõ làm quan hệ dễ thở: giờ riêng – giờ chung, chuyện hai người – chuyện được kể ra ngoài. Và đừng bắt nhau sống "khổ tiết" theo chuẩn khắc kỷ của một phía.',
    work: 'Ngân sách, phạm vi dự án, giờ làm: đặt số cụ thể và giữ. Cam kết vô hạn với khách là con đường ngắn nhất tới phá sản chất lượng.',
    reflect: ['Thứ gì của bạn đang tràn vì chưa có bờ?', 'Kỷ luật nào của bạn đang ở dạng "khổ tiết" — hạ một nấc cho nó sống được quanh năm?'],
  },
  {
    id: 61,
    slug: 'phong-trach-trung-phu',
    name: 'Trung Phu',
    nameVi: 'Phong Trạch Trung Phu',
    binary: '110011',
    keyTags: ['thành tín từ tâm', 'tin cảm được vật', 'rỗng giữa mà thật'],
    tuong: 'Gió thổi trên đầm — nước cảm hơi gió mà gợn theo, không cần ai ép. Quẻ rỗng ở giữa: lòng trống không thành kiến, nên sự thật ở được trong đó.',
    core: 'Trung Phu là quẻ của chữ TÍN ở tầng sâu nhất: thành thật từ trong lõi, đến mức "cảm được cả heo và cá" — loài khó cảm nhất cũng cảm được, nghĩa là sự chân thành đủ thật thì chạm tới cả người khó tính nhất, xa cách nhất. Hình ảnh trung tâm của quẻ: hạc mẹ kêu trong bóng râm, hạc con họa lại — niềm tin thật tạo cộng hưởng tự nhiên không cần phô trương. Tín kiểu này không phải "giữ lời cho có uy tín" (mưu lợi), mà là trong–ngoài–một: nghĩ, nói, làm cùng một dòng. Người như thế đi việc khó mấy cũng "lợi vượt sông lớn".',
    advice: 'Kiểm độ lệch giữa ba tầng: điều bạn nghĩ – điều bạn nói – điều bạn làm. Mỗi độ lệch là một chỗ rò của niềm tin. Với người khó cảm nhất quanh bạn: thử dùng sự thật trần, không chiến thuật.',
    love: 'Tin nhau không xây bằng lời thề mà bằng nghìn lần khớp nhỏ giữa nói và làm. Một lần "nói vậy mà không phải vậy" tốn trăm lần gấp đôi để vá.',
    work: 'Uy tín là tài sản lãi kép: báo đúng tiến độ kể cả khi xấu, hứa ít làm đủ. Khách hàng "heo cá" — lạnh lùng nhất — lại là người trung thành nhất một khi đã cảm.',
    reflect: ['Ở đâu lời nói của bạn đang chạy trước việc làm?', 'Ai là "heo cá" trong đời bạn — và bạn đã thử chạm họ bằng sự thật trần chưa?'],
  },
  {
    id: 62,
    slug: 'loi-son-tieu-qua',
    name: 'Tiểu Quá',
    nameVi: 'Lôi Sơn Tiểu Quá',
    binary: '001100',
    keyTags: ['việc nhỏ thì được', 'đừng bay cao', 'kỹ hơn một chút'],
    tuong: 'Sấm trên đỉnh núi — tiếng vang bị núi chặn, không lan xa được. Con chim bay để lại tiếng kêu: không nên lên cao, nên xuống thấp — xuống thì lành.',
    core: 'Tiểu Quá là thời của việc nhỏ: thế cục không thuận cho cú lớn, nhưng RẤT thuận cho sự chu đáo vượt mức ở việc nhỏ. Lời quẻ chỉ rõ ba chỗ nên "quá một chút": cung kính quá một chút, tiết kiệm quá một chút, lo việc kỹ quá một chút — những cái "quá" nhỏ ấy thời này đều lành. Còn bay cao (dự án lớn, tuyên bố lớn, đầu tư lớn) thì như chim bay ngược lên giữa thế gió đè: "thượng nghịch hạ thuận". Đây không phải quẻ bi quan — nó là quẻ của người khôn biết mùa nào gieo hạt to, mùa nào nhặt hạt nhỏ.',
    advice: 'Hoãn cú lớn lại một mùa. Thắng thế này bằng chuỗi việc nhỏ làm kỹ hơn người: phản hồi nhanh hơn, lời cảm ơn chu đáo hơn, chi tiêu sít hơn, hồ sơ sạch hơn.',
    love: 'Thời điểm của những cử chỉ nhỏ kỹ lưỡng: nhớ ngày nhỏ, làm việc nhà chu đáo, lời hỏi han đúng lúc. Đừng chọn lúc này cho quyết định trọng đại.',
    work: 'Thị trường khó: bảo trì khách cũ kỹ hơn, vá quy trình, dọn dữ liệu. Người làm kỹ việc nhỏ thời xấu là người được giao việc lớn thời tốt.',
    reflect: ['Cú lớn nào bạn đang muốn làm ngược gió — hoãn một mùa có chết không?', 'Ba việc nhỏ nào nếu làm "quá kỹ" tuần này sẽ tích điểm dài hạn?'],
  },
  {
    id: 63,
    slug: 'thuy-hoa-ky-te',
    name: 'Ký Tế',
    nameVi: 'Thủy Hỏa Ký Tế',
    binary: '010101',
    keyTags: ['đã thành', 'mọi thứ vào vị', 'thịnh trị dễ sinh loạn'],
    tuong: 'Nước trên lửa — nồi đang nấu hoàn hảo: lửa đun nước, nước không dập lửa. Sáu hào đều đúng ngôi: trật tự trọn vẹn hiếm có. Người quân tử nhân tượng mà lo hoạn nạn, phòng từ trước.',
    core: 'Ký Tế nghĩa là "đã vượt sông xong" — mọi việc hoàn tất, mọi mảnh vào đúng chỗ: dự án xong, nhà cửa yên, vị trí vững. Đây là quẻ duy nhất mà cả sáu hào đều chính vị — và chính vì thế Kinh Dịch lo lắng: "thoạt đầu lành, cuối cùng loạn" — trật tự hoàn hảo là trạng thái KHÔNG ĐỨNG YÊN ĐƯỢC, mọi biến động từ đây chỉ có một hướng là lệch đi. Sau thành công, kẻ thù lớn nhất là sự buông lơi: nồi nước trên lửa, ngon là khi canh đúng lúc — bỏ đi chơi thì cạn nước cháy nồi. Người xưa qua sông xong vẫn ngoái kiểm tra thuyền.',
    advice: 'Việc vừa thành: chuyển ngay từ chế độ "chiến đấu" sang chế độ "bảo trì có kỷ luật" — kiểm định kỳ, vá lỗ nhỏ ngay, giữ người giỏi ở lại. Đỉnh trật tự là lúc bắt đầu trả phí duy trì.',
    love: 'Cưới xong, nhà xong, con xong — không phải vạch đích mà là đổi môn thi: từ chinh phục sang vun giữ. Cặp đôi tan sau khi "đã ổn định" thường tan vì ngừng canh nồi.',
    work: 'Dự án về đích: nghiệm thu kỹ, tài liệu hóa, lập lịch bảo trì, thưởng đúng người. Thành công không được bảo trì sẽ tự khấu hao về 0.',
    reflect: ['Thứ gì của bạn vừa "xong" mà đang bị bỏ bê vì tưởng xong là xong?', 'Lỗ rò nhỏ nào trong trật tự hiện tại sẽ thành lỗ đắm thuyền nếu để 6 tháng?'],
  },
  {
    id: 64,
    slug: 'hoa-thuy-vi-te',
    name: 'Vị Tế',
    nameVi: 'Hỏa Thủy Vị Tế',
    binary: '101010',
    keyTags: ['chưa thành', 'gần xong nhất là lúc dễ ướt đuôi', 'kết thúc mở'],
    tuong: 'Lửa trên nước — hai thứ chưa gặp đúng thế, nồi chưa bắc xong. Cáo con qua sông, gần tới bờ thì ướt đuôi: sắp thành mà chưa thành.',
    core: 'Vị Tế — "chưa vượt sông xong" — được chọn làm quẻ KẾT THÚC cả bộ Kinh Dịch, và đó là một tuyên ngôn: vòng đời không đóng lại ở "hoàn tất" (Ký Tế) mà mở ra ở "chưa hoàn tất" — luôn còn việc dở, luôn còn chặng mới, và đó không phải thất bại mà là bản chất của sự sống. Thế cục của bạn: việc đang ở đoạn 80–95%, đoạn nguy hiểm nhất — cáo con qua gần hết sông mới ướt đuôi vì chủ quan ở mét cuối. Lời quẻ: thận trọng phân định từng việc còn lại ("biện vật cư phương"), dồn sự tỉnh táo cho khúc chót, và đừng uống mừng trước khi lên bờ — hào cuối say rượu ướt đầu chính là kẻ ăn mừng sớm.',
    advice: 'Liệt kê chính xác phần "chưa": còn mấy việc, việc nào rủi ro nhất, ai canh nó. Kỷ luật khúc cuối: chưa lên bờ chưa mở rượu. Và nếu việc này khép lại — nhớ nó mở ra việc kế: giữ sức cho vòng sau.',
    love: 'Đoạn "sắp": sắp cưới, sắp về chung, sắp làm lành — chính là đoạn cần nâng niu nhất, mọi bất cẩn lúc này đắt gấp ba. Đi nốt mét cuối bằng sự dịu dàng có chủ đích.',
    work: 'Dự án 90%: chốt danh sách việc tồn, kiểm thử khắt khe nhất ở phút chót, hoãn ăn mừng tới sau nghiệm thu. Phần lớn tai tiếng nghề nghiệp sinh ra ở 10% cuối.',
    reflect: ['Việc nào của bạn đang ở mét cuối cùng — và "cái đuôi" nào dễ ướt nhất?', 'Bạn có đang mở rượu trước khi lên bờ ở chuyện gì không?'],
  },
];

/** Tra cứu theo slug — dùng cho generateStaticParams + page. */
export function getQue(slug: string): QueKinhDich | undefined {
  return QUE_PAGES.find((q) => q.slug === slug);
}
