// ─────────────────────────────────────────────────────────────────────────────
// SITE REGISTRY — single source of truth for public TOOL listings (S9 / T10).
//
// Unifies the four formerly hand-maintained lists (QUICK_LOOKUP + TOOLKIT_GROUPS
// in catalog/tools.ts, the /cong-cu catalog TOOLS, and RELATED_TOOLS) into ONE
// entry per tool (keyed by href). Add or edit a tool in ONE place here; the four
// surfaces (mobile drawer · homepage marquee · /cong-cu catalog · related-tools)
// are DERIVED below so they can never drift apart.
//
// The old lists are kept in place for one release as a rollback net; a parity
// test (site-registry.parity.test.ts) asserts the derived views deepEqual them.
// GENERATED by scratchpad/gen-registry.mjs — safe to hand-edit afterwards.
// ─────────────────────────────────────────────────────────────────────────────

import type { ExplorerTool } from '@/components/tools/CongCuExplorer';

export type ToolTier = 'free' | 'premium';
export type QuickGroupKey = 'co-hoc' | 'theo-mua' | 'tam-ly' | 'chiem-tinh' | 'xem-tuoi' | 'kham-pha';
export type Surface = 'drawer' | 'home' | 'catalog';

export interface QuickTool { href: string; label: string; tier: ToolTier; group?: QuickGroupKey; }
export interface ToolChip { n: string; href: string; learn?: string; }
export interface ToolGroup { label: string; tools: ToolChip[]; }
export interface RelatedLink { href: string; label: string; }

export interface ToolEntry {
  href: string;
  surfaces: Surface[];
  /** drawer/footer view (QUICK_LOOKUP) */
  quick?: { label: string; tier: ToolTier; group?: QuickGroupKey };
  /** homepage marquee view (TOOLKIT_GROUPS); n = short chip label */
  home?: { n: string; learn?: string; group: string };
  /** /cong-cu catalog view (ExplorerTool) */
  catalog?: { cat: string; emoji: string; name: string; desc: string };
  /** label shown when THIS tool appears as a related link elsewhere */
  relatedLabel?: string;
  /** ordered target hrefs this tool links to under "Công cụ liên quan" */
  related?: string[];
}

/** Sub-group order + labels for the mobile drawer "Tra cứu nhanh" section. */
export const QUICK_GROUPS: { key: NonNullable<QuickTool['group']>; label: string }[] = [
  {
    "key": "co-hoc",
    "label": "Cổ học Á Đông"
  },
  {
    "key": "tam-ly",
    "label": "Tâm lý hiện đại"
  },
  {
    "key": "chiem-tinh",
    "label": "Chiêm tinh phương Tây"
  },
  {
    "key": "xem-tuoi",
    "label": "Xem tuổi việc lớn"
  },
  {
    "key": "theo-mua",
    "label": "Theo thời điểm"
  },
  {
    "key": "kham-pha",
    "label": "So sánh & đối chiếu"
  }
];

export const TOOL_REGISTRY: ToolEntry[] = [
  {
    "href": "/la-so-tu-vi",
    "catalog": {
      "cat": "la-so",
      "emoji": "☯",
      "name": "Xem lá số Tử Vi",
      "desc": "Lập lá số Tử Vi miễn phí: 12 cung, 121 sao, độ sáng, cách cục — con số thật."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Xem lá số Tử Vi",
    "related": [
      "/la-so-bat-tu",
      "/tu-vi",
      "/tinh-menh-cuc",
      "/bang-chung"
    ]
  },
  {
    "href": "/la-so-bat-tu",
    "catalog": {
      "cat": "la-so",
      "emoji": "☯",
      "name": "Xem lá số Bát Tự",
      "desc": "Lập lá số Bát Tự (Tứ Trụ) miễn phí: 8 chữ, ngũ hành, Nhật Chủ, Thập Thần — tính theo tiết khí."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Xem lá số Bát Tự",
    "related": [
      "/la-so-tu-vi",
      "/bat-tu",
      "/ban-menh",
      "/tinh-menh-cuc"
    ]
  },
  {
    "href": "/tinh-menh-cuc",
    "quick": {
      "label": "Tuổi mệnh cục",
      "tier": "free",
      "group": "co-hoc"
    },
    "catalog": {
      "cat": "la-so",
      "emoji": "🧮",
      "name": "Tuổi mệnh cục",
      "desc": "Tính Mệnh và Cục từ ngày giờ sinh — nền tảng để lập lá số Tử Vi."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Tính Mệnh Cục",
    "related": [
      "/tu-vi",
      "/bat-tu",
      "/than-so-hoc",
      "/bang-chung"
    ]
  },
  {
    "href": "/ban-menh",
    "catalog": {
      "cat": "la-so",
      "emoji": "🪙",
      "name": "Ngũ hành bản mệnh",
      "desc": "Sinh năm nào mệnh gì: tra nạp âm, hành bản mệnh và màu hợp theo năm sinh."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Ngũ hành bản mệnh"
  },
  {
    "href": "/bang-chung",
    "catalog": {
      "cat": "la-so",
      "emoji": "✓",
      "name": "Bằng Chứng",
      "desc": "Kiểm chứng lá số bằng quá khứ thật của bạn — nhập sự kiện đã xảy ra, xem lá số có ghi dấu không. Không bói mù."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Bằng Chứng (kiểm chứng lá số)",
    "related": [
      "/la-so-tu-vi",
      "/tu-vi",
      "/bat-tu"
    ]
  },
  {
    "href": "/dai-van-hien-tai",
    "quick": {
      "label": "Đại vận hiện tại",
      "tier": "free",
      "group": "theo-mua"
    },
    "catalog": {
      "cat": "van-trinh",
      "emoji": "🧭",
      "name": "Đại vận hiện tại",
      "desc": "Bạn đang ở đại vận (10 năm) nào — chủ đề lớn của giai đoạn hiện tại."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Đại vận hiện tại",
    "related": [
      "/timeline",
      "/tu-vi-hom-nay",
      "/sao-han",
      "/tu-vi-2027"
    ]
  },
  {
    "href": "/timeline",
    "catalog": {
      "cat": "van-trinh",
      "emoji": "📈",
      "name": "Timeline Đại Vận",
      "desc": "Xem đại vận 10 năm vận hành thế nào theo dòng thời gian — các mốc chuyển vận lớn."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Timeline đại vận",
    "related": [
      "/dai-van-hien-tai",
      "/tu-vi-2027",
      "/sao-han",
      "/tu-vi-hom-nay"
    ]
  },
  {
    "href": "/tu-vi-nghe-nghiep",
    "catalog": {
      "cat": "van-trinh",
      "emoji": "💼",
      "name": "Tử Vi Nghề Nghiệp",
      "desc": "Lá số nói gì về sự nghiệp: hợp ngành nào, vai trò nào, điểm mạnh khi làm việc."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Tử Vi sự nghiệp",
    "related": [
      "/tu-vi",
      "/career-fit",
      "/bat-tu"
    ]
  },
  {
    "href": "/tu-vi-tinh-yeu",
    "catalog": {
      "cat": "van-trinh",
      "emoji": "❤️",
      "name": "Tử Vi Tình Yêu",
      "desc": "Lá số về tình cảm: cách bạn gắn bó, thể hiện cảm xúc và mẫu xung đột thường gặp."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Tử Vi tình yêu",
    "related": [
      "/tu-vi",
      "/hop-tuoi",
      "/compatibility"
    ]
  },
  {
    "href": "/tu-vi-tai-chinh",
    "catalog": {
      "cat": "van-trinh",
      "emoji": "💰",
      "name": "Tử Vi Tài Chính",
      "desc": "Lá số về tiền bạc: cách kiếm tiền, thói quen quản lý và điểm rủi ro cần lưu ý."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Tử Vi tài chính",
    "related": [
      "/tu-vi",
      "/bat-tu",
      "/tu-vi-nghe-nghiep"
    ]
  },
  {
    "href": "/tu-vi-hom-nay",
    "quick": {
      "label": "Tử Vi hôm nay",
      "tier": "free",
      "group": "theo-mua"
    },
    "catalog": {
      "cat": "van-trinh",
      "emoji": "📅",
      "name": "Tử Vi hôm nay",
      "desc": "Vận trình hôm nay theo 12 con giáp — màu sắc, giờ tốt, điều nên/nên tránh."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Tử Vi hôm nay",
    "related": [
      "/tu-vi",
      "/tu-vi-2026",
      "/tu-vi-2027",
      "/lich-van-nien"
    ]
  },
  {
    "href": "/tu-vi-2026",
    "quick": {
      "label": "Tử Vi 2026",
      "tier": "free",
      "group": "theo-mua"
    },
    "catalog": {
      "cat": "van-trinh",
      "emoji": "🐎",
      "name": "Tử Vi 2026",
      "desc": "Tử Vi năm Bính Ngọ 2026 cho 12 con giáp — công việc, tài lộc, tình cảm."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Tử Vi 2026",
    "related": [
      "/tu-vi",
      "/tu-vi-2027",
      "/sao-han",
      "/tu-vi-hom-nay",
      "/bang-chung"
    ]
  },
  {
    "href": "/tu-vi-2027",
    "quick": {
      "label": "Tử Vi 2027",
      "tier": "free",
      "group": "theo-mua"
    },
    "catalog": {
      "cat": "van-trinh",
      "emoji": "🐐",
      "name": "Tử Vi 2027",
      "desc": "Tử Vi năm Đinh Mùi 2027 cho 12 con giáp — sao hạn, vận trình từng tuổi."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Tử Vi 2027",
    "related": [
      "/tu-vi",
      "/sao-han",
      "/tu-vi-hom-nay",
      "/tu-vi-2026",
      "/lich-van-nien"
    ]
  },
  {
    "href": "/sao-han",
    "quick": {
      "label": "Xem sao hạn",
      "tier": "free",
      "group": "theo-mua"
    },
    "home": {
      "n": "Sao hạn",
      "learn": "/learn/sao-han",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "van-trinh",
      "emoji": "⭐",
      "name": "Xem Sao Hạn",
      "desc": "Tra sao chiếu mệnh (Cửu Diệu) theo tuổi và giới tính — tham khảo theo phong tục."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Xem sao hạn",
    "related": [
      "/tu-vi-hom-nay",
      "/tu-vi-2026",
      "/dai-van-hien-tai",
      "/lich-van-nien",
      "/learn/sao-han"
    ]
  },
  {
    "href": "/mbti",
    "quick": {
      "label": "MBTI",
      "tier": "free",
      "group": "tam-ly"
    },
    "home": {
      "n": "MBTI",
      "learn": "/learn/mbti",
      "group": "Tâm lý hiện đại"
    },
    "catalog": {
      "cat": "hieu-ban-than",
      "emoji": "🧠",
      "name": "MBTI",
      "desc": "16 kiểu tâm trí trên 4 trục — bản đồ thiên hướng nội tại."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "MBTI",
    "related": [
      "/big-five",
      "/disc",
      "/enneagram",
      "/so-sanh",
      "/learn/mbti"
    ]
  },
  {
    "href": "/big-five",
    "quick": {
      "label": "Big Five (OCEAN)",
      "tier": "free",
      "group": "tam-ly"
    },
    "home": {
      "n": "Big Five",
      "learn": "/learn/big-five",
      "group": "Tâm lý hiện đại"
    },
    "catalog": {
      "cat": "hieu-ban-than",
      "emoji": "📊",
      "name": "Big Five",
      "desc": "Mô hình 5 nhân tố: OCEAN — chuẩn mực tâm lý học hiện đại."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Big Five",
    "related": [
      "/mbti",
      "/disc",
      "/enneagram",
      "/so-sanh",
      "/learn/big-five"
    ]
  },
  {
    "href": "/disc",
    "quick": {
      "label": "Trắc nghiệm DiSC",
      "tier": "free",
      "group": "tam-ly"
    },
    "home": {
      "n": "DISC",
      "learn": "/learn/disc",
      "group": "Tâm lý hiện đại"
    },
    "catalog": {
      "cat": "hieu-ban-than",
      "emoji": "🎯",
      "name": "DISC",
      "desc": "Bốn phong cách hành vi: Dominance, Influence, Steadiness, Compliance."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "DISC",
    "related": [
      "/mbti",
      "/big-five",
      "/enneagram",
      "/career-fit",
      "/learn/disc"
    ]
  },
  {
    "href": "/enneagram",
    "quick": {
      "label": "Enneagram",
      "tier": "free",
      "group": "tam-ly"
    },
    "home": {
      "n": "Enneagram",
      "learn": "/learn/enneagram",
      "group": "Tâm lý hiện đại"
    },
    "catalog": {
      "cat": "hieu-ban-than",
      "emoji": "🌀",
      "name": "Enneagram",
      "desc": "Chín nhóm tính cách — khám phá động cơ và nỗi sợ cốt lõi của bạn."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Enneagram",
    "related": [
      "/mbti",
      "/big-five",
      "/disc",
      "/so-sanh",
      "/learn/enneagram"
    ]
  },
  {
    "href": "/than-so-hoc",
    "quick": {
      "label": "Thần số học",
      "tier": "free",
      "group": "co-hoc"
    },
    "home": {
      "n": "Thần Số",
      "learn": "/learn/than-so-hoc",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "hieu-ban-than",
      "emoji": "🔢",
      "name": "Thần Số Học",
      "desc": "Con số cuộc đời, sứ mệnh, linh hồn."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Thần số học",
    "related": [
      "/tu-vi",
      "/bat-tu",
      "/mbti",
      "/can-xuong",
      "/learn/than-so-hoc"
    ]
  },
  {
    "href": "/xem-tuong",
    "quick": {
      "label": "Xem Chỉ Tay & Tướng Mặt",
      "tier": "free",
      "group": "co-hoc"
    },
    "home": {
      "n": "Xem Tướng",
      "learn": "/learn/palm",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "hieu-ban-than",
      "emoji": "🖐️",
      "name": "Xem Chỉ Tay & Tướng Mặt",
      "desc": "Tải ảnh lòng bàn tay hoặc khuôn mặt — AI phân tích xu hướng tính cách theo tướng số học."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Xem tướng",
    "related": [
      "/tu-vi",
      "/gieo-que",
      "/than-so-hoc",
      "/learn/palm"
    ]
  },
  {
    "href": "/ban-do-sao",
    "quick": {
      "label": "Bản đồ sao",
      "tier": "free",
      "group": "chiem-tinh"
    },
    "home": {
      "n": "Bản đồ sao",
      "learn": "/learn/chiem-tinh",
      "group": "Chiêm tinh phương Tây"
    },
    "catalog": {
      "cat": "chiem-tinh",
      "emoji": "🔭",
      "name": "Bản đồ sao",
      "desc": "Chiêm tinh phương Tây: cung Mặt Trời, Mặt Trăng & cung Mọc từ ngày giờ sinh — bản đồ sao cá nhân."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Bản đồ sao",
    "related": [
      "/cung-hoang-dao",
      "/mbti",
      "/big-five",
      "/xem-tuong"
    ]
  },
  {
    "href": "/cung-hoang-dao",
    "quick": {
      "label": "Cung hoàng đạo",
      "tier": "free",
      "group": "chiem-tinh"
    },
    "home": {
      "n": "Cung hoàng đạo",
      "learn": "/learn/chiem-tinh",
      "group": "Chiêm tinh phương Tây"
    },
    "catalog": {
      "cat": "chiem-tinh",
      "emoji": "♌",
      "name": "Cung hoàng đạo",
      "desc": "12 cung hoàng đạo: tra cung theo ngày sinh, tính cách, nguyên tố và cung hợp nhau."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Cung hoàng đạo"
  },
  {
    "href": "/tarot",
    "quick": {
      "label": "Tarot",
      "tier": "free",
      "group": "chiem-tinh"
    },
    "home": {
      "n": "Tarot",
      "learn": "/learn/tarot",
      "group": "Trực giác"
    },
    "catalog": {
      "cat": "chiem-tinh",
      "emoji": "🃏",
      "name": "Tarot",
      "desc": "78 lá bài — ngôn ngữ biểu tượng để đặt câu hỏi sâu hơn."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Tarot",
    "related": [
      "/gieo-que",
      "/xem-tuong",
      "/mbti",
      "/learn/tarot"
    ]
  },
  {
    "href": "/lich-van-nien",
    "quick": {
      "label": "Lịch Vạn Niên",
      "tier": "free",
      "group": "theo-mua"
    },
    "home": {
      "n": "Lịch vạn niên",
      "learn": "/learn/trach-cat",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "ngay-gio",
      "emoji": "📅",
      "name": "Lịch Vạn Niên",
      "desc": "Tra cứu ngày tốt xấu, giờ hoàng đạo, lịch âm dương đầy đủ."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Lịch Vạn Niên",
    "related": [
      "/xem-ngay",
      "/gio-hoang-dao",
      "/ngay-kieng-ky",
      "/sao-han"
    ]
  },
  {
    "href": "/xem-ngay",
    "quick": {
      "label": "Xem ngày tốt",
      "tier": "free",
      "group": "theo-mua"
    },
    "home": {
      "n": "Xem ngày tốt",
      "learn": "/learn/trach-cat",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "ngay-gio",
      "emoji": "📅",
      "name": "Xem Ngày Tốt",
      "desc": "Chọn ngày đẹp cho cưới hỏi, khai trương, động thổ, nhập trạch… theo lịch vạn niên."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Xem ngày tốt",
    "related": [
      "/lich-van-nien",
      "/gio-hoang-dao",
      "/ngay-kieng-ky",
      "/xuat-hanh"
    ]
  },
  {
    "href": "/gio-hoang-dao",
    "quick": {
      "label": "Giờ hoàng đạo",
      "tier": "free",
      "group": "theo-mua"
    },
    "home": {
      "n": "Giờ hoàng đạo",
      "learn": "/learn/trach-cat",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "ngay-gio",
      "emoji": "🕐",
      "name": "Giờ Hoàng Đạo",
      "desc": "Tra giờ tốt (hoàng đạo) trong ngày — đổi theo từng ngày, kèm gợi ý giờ tốt kế tiếp."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Giờ hoàng đạo",
    "related": [
      "/xem-ngay",
      "/ngay-kieng-ky",
      "/xuat-hanh",
      "/lich-van-nien"
    ]
  },
  {
    "href": "/xuat-hanh",
    "catalog": {
      "cat": "ngay-gio",
      "emoji": "🧭",
      "name": "Hướng & Giờ Xuất Hành",
      "desc": "Tra hướng Hỷ Thần, Tài Thần và giờ hoàng đạo để xuất hành — tính theo Can-Chi từng ngày."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Hướng & giờ xuất hành",
    "related": [
      "/gio-hoang-dao",
      "/xem-ngay",
      "/ngay-kieng-ky",
      "/lich-van-nien"
    ]
  },
  {
    "href": "/ngay-kieng-ky",
    "quick": {
      "label": "Ngày kiêng kỵ",
      "tier": "free",
      "group": "theo-mua"
    },
    "home": {
      "n": "Ngày kiêng kỵ",
      "learn": "/learn/trach-cat",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "ngay-gio",
      "emoji": "🗓️",
      "name": "Ngày Kiêng Kỵ",
      "desc": "Tra ngày Tam Nương, Nguyệt Kỵ, Dương Công Kỵ Nhật — ngày nên tránh việc lớn theo phong tục."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Ngày kiêng kỵ",
    "related": [
      "/xem-ngay",
      "/gio-hoang-dao",
      "/lich-van-nien",
      "/xuat-hanh"
    ]
  },
  {
    "href": "/thien-van",
    "quick": {
      "label": "Lịch thiên văn",
      "tier": "free",
      "group": "theo-mua"
    },
    "home": {
      "n": "Lịch thiên văn",
      "learn": "/learn/trach-cat",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "ngay-gio",
      "emoji": "🌘",
      "name": "Lịch thiên văn",
      "desc": "Nhật thực, nguyệt thực và bốn điểm phân–chí 2026–2030 quan sát tại Việt Nam."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "related": [
      "/lich-van-nien",
      "/gio-hoang-dao",
      "/xem-ngay",
      "/ban-do-sao"
    ]
  },
  {
    "href": "/xem-tuoi-cuoi",
    "quick": {
      "label": "Xem tuổi cưới",
      "tier": "free",
      "group": "xem-tuoi"
    },
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "💍",
      "name": "Xem Tuổi Cưới",
      "desc": "Năm này có thuận để cưới không? Tính Kim Lâu, Tam Tai, xung năm theo năm sinh — minh bạch từng bước."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Xem tuổi cưới",
    "related": [
      "/kim-lau",
      "/tam-tai",
      "/hop-tuoi",
      "/xem-ngay",
      "/xem-tuoi-lam-nha"
    ]
  },
  {
    "href": "/xem-tuoi-lam-nha",
    "quick": {
      "label": "Xem tuổi làm nhà",
      "tier": "free",
      "group": "xem-tuoi"
    },
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "🏠",
      "name": "Xem Tuổi Làm Nhà",
      "desc": "Năm này có được tuổi xây/sửa nhà không? Tính Kim Lâu, Hoang Ốc, Tam Tai — kèm cách kiểm tra người mượn tuổi."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Xem tuổi làm nhà",
    "related": [
      "/tam-tai",
      "/huong-nha",
      "/xem-ngay",
      "/thuoc-lo-ban",
      "/xem-tuoi-cuoi"
    ]
  },
  {
    "href": "/khai-truong",
    "quick": {
      "label": "Xem tuổi khai trương",
      "tier": "free",
      "group": "xem-tuoi"
    },
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "🎉",
      "name": "Xem Tuổi Khai Trương",
      "desc": "Năm này có hợp tuổi khai trương / mở hàng không? Tính Tam Tai, xung Thái Tuế theo tuổi chủ — minh bạch từng bước."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Xem tuổi khai trương",
    "related": [
      "/tam-tai",
      "/xem-ngay",
      "/xem-tuoi-cuoi",
      "/hop-tuoi",
      "/sao-han"
    ]
  },
  {
    "href": "/tam-tai",
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "🗓️",
      "name": "Tam Tai",
      "desc": "Tuổi nào phạm Tam Tai và vào những năm nào? Tra theo nhóm tam hợp năm sinh — phong tục để tham khảo, không hù dọa."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Tam Tai",
    "related": [
      "/xem-tuoi-cuoi",
      "/kim-lau",
      "/sao-han",
      "/hop-tuoi"
    ]
  },
  {
    "href": "/kim-lau",
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "💍",
      "name": "Kim Lâu",
      "desc": "Tuổi Kim Lâu cô dâu là gì, năm nào phạm? Tra theo tuổi mụ (chia 9) — phong tục cưới hỏi để tham khảo, không hù dọa."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Kim Lâu (tuổi cưới)",
    "related": [
      "/xem-tuoi-cuoi",
      "/tam-tai",
      "/xem-ngay",
      "/hop-tuoi"
    ]
  },
  {
    "href": "/xong-dat",
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "🧧",
      "name": "Tuổi Xông Đất",
      "desc": "Gợi ý tuổi xông đất Tết Đinh Mùi 2027 theo tam hợp, lục hợp & ngũ hành — minh bạch, tham khảo."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Tuổi xông đất",
    "related": [
      "/hop-tuoi",
      "/xem-tuoi-cuoi",
      "/tu-vi-2027",
      "/xem-ngay"
    ]
  },
  {
    "href": "/hop-tuoi",
    "quick": {
      "label": "Hợp tuổi",
      "tier": "free",
      "group": "co-hoc"
    },
    "home": {
      "n": "Hợp tuổi",
      "learn": "/learn/hop-tuoi",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "💑",
      "name": "Hợp Tuổi",
      "desc": "Kiểm tra hợp tuổi vợ chồng, xây dựng, xuất hành theo tam hợp."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Xem hợp tuổi",
    "related": [
      "/xem-hop-nhom",
      "/compatibility",
      "/dat-ten-ngu-hanh",
      "/sao-han",
      "/learn/hop-tuoi"
    ]
  },
  {
    "href": "/huong-nha",
    "quick": {
      "label": "Xem hướng nhà",
      "tier": "free",
      "group": "xem-tuoi"
    },
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "🧭",
      "name": "Xem Hướng Nhà",
      "desc": "Hướng nhà hợp tuổi theo Bát Trạch (cung phi): 4 hướng tốt – 4 hướng tránh cho cửa, giường, bếp."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Xem hướng nhà",
    "related": [
      "/phi-tinh",
      "/thuoc-lo-ban",
      "/ban-menh",
      "/huong-ban-lam-viec",
      "/xem-tuoi-lam-nha"
    ]
  },
  {
    "href": "/thuoc-lo-ban",
    "quick": {
      "label": "Thước Lỗ Ban",
      "tier": "free",
      "group": "co-hoc"
    },
    "home": {
      "n": "Thước Lỗ Ban",
      "learn": "/learn/phong-thuy",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "📐",
      "name": "Thước Lỗ Ban",
      "desc": "Đo kích thước cát hung theo thước phong thủy truyền thống."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Thước Lỗ Ban",
    "related": [
      "/lich-van-nien",
      "/gio-hoang-dao",
      "/xem-ngay"
    ]
  },
  {
    "href": "/phi-tinh",
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "🧭",
      "name": "Huyền Không Phi Tinh",
      "desc": "Lập bàn phi tinh 9 cung theo nguyên vận + hướng nhà: vận/sơn/hướng tinh, phán Vượng sơn Vượng hướng. Lý khí, con số thật."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Huyền Không Phi Tinh",
    "related": [
      "/huong-nha",
      "/thuoc-lo-ban",
      "/ban-menh",
      "/xem-tuoi-lam-nha",
      "/learn/phong-thuy"
    ]
  },
  {
    "href": "/mau-xe-hop-menh",
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "🚗",
      "name": "Màu Xe Hợp Mệnh",
      "desc": "Sinh năm nào hợp màu xe gì? Tra theo ngũ hành bản mệnh — màu hợp và màu nên cân nhắc, để tham khảo, không hù dọa."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Màu xe hợp mệnh",
    "related": [
      "/ban-menh",
      "/huong-nha",
      "/huong-ban-lam-viec",
      "/hop-tuoi"
    ]
  },
  {
    "href": "/huong-ban-lam-viec",
    "catalog": {
      "cat": "xem-tuoi",
      "emoji": "🪑",
      "name": "Hướng Bàn Làm Việc",
      "desc": "Nên ngồi quay mặt về hướng nào khi làm việc, khi học? Tra theo Bát Trạch (cung phi) từ năm sinh — để tham khảo, không hù dọa."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Hướng bàn làm việc",
    "related": [
      "/huong-nha",
      "/ban-menh",
      "/mau-xe-hop-menh",
      "/thuoc-lo-ban",
      "/learn/phong-thuy"
    ]
  },
  {
    "href": "/compatibility",
    "catalog": {
      "cat": "quan-he",
      "emoji": "💞",
      "name": "Hợp Đôi",
      "desc": "Đo độ hợp giữa hai người — tính cách, cảm xúc và mẫu hình tương tác."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Hợp đôi",
    "related": [
      "/hop-tuoi",
      "/xem-hop-nhom",
      "/mbti"
    ]
  },
  {
    "href": "/xem-hop-nhom",
    "quick": {
      "label": "Xem hợp nhóm / gia đình",
      "tier": "free",
      "group": "kham-pha"
    },
    "catalog": {
      "cat": "quan-he",
      "emoji": "👨‍👩‍👧‍👦",
      "name": "Xem Hợp Nhóm",
      "desc": "Thêm 3–6 người (gia đình, nhóm bạn) — điểm hoà hợp chung, từng cặp và gợi ý phối hợp."
    },
    "surfaces": [
      "drawer",
      "catalog"
    ],
    "relatedLabel": "Hợp nhóm",
    "related": [
      "/hop-tuoi",
      "/compatibility",
      "/mbti"
    ]
  },
  {
    "href": "/family-profiles",
    "catalog": {
      "cat": "quan-he",
      "emoji": "👪",
      "name": "Hồ Sơ Gia Đình",
      "desc": "Lưu hồ sơ cả nhà một chỗ — hiểu tính cách, hợp khắc và cách phối hợp giữa các thành viên."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Hồ sơ gia đình",
    "related": [
      "/xem-hop-nhom",
      "/compatibility",
      "/hop-tuoi",
      "/sinh-con"
    ]
  },
  {
    "href": "/sinh-con",
    "catalog": {
      "cat": "quan-he",
      "emoji": "👶",
      "name": "Sinh Con Theo Năm",
      "desc": "Mệnh & con giáp của bé theo năm sinh + đối chiếu tuổi bố mẹ — tham khảo phong tục."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Sinh con theo năm",
    "related": [
      "/dat-ten-ngu-hanh",
      "/hop-tuoi",
      "/ban-menh",
      "/xem-tuoi-cuoi"
    ]
  },
  {
    "href": "/dat-ten-ngu-hanh",
    "quick": {
      "label": "Đặt tên ngũ hành",
      "tier": "free",
      "group": "co-hoc"
    },
    "home": {
      "n": "Đặt tên ngũ hành",
      "learn": "/learn/dat-ten-ngu-hanh",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "quan-he",
      "emoji": "🌱",
      "name": "Đặt Tên Ngũ Hành",
      "desc": "Tra mệnh ngũ hành của bé theo ngày sinh + gợi ý tên hợp mệnh — gợi ý tham khảo."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Đặt tên ngũ hành",
    "related": [
      "/sinh-con",
      "/ban-menh",
      "/bat-tu"
    ]
  },
  {
    "href": "/so-sanh",
    "quick": {
      "label": "So sánh lăng kính",
      "tier": "free",
      "group": "kham-pha"
    },
    "home": {
      "n": "So sánh lăng kính",
      "group": "Khám phá & so sánh"
    },
    "catalog": {
      "cat": "kham-pha",
      "emoji": "🪞",
      "name": "So Sánh Lăng Kính",
      "desc": "Đặt hai lăng kính cạnh nhau — MBTI vs Big Five, Tử Vi vs Bát Tự… thấy rõ mỗi hệ soi sáng điều gì."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "So sánh lăng kính",
    "related": [
      "/mbti",
      "/big-five",
      "/disc"
    ]
  },
  {
    "href": "/decision-simulator",
    "catalog": {
      "cat": "kham-pha",
      "emoji": "🔀",
      "name": "Mô Phỏng Quyết Định",
      "desc": "Đặt 2 lựa chọn cạnh nhau — đối chiếu theo lá số để thấy mỗi hướng nghiêng về điều gì."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Mô phỏng quyết định",
    "related": [
      "/so-sanh",
      "/career-fit",
      "/mbti",
      "/gieo-que"
    ]
  },
  {
    "href": "/career-fit",
    "catalog": {
      "cat": "kham-pha",
      "emoji": "🧩",
      "name": "Nhóm Nghề",
      "desc": "Gợi ý nhóm ngành nghề hợp với thiên hướng của bạn — từ tính cách và lá số."
    },
    "surfaces": [
      "catalog"
    ],
    "relatedLabel": "Nghề phù hợp",
    "related": [
      "/mbti",
      "/disc",
      "/tu-vi-nghe-nghiep"
    ]
  },
  {
    "href": "/gieo-que",
    "quick": {
      "label": "Gieo Quẻ Kinh Dịch",
      "tier": "free",
      "group": "co-hoc"
    },
    "home": {
      "n": "Kinh Dịch",
      "learn": "/learn/kinh-dich",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "kham-pha",
      "emoji": "🪬",
      "name": "Gieo Quẻ",
      "desc": "Kinh Dịch 64 quẻ — hỏi thời thế, nhận chỉ dẫn từ âm dương."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Gieo quẻ Kinh Dịch",
    "related": [
      "/tarot",
      "/xem-tuong",
      "/tu-vi",
      "/learn/kinh-dich"
    ]
  },
  {
    "href": "/can-xuong",
    "quick": {
      "label": "Cân Xương Đoán Số",
      "tier": "free",
      "group": "co-hoc"
    },
    "home": {
      "n": "Cân Xương",
      "learn": "/learn/can-xuong",
      "group": "Cổ học Á Đông"
    },
    "catalog": {
      "cat": "kham-pha",
      "emoji": "⚖️",
      "name": "Cân Xương",
      "desc": "Luận cân nặng xương theo ngày sinh — luận mệnh dân gian."
    },
    "surfaces": [
      "drawer",
      "home",
      "catalog"
    ],
    "relatedLabel": "Cân xương",
    "related": [
      "/tu-vi",
      "/bat-tu",
      "/than-so-hoc",
      "/sao-han"
    ]
  },
  {
    "href": "/hoi-dap",
    "home": {
      "n": "Hỏi đáp",
      "group": "Khám phá & so sánh"
    },
    "catalog": {
      "cat": "kham-pha",
      "emoji": "💬",
      "name": "Hỏi Đáp",
      "desc": "Giải đáp ngắn gọn những thắc mắc thường gặp về tử vi, bát tự và các công cụ tâm lý."
    },
    "surfaces": [
      "home",
      "catalog"
    ],
    "relatedLabel": "Hỏi đáp",
    "related": [
      "/tu-vi",
      "/mbti",
      "/gieo-que"
    ]
  },
  {
    "href": "/tu-kiem",
    "catalog": {
      "cat": "kham-pha",
      "emoji": "🪞",
      "name": "Tự kiểm — Đừng tin mù",
      "desc": "Bài 1 phút: vì sao lời bói luôn thấy \"đúng ghê\" và cách không bị lừa."
    },
    "surfaces": [
      "catalog"
    ],
    "related": [
      "/so-sanh",
      "/hoi-dap",
      "/gieo-que",
      "/tarot"
    ]
  },
  {
    "href": "/tu-vi",
    "home": {
      "n": "Tử Vi",
      "learn": "/learn/tu-vi",
      "group": "Cổ học Á Đông"
    },
    "surfaces": [
      "home"
    ],
    "relatedLabel": "Tử Vi",
    "related": [
      "/tu-vi-2027",
      "/bat-tu",
      "/than-so-hoc",
      "/tinh-menh-cuc",
      "/lich-van-nien",
      "/bang-chung"
    ]
  },
  {
    "href": "/bat-tu",
    "quick": {
      "label": "Bát Tự",
      "tier": "free",
      "group": "co-hoc"
    },
    "home": {
      "n": "Bát Tự",
      "learn": "/learn/bat-tu",
      "group": "Cổ học Á Đông"
    },
    "surfaces": [
      "drawer",
      "home"
    ],
    "relatedLabel": "Bát Tự",
    "related": [
      "/tu-vi",
      "/than-so-hoc",
      "/can-xuong",
      "/dat-ten-ngu-hanh",
      "/learn/bat-tu"
    ]
  },
  {
    "href": "/learn/bat-tu",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Bát Tự"
  },
  {
    "href": "/learn/than-so-hoc",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Thần số học"
  },
  {
    "href": "/learn/mbti",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu MBTI"
  },
  {
    "href": "/learn/big-five",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Big Five"
  },
  {
    "href": "/learn/disc",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu DISC"
  },
  {
    "href": "/learn/enneagram",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Enneagram"
  },
  {
    "href": "/learn/palm",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Xem tướng"
  },
  {
    "href": "/learn/tarot",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Tarot"
  },
  {
    "href": "/learn/kinh-dich",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Kinh Dịch"
  },
  {
    "href": "/learn/sao-han",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Sao hạn"
  },
  {
    "href": "/learn/hop-tuoi",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu hợp tuổi"
  },
  {
    "href": "/learn/phong-thuy",
    "surfaces": [],
    "relatedLabel": "Tìm hiểu Phong thuỷ"
  }
];

/** Drawer/footer display order (QUICK_LOOKUP). */
export const QUICK_ORDER: string[] = [
  "/tu-vi-2027",
  "/tu-vi-2026",
  "/tu-vi-hom-nay",
  "/hop-tuoi",
  "/can-xuong",
  "/lich-van-nien",
  "/xem-ngay",
  "/sao-han",
  "/gio-hoang-dao",
  "/thien-van",
  "/ngay-kieng-ky",
  "/dat-ten-ngu-hanh",
  "/bat-tu",
  "/mbti",
  "/than-so-hoc",
  "/thuoc-lo-ban",
  "/tinh-menh-cuc",
  "/ban-do-sao",
  "/cung-hoang-dao",
  "/tarot",
  "/dai-van-hien-tai",
  "/gieo-que",
  "/big-five",
  "/disc",
  "/enneagram",
  "/xem-tuong",
  "/xem-hop-nhom",
  "/so-sanh",
  "/xem-tuoi-cuoi",
  "/xem-tuoi-lam-nha",
  "/huong-nha",
  "/khai-truong"
];

/** Homepage marquee grouping + within-group order (TOOLKIT_GROUPS). */
export const HOME_GROUPS_ORDER: { label: string; hrefs: string[] }[] = [
  {
    "label": "Cổ học Á Đông",
    "hrefs": [
      "/tu-vi",
      "/bat-tu",
      "/xem-tuong",
      "/than-so-hoc",
      "/gieo-que",
      "/can-xuong",
      "/thuoc-lo-ban",
      "/hop-tuoi",
      "/lich-van-nien",
      "/xem-ngay",
      "/sao-han",
      "/gio-hoang-dao",
      "/thien-van",
      "/ngay-kieng-ky",
      "/dat-ten-ngu-hanh"
    ]
  },
  {
    "label": "Tâm lý hiện đại",
    "hrefs": [
      "/mbti",
      "/big-five",
      "/disc",
      "/enneagram"
    ]
  },
  {
    "label": "Chiêm tinh phương Tây",
    "hrefs": [
      "/ban-do-sao",
      "/cung-hoang-dao"
    ]
  },
  {
    "label": "Trực giác",
    "hrefs": [
      "/tarot"
    ]
  },
  {
    "label": "Khám phá & so sánh",
    "hrefs": [
      "/so-sanh",
      "/hoi-dap"
    ]
  }
];

const byHref = new Map(TOOL_REGISTRY.map((e) => [e.href, e]));
const need = (h: string): ToolEntry => { const e = byHref.get(h); if (!e) throw new Error('site-registry: unknown href ' + h); return e; };

/** Flat quick-lookup list — mobile drawer. Derived, do not hand-edit. */
export function toQuickLookup(): QuickTool[] {
  return QUICK_ORDER.map((h) => {
    const q = need(h).quick!;
    return q.group !== undefined ? { href: h, label: q.label, tier: q.tier, group: q.group } : { href: h, label: q.label, tier: q.tier };
  });
}
export const QUICK_LOOKUP: QuickTool[] = toQuickLookup();

/** Homepage grouped showcase. Derived, do not hand-edit. */
export function toToolkitGroups(): ToolGroup[] {
  return HOME_GROUPS_ORDER.map((g) => ({
    label: g.label,
    tools: g.hrefs.map((h) => { const hm = need(h).home!; return hm.learn !== undefined ? { n: hm.n, href: h, learn: hm.learn } : { n: hm.n, href: h }; }),
  }));
}
export const TOOLKIT_GROUPS: ToolGroup[] = toToolkitGroups();

/** /cong-cu catalog list. Derived, do not hand-edit. */
export function toCatalogTools(): ExplorerTool[] {
  return TOOL_REGISTRY.filter((e) => e.catalog).map((e) => ({ cat: e.catalog!.cat, href: e.href, emoji: e.catalog!.emoji, name: e.catalog!.name, desc: e.catalog!.desc }));
}
export const CATALOG_TOOLS: ExplorerTool[] = toCatalogTools();

/** Related-tools map keyed by route. Derived, do not hand-edit. */
export function toRelatedTools(): Record<string, RelatedLink[]> {
  const out: Record<string, RelatedLink[]> = {};
  for (const e of TOOL_REGISTRY) if (e.related) out[e.href] = e.related.map((t) => ({ href: t, label: need(t).relatedLabel! }));
  return out;
}
export const RELATED_TOOLS: Record<string, RelatedLink[]> = toRelatedTools();
