// hieu.asia — Nội dung trang ý nghĩa 56 lá Ẩn phụ (Minor Arcana), đợt 2 thư viện tarot.
// Nghĩa theo truyền thống Rider–Waite–Smith, giọng phản tư của site (gợi câu hỏi, không phán).
// Khác engine lib/tools/tarot.ts (nghĩa 1 dòng cho lượt rút): đây là dữ liệu BIÊN TẬP cho trang tĩnh.
// name_vi khớp đúng tên hiển thị của engine ("Át Gậy" … "Vua Tiền") để người rút tra được lá vừa gặp.

import type { TarotCardPage } from './tarot-card-pages';

export const MINOR_PAGES: TarotCardPage[] = [
  // ============ GẬY (Wands) — lửa: hành động, đam mê, năng lượng ============
  {
    slug: 'ace-of-wands',
    name: 'Ace of Wands',
    name_vi: 'Át Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 1,
    keyUp: ['tia cảm hứng', 'khởi sự', 'đam mê mới'],
    keyRev: ['hứng tắt nhanh', 'trì hoãn khởi đầu'],
    image:
      'Một bàn tay vươn ra từ mây, nắm cây gậy còn đang đâm chồi xanh. Năng lượng sống ở dạng thô nhất: một xung lực muốn-bắt-đầu.',
    up: 'Át Gậy là tia lửa: một ý tưởng, một cơ hội, một việc khiến bạn rạo rực muốn làm ngay. Lá này không hứa kết quả — nó chỉ xác nhận rằng nguồn năng lượng đang có thật, và năng lượng kiểu này không giữ được lâu trong kho. Cách dùng tốt nhất: biến hứng thành một bước thử nhỏ trong vòng vài ngày, trước khi đời thường kịp dập tắt nó.',
    rev: 'Chiều ngược là cái hứng bị nghẽn: ý tưởng nằm trong sổ tay mãi không thành việc, hoặc bắt đầu rồi xìu sau ba hôm. Đáng hỏi: thứ này thật sự là đam mê của bạn — hay chỉ là cơn hào hứng mượn từ người khác?',
    love: 'Trong tình cảm: một rung động mới, hoặc lửa cũ bỗng được khơi lại. Đừng phân tích vội — cho cảm xúc này một cơ hội được thử.',
    work: 'Trong công việc: thời điểm tốt để pitch ý tưởng, mở dự án, học thứ mình tò mò. Bước thử rẻ nhất trong tuần này là gì?',
    reflect: [
      'Ý tưởng nào khiến bạn háo hức ba ngày liên tiếp gần đây?',
      'Nếu chỉ có một giờ để bắt đầu nó ngay hôm nay, bạn sẽ làm gì trong giờ đó?',
    ],
  },
  {
    slug: 'two-of-wands',
    name: 'Two of Wands',
    name_vi: 'Hai Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 2,
    keyUp: ['tầm nhìn', 'lập kế hoạch', 'chọn hướng đi'],
    keyRev: ['sợ rời vùng an toàn', 'kế hoạch trên giấy'],
    image:
      'Một người đứng trên tường lâu đài, tay cầm quả địa cầu nhỏ, mắt nhìn ra biển. Thế giới trong tay — nhưng vẫn đang đứng trong tường thành của mình.',
    up: 'Hai Gậy là khoảnh khắc sau tia lửa: bạn đã có ý định, giờ là lúc ngắm bản đồ — đi đâu, đánh đổi gì, phạm vi nào vừa sức. Lá này quý ở chỗ nó cho phép tham vọng: dám hình dung một tương lai lớn hơn hiện tại. Kế hoạch tốt không phải kế hoạch hoàn hảo, mà là kế hoạch đủ rõ để bước chân đầu tiên biết đặt vào đâu.',
    rev: 'Ngược chiều, quả địa cầu vẫn nằm trong tay mà chân không rời tường thành: tính mãi, cân nhắc mãi, an toàn quá lâu. Một kế hoạch không có ngày bắt đầu chỉ là một giấc mơ có gạch đầu dòng.',
    love: 'Trong tình cảm: hai người nên ngồi vẽ chung một bức tranh xa hơn — sống ở đâu, tiền bạc thế nào, muốn đời chung ra sao. Khác tầm nhìn không đáng sợ bằng không ai dám nói tầm nhìn của mình.',
    work: 'Trong công việc: thời điểm hoạch định — mở rộng hay đào sâu, thị trường nào, kỹ năng nào cần trước. Viết kế hoạch ra giấy kèm một mốc ngày cụ thể.',
    reflect: [
      'Bức tranh 3 năm tới bạn thật sự muốn trông như thế nào — nói to lên được không?',
      'Điều gì giữ bạn trong "tường thành" hiện tại: sự hợp lý, hay sự quen?',
    ],
  },
  {
    slug: 'three-of-wands',
    name: 'Three of Wands',
    name_vi: 'Ba Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 3,
    keyUp: ['có trớn ban đầu', 'mở rộng', 'chờ thuyền về'],
    keyRev: ['chậm trễ', 'kỳ vọng lệch thực tế'],
    image:
      'Người đàn ông đứng trên đồi cao nhìn ra biển, ba cây gậy cắm vững quanh mình, những con thuyền đang dong buồm phía xa. Việc đã khởi hành — giờ là đoạn giữ nhịp và ngóng kết quả.',
    up: 'Ba Gậy là giai đoạn việc đã chạy: những gì bạn gieo bắt đầu có trớn, cơ hội mở rộng xuất hiện — đối tác mới, thị trường xa hơn, vòng quan hệ rộng hơn. Lá này gợi tư thế chủ động chờ: không ngồi không, mà chuẩn bị sẵn bến bãi cho lúc thuyền về. Tầm nhìn đã thành chuyển động; đừng quay đầu giữa chừng chỉ vì kết quả chưa cập cảng.',
    rev: 'Ngược chiều: thuyền về chậm hơn hẹn, hoặc chở về thứ khác kỳ vọng. Trước khi nản, kiểm tra lại — kỳ vọng ban đầu có thực tế không, và độ trễ này là tín hiệu xấu hay chỉ là nhịp bình thường của biển?',
    love: 'Trong tình cảm: mối quan hệ cần không gian lớn hơn — chuyến đi chung, kế hoạch chung, hoặc đơn giản là dám nghĩ xa hơn vài tháng tới.',
    work: 'Trong công việc: kết quả đầu tiên ló dạng — đúng lúc cân nhắc mở rộng. Nhưng mở rộng trên cái đang chạy tốt, đừng mở rộng để chạy trốn cái đang dở dang.',
    reflect: [
      '"Con thuyền" nào bạn đã thả đi và đang ngóng — bạn đã chuẩn bị gì cho lúc nó về?',
      'Nếu kết quả về chậm 3 tháng so với mong đợi, kế hoạch của bạn còn đứng vững không?',
    ],
  },
  {
    slug: 'four-of-wands',
    name: 'Four of Wands',
    name_vi: 'Bốn Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 4,
    keyUp: ['ăn mừng', 'mái ấm', 'cột mốc', 'sum họp'],
    keyRev: ['cột mốc bị bỏ quên', 'bất ổn chỗ ở'],
    image:
      'Bốn cây gậy dựng thành cổng kết hoa, hai người nâng bó hoa chào đón, phía sau là tòa nhà vững và đám đông vui. Hình ảnh của lễ mừng và một nơi để trở về.',
    up: 'Bốn Gậy là cột mốc đáng mừng: tân gia, cưới hỏi, xong một chặng, đội nhóm gắn kết, gia đình sum vầy. Lá này nhắc một việc người chăm chỉ hay quên: dừng lại ăn mừng. Niềm vui được đánh dấu tử tế sẽ thành ký ức nuôi mình lúc khó; thành quả không được ăn mừng thì chỉ là một dòng gạch đầu dòng trôi qua.',
    rev: 'Ngược chiều: một cột mốc đi qua mà không ai buồn đánh dấu, hoặc cảm giác "nhà" đang lung lay — nơi ở, nơi làm, nhóm bạn không còn cho cảm giác thuộc về. Đáng hỏi: bạn cần sửa chỗ đứng, hay cần tìm chỗ mới?',
    love: 'Trong tình cảm: giai đoạn ấm — ra mắt, về chung, kỷ niệm. Hãy là người chủ động tạo dịp; sự gắn bó được nuôi bằng những lễ nhỏ đều đặn hơn là lễ to hiếm hoi.',
    work: 'Trong công việc: dự án cán mốc — tổ chức một buổi tổng kết tử tế cho cả nhóm. Văn hóa ăn mừng đúng lúc giữ người giỏi hơn lương thưởng đơn thuần.',
    reflect: [
      'Thành quả nào gần đây của bạn xứng đáng một bữa ăn mừng mà bạn đã bỏ qua?',
      'Nơi nào cho bạn cảm giác "về nhà" — và bạn có đang vun cho nơi đó không?',
    ],
  },
  {
    slug: 'five-of-wands',
    name: 'Five of Wands',
    name_vi: 'Năm Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 5,
    keyUp: ['va chạm ý kiến', 'cạnh tranh', 'tập dượt'],
    keyRev: ['cãi vã vô ích', 'né xung đột cần thiết'],
    image:
      'Năm thanh niên khua năm cây gậy vào nhau — nhìn như đánh nhau, nhưng không ai bị thương. Một trận tập dượt nhiều hơn một trận chiến.',
    up: 'Năm Gậy là sự va chạm ồn ào mà ít sát thương: họp hành tranh cãi, đồng nghiệp ganh đua, anh em khắc khẩu. Lá này gợi cách nhìn lành mạnh về xung đột: ý kiến va nhau là cách ý tưởng được tôi luyện — miễn là đánh vào vấn đề, không đánh vào người. Cạnh tranh đúng kiểu làm tất cả cùng giỏi lên.',
    rev: 'Ngược chiều có hai mặt: hoặc cãi nhau triền miên về thứ không đáng (cái tôi đội lốt quan điểm), hoặc né tránh một cuộc tranh luận cần thiết để giữ hòa khí giả. Im lặng cho yên chuyện thường chỉ hoãn chuyện, không yên chuyện.',
    love: 'Trong tình cảm: khắc khẩu chưa chắc là khắc mệnh — nhưng để ý xem hai người đang tranh luận để hiểu nhau, hay để thắng nhau.',
    work: 'Trong công việc: môi trường đang nhiều tiếng nói. Đặt luật chơi cho tranh luận (nói có dữ kiện, không cắt lời, chốt người quyết) sẽ biến ồn ào thành chất lượng.',
    reflect: [
      'Cuộc tranh cãi gần nhất của bạn: đánh vào vấn đề hay đánh vào người?',
      'Có cuộc đối thoại khó nào bạn đang né mà càng né càng phình to?',
    ],
  },
  {
    slug: 'six-of-wands',
    name: 'Six of Wands',
    name_vi: 'Sáu Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 6,
    keyUp: ['thắng lợi', 'được công nhận', 'tin vui'],
    keyRev: ['hư danh', 'sợ thất bại công khai', 'thiếu ghi nhận'],
    image:
      'Người kỵ sĩ đội vòng nguyệt quế cưỡi ngựa qua đám đông, cây gậy trên tay cũng kết vòng hoa. Chiến thắng — và quan trọng không kém: được mọi người nhìn thấy.',
    up: 'Sáu Gậy là tin vui sau nỗ lực: được khen đúng việc, đậu kỳ thi, dự án thành, lời mời tốt tìm đến. Lá này nói về sự công nhận — thứ con người ai cũng cần dù hay chối. Nhận lời khen một cách đàng hoàng ("cảm ơn, tôi đã làm việc thật") cũng là một kỹ năng; khiêm tốn giả vờ đôi khi chỉ là cách từ chối niềm vui của chính mình.',
    rev: 'Ngược chiều: hoặc thành tích chỉ đẹp trên bề mặt (đám đông vỗ tay nhưng mình biết rõ phần rỗng), hoặc nỗ lực thật mà không ai ghi nhận — và bạn bắt đầu nghi ngờ giá trị của mình. Giá trị của việc bạn làm không chờ tiếng vỗ tay mới tồn tại.',
    love: 'Trong tình cảm: đừng tiếc lời ghi nhận nhau — "em thấy anh đã cố" có sức nặng hơn nhiều món quà. Người được nhìn thấy sẽ ở lại.',
    work: 'Trong công việc: thời điểm tốt để trình bày thành quả, xin tăng lương, ứng tuyển vị trí cao hơn. Kể đúng công sức của mình không phải là khoe.',
    reflect: [
      'Lời khen gần nhất bạn nhận: bạn đã đón nó thế nào — và vì sao?',
      'Ai quanh bạn đang xứng đáng một lời ghi nhận mà bạn chưa nói ra?',
    ],
  },
  {
    slug: 'seven-of-wands',
    name: 'Seven of Wands',
    name_vi: 'Bảy Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 7,
    keyUp: ['giữ vững lập trường', 'bảo vệ thành quả', 'kiên cường'],
    keyRev: ['đuối sức', 'cố thủ thứ không đáng'],
    image:
      'Một người đứng trên gò cao, cầm gậy gạt sáu cây gậy chĩa lên từ phía dưới. Vị thế cao hơn — nhưng phải liên tục chống đỡ.',
    up: 'Bảy Gậy xuất hiện khi điều bạn xây bắt đầu bị thách thức: quan điểm bị phản bác, vị trí bị nhòm ngó, lựa chọn sống bị người thân chất vấn. Lá này gợi sự kiên định có căn cứ: nếu bạn đã suy xét kỹ và vẫn tin, hãy giữ — người đứng trên gò có lợi thế, đừng tự bỏ gò chạy xuống. Bị phản đối không có nghĩa là sai; mọi thứ đáng giá đều từng bị phản đối.',
    rev: 'Ngược chiều: cuộc phòng thủ đã kéo quá dài và bạn đuối — hoặc tệ hơn, thứ đang cố thủ không còn đáng để thủ. Kiên định và cố chấp giống nhau ở tư thế, khác nhau ở câu hỏi: "nếu có bằng chứng ngược, mình có đổi ý không?"',
    love: 'Trong tình cảm: có thể bạn đang phải bảo vệ lựa chọn của mình trước gia đình, bạn bè. Nghe hết — rồi tự quyết. Người ngoài góp ý đời bạn, nhưng không sống đời bạn.',
    work: 'Trong công việc: cạnh tranh tăng, ý tưởng bị thử lửa. Chuẩn bị dữ kiện kỹ hơn thay vì nói to hơn.',
    reflect: [
      'Điều bạn đang bảo vệ: bạn giữ nó vì còn tin, hay vì đã lỡ tuyên bố?',
      'Trận nào đáng đánh tiếp, trận nào nên rút để giữ sức cho trận đáng?',
    ],
  },
  {
    slug: 'eight-of-wands',
    name: 'Eight of Wands',
    name_vi: 'Tám Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 8,
    keyUp: ['tăng tốc', 'tin tức dồn dập', 'mọi thứ chuyển động'],
    keyRev: ['chậm trễ', 'loạn nhịp', 'tin nhiễu'],
    image:
      'Tám cây gậy bay song song giữa trời quang, không người, không cản trở. Lá hiếm hoi không có nhân vật — vì nhân vật chính là tốc độ.',
    up: 'Tám Gậy là giai đoạn mọi thứ tăng tốc: tin nhắn dồn về, cơ hội đến nhanh, việc tưởng lâu bỗng xong sớm. Lá này khuyên thuận theo đà: trả lời nhanh, quyết nhanh những thứ đã đủ dữ kiện, đừng để cơ hội nguội vì thói quen "để mai tính". Nhưng tốc độ chỉ đẹp khi có hướng — tám cây gậy bay cùng một phía.',
    rev: 'Ngược chiều: mọi thứ ì lại — chờ phản hồi, chờ duyệt, chờ người. Hoặc ngược lại: quá nhiều thứ bay đến cùng lúc thành nhiễu. Lúc này thứ cần không phải nhanh hơn mà là lọc: việc nào thật sự cần bạn tuần này?',
    love: 'Trong tình cảm: chuyện tiến triển nhanh — nhắn nhiều, gặp dày, cảm xúc tăng tốc. Tận hưởng, nhưng thỉnh thoảng kiểm tra xem cả hai có đang cùng một vận tốc.',
    work: 'Trong công việc: giai đoạn bận tốt — nhiều chuyển động, nhiều phản hồi. Dọn lịch để bắt kịp; một ngày chậm lúc này đắt hơn bình thường.',
    reflect: [
      'Cơ hội nào đang chờ một câu trả lời của bạn lâu hơn mức nó đáng phải chờ?',
      'Tốc độ hiện tại của bạn: đang có hướng, hay chỉ đang có đà?',
    ],
  },
  {
    slug: 'nine-of-wands',
    name: 'Nine of Wands',
    name_vi: 'Chín Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 9,
    keyUp: ['chặng cuối', 'bền bỉ', 'cảnh giác có lý do'],
    keyRev: ['kiệt sức', 'phòng thủ quá đà'],
    image:
      'Người lính băng đầu, tựa vào cây gậy, sau lưng là hàng rào tám cây gậy thẳng đứng. Mệt và đầy vết trận — nhưng vẫn đứng.',
    up: 'Chín Gậy là lá của chặng cuối: đã đi xa, đã trầy trật, và đích thật sự không còn xa. Lá này thừa nhận cái mệt của bạn là có thật — đồng thời nhắc rằng kinh nghiệm từ những lần vấp chính là hàng rào đang bảo vệ bạn. Đừng nhầm "mệt" với "sai đường"; người về đích thường là người chịu mệt thêm đúng một chặng nữa.',
    rev: 'Ngược chiều: sự bền bỉ đã chuyển thành kiệt quệ, hoặc những vết thương cũ làm bạn phòng thủ với cả người không định làm hại mình. Nghỉ không phải là bỏ cuộc — và không phải ai đến gần cũng là để tấn công.',
    love: 'Trong tình cảm: vết thương cũ có thể đang khiến bạn thủ thế với người mới. Cẩn trọng là khôn; mặc nguyên giáp đi hẹn hò thì không.',
    work: 'Trong công việc: dự án ở đoạn 80% — đoạn dễ bỏ nhất. Chia phần còn lại thành mục tiêu thật nhỏ và đi từng bước.',
    reflect: [
      'Thứ bạn sắp bỏ cuộc: còn bao xa nữa thật sự — đã đo chưa, hay chỉ cảm thấy xa?',
      'Hàng rào nào của bạn đang bảo vệ, hàng rào nào đang giam?',
    ],
  },
  {
    slug: 'ten-of-wands',
    name: 'Ten of Wands',
    name_vi: 'Mười Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 10,
    keyUp: ['quá tải', 'gánh nhiều vai', 'trách nhiệm chồng'],
    keyRev: ['buông bớt', 'học từ chối', 'san sẻ'],
    image:
      'Một người ôm cả bó mười cây gậy, còng lưng đi về phía ngôi làng phía xa — gậy che luôn tầm nhìn phía trước. Gánh được, nhưng không thấy đường.',
    up: 'Mười Gậy là sức nặng của thành công: việc nhiều vì bạn làm được việc, vai nhiều vì bạn đáng tin. Nhưng lá này chỉ thẳng cái giá: ôm hết thì lưng còng và mắt không còn thấy hướng. Câu hỏi của nó rất thực dụng: trong bó gậy đang vác, cây nào thật sự phải là của bạn — và cây nào bạn vác chỉ vì không ai dám nói "để tôi".',
    rev: 'Ngược chiều là tin tốt đang đến gần: bạn bắt đầu thấy mình không cần vác hết — giao bớt, từ chối bớt, bỏ hẳn vài thứ. Buông một việc không quan trọng để làm tốt việc quan trọng không phải là thất hứa, đó là trung thực về giới hạn.',
    love: 'Trong tình cảm: một người gánh hết — tiền, nhà cửa, cảm xúc — lâu dần sẽ thành một người oán thầm. Chia gánh là việc của hai người, nói ra là bước đầu.',
    work: 'Trong công việc: liệt kê mọi việc đang ôm, đánh dấu thứ chỉ-mình-làm-được. Phần còn lại: giao, hoãn, hoặc bỏ.',
    reflect: [
      'Việc nào bạn đang vác mà thật ra không ai yêu cầu bạn vác?',
      'Nếu buộc phải bỏ 3 thứ khỏi vai trong tuần này, bạn bỏ gì — và điều gì cản bạn làm thế ngay?',
    ],
  },
  {
    slug: 'page-of-wands',
    name: 'Page of Wands',
    name_vi: 'Thị Đồng Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 11,
    keyUp: ['tò mò', 'tin vui về cơ hội', 'tinh thần thử nghiệm'],
    keyRev: ['cả thèm chóng chán', 'thiếu kiên trì'],
    image:
      'Chàng trai trẻ giữa sa mạc, ngắm cây gậy đâm chồi trên tay như ngắm một điều kỳ diệu nhỏ. Chưa có chiến tích — nhưng có thứ quý không kém: sự háo hức.',
    up: 'Thị Đồng Gậy là tinh thần người mới bắt đầu: tò mò, dám thử, chưa bị kinh nghiệm làm cho rụt rè. Lá này hay báo một tin vui nhỏ về cơ hội — lời rủ rê một dự án, một lớp học, một chuyến đi. Nó cũng nhắc người đã "già nghề": thử làm lại điều gì đó với con mắt lần đầu, bạn sẽ thấy thứ mà sự thành thạo che mất.',
    rev: 'Ngược chiều: hứng nhanh nguội nhanh, nhảy từ thứ này sang thứ khác mà không thứ nào quá ba tuần. Tò mò là tài sản; tò mò không có điểm đáp thì chỉ là giải trí.',
    love: 'Trong tình cảm: năng lượng tán tỉnh, rủ rê, làm quen — vui và nhẹ. Cứ để nhẹ, nhưng chân thành: đùa vui khác với đùa giỡn cảm xúc người khác.',
    work: 'Trong công việc: hợp giai đoạn học việc, thử vai mới, làm prototype. Cho phép mình làm dở lúc đầu — đó là học phí rẻ nhất.',
    reflect: [
      'Lần gần nhất bạn thử một thứ hoàn toàn mới là khi nào?',
      'Trong các thứ đang "thèm thử", thứ nào bạn sẵn lòng theo ít nhất ba tháng?',
    ],
  },
  {
    slug: 'knight-of-wands',
    name: 'Knight of Wands',
    name_vi: 'Hiệp Sĩ Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 12,
    keyUp: ['nhiệt huyết', 'hành động táo bạo', 'lao về mục tiêu'],
    keyRev: ['bốc đồng', 'hứa rồi rời đi', 'nóng vội'],
    image:
      'Hiệp sĩ trên lưng ngựa chồm vó, áo giáp điểm hình kỳ nhông lửa, lông mũ như ngọn lửa bốc. Năng lượng đẹp nhất và khó kiểm soát nhất của bộ Gậy.',
    up: 'Hiệp Sĩ Gậy là cú lao tới: nhận việc khó, chuyển nơi sống, theo đuổi điều mình muốn một cách công khai và rực rỡ. Lá này quý ở sự dứt khoát — trong khi người khác còn cân nhắc, bạn đã ở trên đường. Có những cánh cửa chỉ mở cho người dám gõ mạnh.',
    rev: 'Ngược chiều: lửa thành bốc đồng — quyết trong cơn hứng, hứa trong cơn vui, rồi nguội giữa chừng để lại dở dang cho người khác dọn. Trước cú lao kế tiếp, trả lời một câu: "ai sẽ gánh nếu mình đổi ý?"',
    love: 'Trong tình cảm: cuốn hút mãnh liệt, tiến nhanh, nhiều cử chỉ lớn. Đẹp — nếu đi kèm khả năng ở lại khi hết tuần trăng mật. Nhìn hành động lặp lại, đừng chỉ nhìn màn mở đầu.',
    work: 'Trong công việc: hợp các cú đẩy lớn — ra mắt, chạy chiến dịch, mở thị trường. Cặp với một người giỏi vận hành để lửa của bạn không đốt luôn quy trình.',
    reflect: [
      'Điều gì bạn đang muốn lao vào — và bạn đã hình dung tới tuần thứ sáu chưa, hay mới tới ngày khai trương?',
      'Lời hứa nào bạn từng buông giữa chừng — nó dạy bạn gì về lời hứa sắp tới?',
    ],
  },
  {
    slug: 'queen-of-wands',
    name: 'Queen of Wands',
    name_vi: 'Hoàng Hậu Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 13,
    keyUp: ['tự tin ấm áp', 'truyền cảm hứng', 'sống rõ mình'],
    keyRev: ['cạn năng lượng', 'so sánh', 'ghen tị ngầm'],
    image:
      'Hoàng hậu ngồi thẳng, tay cầm gậy, tay cầm hoa hướng dương, con mèo đen ngồi dưới chân. Rực rỡ mà không chói; có cả phần bóng tối được thuần hóa.',
    up: 'Hoàng Hậu Gậy là kiểu tự tin làm người khác ấm lên thay vì lép vế: biết mình muốn gì, nói được điều mình nghĩ, và còn dư năng lượng để cổ vũ người bên cạnh. Lá này gợi bạn bước ra ánh sáng của chính mình — nhận vai chính trong đời mình thay vì làm khán giả nhiệt tình của đời người khác.',
    rev: 'Ngược chiều: pin cạn — vẫn phải tươi cười vận hành mọi thứ trong khi bên trong đã mỏi; hoặc ngọn lửa chuyển thành so sánh, ghen tị ngầm với người đang rực rỡ hơn. Người khác tỏa sáng không làm tối phần của bạn.',
    love: 'Trong tình cảm: sự cuốn hút của bạn nằm ở việc sống đúng mình — đừng gọt bớt cá tính cho vừa một khuôn. Người phù hợp yêu bạn ở bản gốc.',
    work: 'Trong công việc: hợp vai trò cần truyền lửa — dẫn nhóm, thuyết trình, xây văn hóa. Nhớ lịch nạp năng lượng của chính mình trước khi phát cho người khác.',
    reflect: [
      'Ở đâu bạn đang sống "bản rút gọn" của chính mình — và vì ai?',
      'Điều gì nạp lại năng lượng cho bạn thật sự — lần cuối bạn làm nó là bao giờ?',
    ],
  },
  {
    slug: 'king-of-wands',
    name: 'King of Wands',
    name_vi: 'Vua Gậy',
    arcana: 'minor',
    suit_vi: 'Gậy',
    number: 14,
    keyUp: ['lãnh đạo bằng tầm nhìn', 'dám quyết', 'truyền hướng đi'],
    keyRev: ['độc đoán', 'kỳ vọng đốt người khác'],
    image:
      'Vị vua ngồi nghiêng người về phía trước như sắp đứng dậy, áo choàng thêu kỳ nhông lửa cắn đuôi thành vòng tròn. Quyền lực ở đây không tĩnh — nó luôn chực hành động.',
    up: 'Vua Gậy là người cầm lửa đã chín: vẫn nguyên đam mê của tuổi trẻ nhưng thêm khả năng nhìn xa và chịu trách nhiệm. Lá này gợi vai trò dẫn dắt — đặt hướng, truyền lửa, dám quyết những việc người khác né. Lãnh đạo kiểu Vua Gậy không quản từng li; ông vẽ chân trời rõ đến mức người khác tự muốn đi về phía đó.',
    rev: 'Ngược chiều: tầm nhìn thành áp đặt — "hướng của tôi là hướng duy nhất", kỳ vọng cao đến mức đốt cháy người làm cùng, nghe góp ý như nghe xúc phạm. Lửa lớn cần lò tốt; không có lò, nó chỉ là đám cháy.',
    love: 'Trong tình cảm: bạn (hoặc người ấy) là kiểu dẫn dắt, quyết đoán, che chở. Đẹp khi đối phương được hỏi ý; ngột khi mọi quyết định đã được quyết hộ.',
    work: 'Trong công việc: thời điểm nhận vai lớn hơn — dẫn dự án, đại diện tiếng nói chung. Đặt hướng xong, hãy lùi một bước cho người khác chỗ trổ tài.',
    reflect: [
      'Nếu phải phát biểu "chân trời" của nhóm/gia đình mình trong một câu, bạn nói gì?',
      'Kỳ vọng của bạn đang nâng người quanh mình lên, hay đang đè họ xuống?',
    ],
  },

  // ============ CỐC (Cups) — nước: cảm xúc, quan hệ, trực giác ============
  {
    slug: 'ace-of-cups',
    name: 'Ace of Cups',
    name_vi: 'Át Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 1,
    keyUp: ['mở lòng', 'cảm xúc mới', 'lòng trắc ẩn'],
    keyRev: ['đè nén cảm xúc', 'cho mà quên nhận'],
    image:
      'Bàn tay từ mây nâng chiếc chén trào năm dòng nước, chim bồ câu ngậm bánh thánh sà xuống. Trái tim ở trạng thái đầy — và đang tràn ra ngoài.',
    up: 'Át Cốc là khởi đầu của dòng cảm xúc: một tình cảm mới chớm, một tình bạn ấm lên, lòng trắc ẩn bỗng mở với người lạ, hay đơn giản là cảm giác "tim mình mềm lại" sau một thời gian khô. Lá này khuyên đón nhận thay vì phân tích: cảm xúc đến trước, tên gọi tính sau. Chén đầy thì tự tràn — yêu thương thật không cần gồng để phát.',
    rev: 'Ngược chiều: dòng nước bị chặn — có điều muốn bày tỏ mà nuốt vào, hoặc cho đi nhiều đến mức quên mất chén của mình cũng cần được rót. Cảm xúc bị đè lâu không biến mất; nó chỉ đổi cửa ra, thường là cửa xấu hơn.',
    love: 'Trong tình cảm: thời điểm đẹp để bày tỏ, làm lành, hoặc mở lòng lại sau tổn thương. Một lời thật lòng lúc này nặng ký hơn mọi chiến thuật.',
    work: 'Trong công việc: để lòng tốt có chỗ — giúp một đồng nghiệp, nói một lời tử tế. Môi trường làm việc đổi chất từ những việc nhỏ thế này.',
    reflect: [
      'Điều gì bạn đang muốn bày tỏ mà cứ nuốt lại — và sợ gì nếu nói ra?',
      'Chén của bạn dạo này được rót bằng gì — và ai rót?',
    ],
  },
  {
    slug: 'two-of-cups',
    name: 'Two of Cups',
    name_vi: 'Hai Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 2,
    keyUp: ['kết nối hai chiều', 'tâm đầu ý hợp', 'đồng minh'],
    keyRev: ['lệch nhịp', 'rạn nhỏ chưa nói'],
    image:
      'Hai người nâng chén trao nhau dưới biểu tượng trượng thần Hermes và đầu sư tử có cánh — một nghi thức của sự bình đẳng và tin cậy.',
    up: 'Hai Cốc là kết nối hai chiều ở dạng đẹp nhất: hai người nhìn nhau ngang tầm mắt — một mối tình cân xứng, một tình bạn tri kỷ, một cộng sự hiểu ý. Lá này nhấn vào chữ "hai chiều": cho và nhận, nói và nghe, nâng và được nâng. Những liên minh như vậy không tự nhiên có; chúng được xây từ nhiều lần trao chén nhỏ.',
    rev: 'Ngược chiều: nhịp đôi bên đang lệch — một người nghiêng nhiều hơn, một vết rạn nhỏ chưa ai gọi tên. Rạn nhỏ xử lý sớm là chuyện năm phút; để lâu thành chuyện năm tháng.',
    love: 'Trong tình cảm: giai đoạn tâm đầu ý hợp, hoặc cơ hội hàn gắn thật sự nếu cả hai cùng bước một bước. Hãy là người chìa chén trước.',
    work: 'Trong công việc: hợp tác một-một rất thuận — tìm một đồng minh, một người cố vấn, một cộng sự bù kỹ năng. Quan hệ chất lượng hơn quan hệ số lượng.',
    reflect: [
      'Mối quan hệ nào của bạn đang thật sự hai chiều — và bạn có nói cho họ biết bạn quý điều đó?',
      'Vết lệch nhỏ nào bạn đang thấy mà chưa gọi tên?',
    ],
  },
  {
    slug: 'three-of-cups',
    name: 'Three of Cups',
    name_vi: 'Ba Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 3,
    keyUp: ['tình bạn', 'ăn mừng cùng nhau', 'cộng đồng nâng đỡ'],
    keyRev: ['ngợp tiệc tùng', 'xã giao rỗng', 'cảm giác bị ra rìa'],
    image:
      'Ba người phụ nữ nâng chén thành vòng tròn giữa vườn trái chín — niềm vui ở dạng tập thể, không ai là trung tâm, ai cũng là một phần.',
    up: 'Ba Cốc là niềm vui được chia: bạn bè tụ lại, hội nhóm ăn mừng, những người "cùng phe đời" có mặt đúng lúc. Lá này nhắc một sự thật giản dị: niềm vui nhân lên khi chia, nỗi buồn nhẹ đi khi kể. Nếu lâu rồi chưa gặp đám bạn thân — đó không phải chuyện nhỏ, đó là một khoản đầu tư đang bị bỏ quên.',
    rev: 'Ngược chiều: lịch xã giao dày mà rỗng — đông người, ít thân; hoặc cảm giác đứng ngoài vòng tròn, nhìn cuộc vui qua màn hình người khác. Chất của vài tình bạn sâu đáng giá hơn lượng của trăm cái gật đầu.',
    love: 'Trong tình cảm: đưa nhau vào vòng bạn bè của mình là một cột mốc thật. Mặt trầm: để ý khi "cuộc vui chung" thành nơi trốn những cuộc trò chuyện riêng.',
    work: 'Trong công việc: thành quả của nhóm — ăn mừng kiểu nhóm. Văn hóa đồng đội xây từ những dịp vui có chủ đích.',
    reflect: [
      'Ba người nào bạn muốn có mặt trong vòng tròn của mình mười năm nữa — họ có biết không?',
      'Lịch gặp gỡ của bạn dạo này: nhiều cuộc đông người hay đủ cuộc thân tình?',
    ],
  },
  {
    slug: 'four-of-cups',
    name: 'Four of Cups',
    name_vi: 'Bốn Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 4,
    keyUp: ['chán chường', 'thờ ơ', 'không thấy cơ hội trước mặt'],
    keyRev: ['tỉnh ra', 'nhận lời mời', 'biết ơn trở lại'],
    image:
      'Chàng trai khoanh tay ngồi dưới gốc cây, nhìn ba chiếc chén trước mặt đầy chán nản — không thấy chiếc chén thứ tư đang được mây chìa ra ngay bên cạnh.',
    up: 'Bốn Cốc là cơn chán giữa no đủ: mọi thứ ổn mà không thấy vui, lời mời đến mà không buồn nhận, cơ hội trước mặt mà mắt nhìn xuyên qua. Lá này không mắng bạn vô ơn — nó chỉ ra rằng sự bão hòa cảm xúc là có thật, và đôi khi cái cần không phải thứ mới, mà là con mắt mới nhìn thứ đang có.',
    rev: 'Ngược chiều là cú tỉnh: nhận ra chén thứ tư, nói "có" với một lời mời suýt bỏ qua, thấy lại vị của những thứ quen. Giai đoạn chán thường là buồng chờ của một giai đoạn khác — miễn là đừng xây nhà luôn trong buồng chờ.',
    love: 'Trong tình cảm: sự nguội không phải lúc nào cũng do hết yêu — nhiều khi do hết để ý. Thử nhìn người bên cạnh như lần đầu gặp: họ có gì mà ngày xưa bạn đã chọn?',
    work: 'Trong công việc: chán việc chưa chắc cần đổi việc — thử đổi cách làm, nhận một mảng mới, dạy lại người mới. Nếu đã thử mà vẫn trơ, đó mới là dữ kiện.',
    reflect: [
      '"Chén thứ tư" nào có thể đang được chìa ra mà bạn chưa buồn quay sang nhìn?',
      'Cơn chán này muốn nói gì: cần nghỉ, cần mới, hay cần nhìn lại cách bạn đang sống ngày thường?',
    ],
  },
  {
    slug: 'five-of-cups',
    name: 'Five of Cups',
    name_vi: 'Năm Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 5,
    keyUp: ['tiếc nuối', 'mất mát', 'nhìn mãi phần đổ'],
    keyRev: ['quay lại nhìn phần còn', 'chấp nhận', 'bước tiếp'],
    image:
      'Người khoác áo choàng đen đứng cúi đầu trước ba chiếc chén đổ — sau lưng vẫn còn hai chén đứng nguyên, và một cây cầu dẫn về phía ngôi nhà bên kia sông.',
    up: 'Năm Cốc là nỗi buồn của mất mát: một chuyện không thành, một người rời đi, một cơ hội đổ. Lá này không bảo "vui lên" — nó cho phép bạn đứng đó buồn cho trọn, vì phần đổ là thật và xứng đáng được tiếc. Nhưng nó cũng đặt sẵn chi tiết: hai chén sau lưng còn nguyên, và có một cây cầu. Khi nào sẵn sàng — chỉ cần quay người.',
    rev: 'Ngược chiều: cú quay người ấy đang diễn ra — bạn bắt đầu thấy thứ còn lại, kể về chuyện cũ mà giọng đã nhẹ. Tha thứ (cho người, và cho mình) không phải là nói chuyện cũ đúng; nó là thôi để chuyện cũ đặt lịch cho ngày mới.',
    love: 'Trong tình cảm: sau đổ vỡ, đừng vội kết luận về cả phần đời còn lại. Người cũ lấy đi ba chén — không lấy được hai chén và cây cầu.',
    work: 'Trong công việc: dự án thất bại — khóc xong thì làm "lễ rút kinh nghiệm" cho tử tế: cái gì đổ vì mình, cái gì đổ vì trời, lần sau khác chỗ nào.',
    reflect: [
      'Bạn đã cho mình buồn đủ chưa — hay đang dùng bận rộn để khỏi buồn?',
      '"Hai chiếc chén còn đứng" của bạn lúc này là gì?',
    ],
    ease:
      'Lá này hay bị đọc thành "điềm mất mát sắp tới" — không phải. Nó mô tả một trạng thái tiếc nuối đang có, và nhắc rằng còn thứ chưa đổ. Không ai cần cúng gì để "giải" một nỗi buồn; nỗi buồn cần được sống cho trọn rồi đi qua.',
  },
  {
    slug: 'six-of-cups',
    name: 'Six of Cups',
    name_vi: 'Sáu Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 6,
    keyUp: ['ký ức ấm', 'hoài niệm', 'người cũ – chốn cũ', 'lòng tốt vô tư'],
    keyRev: ['kẹt trong quá khứ', 'lý tưởng hóa ngày xưa'],
    image:
      'Trong sân làng cũ, đứa trẻ lớn trao chén đầy hoa trắng cho đứa trẻ nhỏ hơn. Sáu chén đầy hoa — quà của ký ức, cho đi không tính toán.',
    up: 'Sáu Cốc là mùi của tuổi thơ: người bạn cũ nhắn tin, về thăm chốn cũ, lật lại album, hay một cử chỉ tốt vô tư làm bạn nhớ rằng mình từng hồn nhiên thế nào. Lá này gợi giá trị của gốc rễ: thỉnh thoảng múc nước từ giếng cũ — gọi cho người xưa, cảm ơn người từng giúp — không phải để quay lại sống ở đó, mà để nhớ mình lớn lên từ đâu.',
    rev: 'Ngược chiều: hoài niệm thành nơi trốn — "ngày xưa" được tô đẹp tới mức hiện tại không cách gì cạnh tranh nổi. Ký ức là chỗ để thăm, không phải chỗ để ở.',
    love: 'Trong tình cảm: người cũ xuất hiện lại, hoặc hai người ôn kỷ niệm và thấy ấm. Hỏi thật: thứ đang nhớ là con người đó hôm nay — hay phiên bản của họ trong ký ức?',
    work: 'Trong công việc: kỹ năng hay mối quan hệ từ thời xưa có thể đang dùng lại được. Gửi một lời hỏi thăm tử tế đến người từng dìu mình — không cần lý do.',
    reflect: [
      'Ký ức nào nuôi bạn — và ký ức nào đang giữ chân bạn?',
      'Ai trong quá khứ xứng đáng một lời cảm ơn mà bạn chưa từng gửi?',
    ],
  },
  {
    slug: 'seven-of-cups',
    name: 'Seven of Cups',
    name_vi: 'Bảy Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 7,
    keyUp: ['nhiều lựa chọn', 'mơ mộng', 'ảo ảnh hấp dẫn'],
    keyRev: ['tỉnh mộng', 'chọn một và làm'],
    image:
      'Bóng người đứng trước bảy chiếc chén lơ lửng trên mây, mỗi chén một báu vật: lâu đài, vòng nguyệt quế, rắn, châu báu… — thứ nào cũng lấp lánh, và tất cả đều đang ở trên mây.',
    up: 'Bảy Cốc là cơn say lựa chọn: nhiều hướng đi, nhiều viễn cảnh, nhiều "giá như" — và chính sự nhiều ấy gây tê liệt. Lá này không chê giấc mơ; nó chỉ nhắc rằng mơ là nguyên liệu, không phải món ăn. Bảy giấc mơ trên mây không bằng một giấc mơ được kéo xuống đất kèm bước đi đầu tiên.',
    rev: 'Ngược chiều là sự tỉnh: bạn bắt đầu phân biệt được lấp lánh và giá trị, gạch bớt lựa chọn, chọn một thứ để cam kết. Cảm giác "đóng bớt cửa" hơi tiếc — nhưng mọi cánh cửa đều chỉ mở cho người đã bước hẳn vào một hành lang.',
    love: 'Trong tình cảm: phân vân giữa nhiều đối tượng, hoặc yêu một hình mẫu tưởng tượng hơn là con người thật trước mặt. Người thật có khuyết điểm; hình mẫu thì không bao giờ ôm được.',
    work: 'Trong công việc: nhiều ý tưởng, nhiều "cơ hội lớn" — đặt cho mỗi thứ một phép thử rẻ trong hai tuần, dữ kiện sẽ chọn thay cảm giác.',
    reflect: [
      'Trong các viễn cảnh đang ôm, cái nào bạn sẵn lòng trả giá để theo — không chỉ thích khi nghĩ tới?',
      'Bước đầu tiên rẻ nhất để kéo giấc mơ số một xuống đất là gì?',
    ],
  },
  {
    slug: 'eight-of-cups',
    name: 'Eight of Cups',
    name_vi: 'Tám Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 8,
    keyUp: ['rời bỏ thứ đủ-mà-thiếu', 'đi tìm ý nghĩa', 'can đảm buông'],
    keyRev: ['sợ rời đi', 'đi mà chưa rõ vì sao'],
    image:
      'Dưới ánh trăng, một người chống gậy quay lưng bỏ lại tám chiếc chén xếp ngay ngắn, men theo lạch nước đi về phía núi. Tám chén không đổ — chỉ là không còn đủ.',
    up: 'Tám Cốc là cuộc rời đi khó giải thích nhất: thứ bỏ lại không tệ — công việc ổn, mối quan hệ êm, cuộc sống đáng mơ với người ngoài — nhưng bên trong bạn biết nó thiếu một chén. Lá này công nhận thứ can đảm ít được vỗ tay: dám rời cái đủ để đi tìm cái đúng. Không phải mọi cuộc ra đi đều là chạy trốn; có những cuộc ra đi là trưởng thành.',
    rev: 'Ngược chiều: hoặc bạn biết phải đi mà chân chưa nhấc nổi (tiếc công xếp tám chén), hoặc đã đi mà thật ra chưa trả lời được "đi tìm gì" — và nguy cơ là tới nơi mới lại xếp đúng tám chén cũ.',
    love: 'Trong tình cảm: cảm giác "đủ mà thiếu" trong một mối quan hệ đáng được nói ra trước khi đáng được rời đi. Có khi chén thứ chín nằm ngay trong cuộc trò chuyện chưa từng có.',
    work: 'Trong công việc: rời vị trí tốt để theo điều có ý nghĩa hơn — hợp lệ, miễn đã thử sửa tại chỗ và đã định nghĩa được "ý nghĩa hơn" là gì.',
    reflect: [
      'Thứ gì trong đời bạn đang "đủ mà thiếu" — thiếu chính xác cái gì?',
      'Nếu rời đi, bạn đi TÌM gì — nói được thành một câu không?',
    ],
  },
  {
    slug: 'nine-of-cups',
    name: 'Nine of Cups',
    name_vi: 'Chín Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 9,
    keyUp: ['mãn nguyện', 'điều ước thành', 'biết đủ'],
    keyRev: ['thỏa mãn bề mặt', 'khoe để lấp', 'rỗng bên trong'],
    image:
      'Người đàn ông ngồi khoanh tay mỉm cười, sau lưng là kệ cong xếp chín chiếc chén như huy chương. Truyền thống gọi đây là "lá điều ước" — cảm giác được toại nguyện.',
    up: 'Chín Cốc là khoảnh khắc "được": điều mong mỏi thành hình, và bạn được phép ngồi xuống tận hưởng nó không áy náy. Lá này dạy một kỹ năng bị xem nhẹ: biết nhận mình đang ổn. Nhiều người leo cả đời mà không một lần đứng lại ở đỉnh nào để thở — đỉnh nào cũng chỉ là trạm tiếp nhiên liệu cho đỉnh sau. Hôm nay, cho phép mình toại nguyện.',
    rev: 'Ngược chiều: nụ cười cho khán giả — thành tựu để đăng, để kể, nhưng đêm về thấy rỗng. Hỏi thẳng: điều ước đã thành kia là ước của bạn, hay ước bạn mượn từ kỳ vọng người khác?',
    love: 'Trong tình cảm: hài lòng thật với những gì đang có — và nói cho người kia biết. Mặt trầm: vẻ "ổn cả" trưng ra ngoài đôi khi là lý do không ai hỏi bạn câu hỏi sâu.',
    work: 'Trong công việc: mục tiêu đạt — chốt sổ, thưởng cho mình, rồi mới đặt mục tiêu mới. Đặt mục tiêu mới NGAY khi vừa đạt là cách chắc nhất để không bao giờ thấy đủ.',
    reflect: [
      'Điều gì bạn từng ước có — và hiện đang có mà quên mất mình từng ước?',
      'Nếu không ai biết đến thành tựu này, nó còn làm bạn vui không?',
    ],
  },
  {
    slug: 'ten-of-cups',
    name: 'Ten of Cups',
    name_vi: 'Mười Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 10,
    keyUp: ['viên mãn quan hệ', 'gia đình thuận', 'hạnh phúc bền'],
    keyRev: ['hình ảnh hoàn hảo che vết rạn', 'kỳ vọng cổ tích'],
    image:
      'Đôi vợ chồng dang tay dưới cầu vồng mười chén, hai đứa trẻ nhảy múa bên cạnh, xa xa là mái nhà bên dòng sông. Bức tranh "về đích" của bộ Cốc.',
    up: 'Mười Cốc là viên mãn của tình thân: gia đình thuận, các mối quan hệ cốt lõi lành mạnh, cảm giác "mình có nơi để thuộc về". Lá này nhắc rằng hạnh phúc kiểu này trông như quà nhưng thật ra là công trình: nó được xây bằng nhiều năm lắng nghe, nhường nhịn, sửa chữa. Nếu bạn đang có nó — đó không phải may mắn suông, hãy tiếp tục bảo trì.',
    rev: 'Ngược chiều: bức tranh đẹp dùng để che — nhà ngoài ấm trong lạnh, ảnh gia đình rạng rỡ đăng từ một bàn ăn im lặng. Hoặc kỳ vọng "cổ tích" cao đến mức hạnh phúc thật (vốn có cãi vã, có mệt) bị chấm rớt. Hạnh phúc thật không hoàn hảo; nó chỉ cần thật.',
    love: 'Trong tình cảm: tầm nhìn về mái ấm chung — đáng nói với nhau một cách cụ thể: "gia đình hạnh phúc" với mỗi người trông khác nhau thế nào.',
    work: 'Trong công việc: cân bằng được việc và nhà lúc này quý hơn thăng tiến. Một quyết định nghề nghiệp tốt là quyết định mà 5 người ở "mười chén" của bạn không phải trả giá.',
    reflect: [
      '"Mười chén" của bạn gồm những ai — lịch của bạn tuần này có phản ánh điều đó?',
      'Ở nhà bạn, điều gì đang được giữ cho "trông ổn" thay vì được sửa cho ổn thật?',
    ],
  },
  {
    slug: 'page-of-cups',
    name: 'Page of Cups',
    name_vi: 'Thị Đồng Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 11,
    keyUp: ['tín hiệu cảm xúc mới', 'trực giác chớm nở', 'sáng tạo hồn nhiên'],
    keyRev: ['dễ tổn thương', 'mơ mộng quá đà'],
    image:
      'Thị đồng áo hoa đứng bên bờ biển, nâng chén — và một chú cá nhỏ ngó ra khỏi chén nhìn lại. Điều bất ngờ dễ thương từ thế giới cảm xúc.',
    up: 'Thị Đồng Cốc là tin nhắn từ trái tim: một rung động không hẹn, một ý tưởng sáng tạo ngộ nghĩnh, một giấc mơ kỳ lạ đáng ghi lại, một lời mời mang màu cảm xúc. Lá này gợi thái độ hồn nhiên với đời sống bên trong: đừng vội phán xét cảm xúc "vớ vẩn" — con cá trong chén chỉ ngoi lên với người chịu nhìn vào chén.',
    rev: 'Ngược chiều: nhạy cảm thành dễ vỡ — một lời nói nhẹ cũng thành sóng lớn; hoặc mơ mộng thành thoát ly, sống trong kịch bản tưởng tượng nhiều hơn đời thật. Cảm xúc là tín hiệu, không phải mệnh lệnh.',
    love: 'Trong tình cảm: một tín hiệu mới — tin nhắn làm quen, cử chỉ ngọt bất ngờ. Đón bằng sự tò mò nhẹ nhõm, đừng vội viết cả cuốn tiểu thuyết từ một cái nhìn.',
    work: 'Trong công việc: ý tưởng "ngây ngô" trong cuộc họp có khi là ý hay nhất — nói ra. Người mới hỏi câu lạ thường thấy thứ người cũ đã quen mắt.',
    reflect: [
      'Cảm xúc lạ nào gần đây bạn gạt đi vì "vớ vẩn" — nếu nó là tín hiệu thì nó báo gì?',
      'Lần cuối bạn làm một việc sáng tạo chỉ để vui là khi nào?',
    ],
  },
  {
    slug: 'knight-of-cups',
    name: 'Knight of Cups',
    name_vi: 'Hiệp Sĩ Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 12,
    keyUp: ['lãng mạn', 'lời mời từ trái tim', 'theo đuổi lý tưởng'],
    keyRev: ['hứa ngọt làm mỏng', 'thất thường', 'lãng mạn hóa mọi thứ'],
    image:
      'Hiệp sĩ trên ngựa trắng đi nước kiệu chậm rãi, tay nâng chén như đang dâng tặng, áo giáp gắn cánh ở mũ và gót. Người mang lời tỏ bày đến — một cách đầy nghi thức.',
    up: 'Hiệp Sĩ Cốc là người theo đuổi bằng trái tim: lời tỏ tình, lời mời hợp tác đầy cảm hứng, một đề nghị làm điều đẹp đẽ. Lá này cũng là lời nhắc về phong cách: có những việc nên làm cho đẹp — chọn lời, chọn lúc, chọn cách. Sự lãng mạn (với người, với nghề, với đời) không phải xa xỉ; nó là cách nói "điều này xứng đáng được làm tử tế".',
    rev: 'Ngược chiều: chén đưa ra mà chân không đứng yên — lời ngọt nhiều hơn việc làm, cảm xúc dâng nhanh rút nhanh, yêu cái cảm giác đang yêu hơn là yêu người trước mặt. Kiểm chứng đơn giản: nhìn độ lặp lại, đừng nhìn độ long lanh.',
    love: 'Trong tình cảm: giai đoạn được (hoặc nên) tỏ bày. Nếu bạn là người nhận: tận hưởng, và quan sát hành động sau lời nói. Nếu bạn là người trao: hứa ít thôi, làm đủ.',
    work: 'Trong công việc: lời mời dự án "đúng mơ ước" — kiểm tra phần ruột (tiền, người, cam kết) trước khi ký vì phần vỏ.',
    reflect: [
      'Bạn đang theo đuổi điều gì bằng cả trái tim — và đã làm nó tử tế tới mức nào?',
      'Lời hứa nào của bạn (hoặc dành cho bạn) đang chờ được chứng minh bằng việc làm?',
    ],
  },
  {
    slug: 'queen-of-cups',
    name: 'Queen of Cups',
    name_vi: 'Hoàng Hậu Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 13,
    keyUp: ['thấu cảm sâu', 'lắng nghe', 'an toàn cảm xúc'],
    keyRev: ['thấm nỗi người đến kiệt', 'mất ranh giới'],
    image:
      'Hoàng hậu ngồi trên ngai sát mép nước, nâng chiếc chén có nắp — chén duy nhất đóng kín trong cả bộ bài — chân không chạm nước mà chạm bờ.',
    up: 'Hoàng Hậu Cốc là người mà ai cũng tìm đến để được nghe: thấu cảm sâu, giữ chuyện kín, làm người khác an toàn để yếu lòng. Chi tiết đắt của lá nằm ở chiếc chén có nắp và bàn chân trên bờ: hiểu nước mà không tan vào nước — cảm được nỗi người mà vẫn giữ được hình dạng của mình. Đó là thấu cảm bền, khác với thấm nỗi người rồi chìm cùng.',
    rev: 'Ngược chiều: ranh giới nhòe — nỗi buồn của người thành nỗi buồn của mình, nghe cả thế giới mà không ai nghe mình, kiệt vì làm "trạm cứu hộ cảm xúc" không giờ đóng cửa. Người giúp giỏi nhất là người còn nguyên.',
    love: 'Trong tình cảm: sự dịu dàng và lắng nghe của bạn là tài sản — miễn nó chảy hai chiều. Một mối quan hệ mà chỉ một người làm chén chứa thì chén ấy sớm tràn.',
    work: 'Trong công việc: hợp vai chăm người — nhân sự, chăm khách, dẫn dắt tinh thần nhóm. Đặt giờ "đóng quầy" cảm xúc rõ ràng để còn sạc lại.',
    reflect: [
      'Ai là người nghe của bạn — và bạn có cho phép mình được nghe không?',
      'Ranh giới nào bạn cần dựng lại để thương người mà không hao mình?',
    ],
  },
  {
    slug: 'king-of-cups',
    name: 'King of Cups',
    name_vi: 'Vua Cốc',
    arcana: 'minor',
    suit_vi: 'Cốc',
    number: 14,
    keyUp: ['điềm tĩnh giữa sóng', 'trưởng thành cảm xúc', 'cân bằng tình – lý'],
    keyRev: ['nén thành xa cách', 'điều khiển êm ái'],
    image:
      'Vị vua ngồi trên ngai đá nổi giữa biển động — cá nhảy, thuyền nghiêng phía xa — mà gương mặt và tay chén vẫn yên. Không phải biển lặng; là người lặng.',
    up: 'Vua Cốc là độ chín của cảm xúc: vẫn cảm đủ — giận, buồn, thất vọng — nhưng không để con sóng nào cầm lái. Trong nhà, đây là người giữ nhiệt độ; trong nhóm, là người mà khủng hoảng tìm đến để được nói chuyện tử tế. Lá này gợi phép thử của trưởng thành: bị chạm đúng chỗ đau mà vẫn chọn được lời tử tế — không phải vì sợ, mà vì đã hiểu mình.',
    rev: 'Ngược chiều: sự điềm tĩnh là vỏ — bên dưới là cảm xúc bị nén lâu thành lạnh, thành xa cách, có khi thành kiểm soát êm ái (dùng sự "bình tĩnh hơn" để làm người khác thấy mình vô lý). Bình tĩnh thật mở cửa; bình tĩnh giả đóng băng.',
    love: 'Trong tình cảm: vững chãi của bạn là chỗ tựa — nhưng người thương cần cả phần thật đang xao động bên dưới. Cho người ấy thấy sóng của mình cũng là một dạng tin tưởng.',
    work: 'Trong công việc: hợp vai xử lý khủng hoảng, hòa giải, dẫn dắt giai đoạn nhạy cảm. Đừng để "anh ấy lúc nào chẳng ổn" thành lý do không ai hỏi bạn có ổn không.',
    reflect: [
      'Cơn sóng nào bạn đang giữ dưới mặt nước — giữ vì ai, và giá là gì?',
      'Lần gần nhất bạn nói "tôi đang buồn/giận" một cách bình thản là khi nào?',
    ],
  },

// ============ KIẾM (Swords) — khí: tư duy, lời nói, sự thật ============
  {
    slug: 'ace-of-swords',
    name: 'Ace of Swords',
    name_vi: 'Át Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 1,
    keyUp: ['sự thật rõ ra', 'quyết định sắc bén', 'ý tưởng đột phá'],
    keyRev: ['rối trí', 'sự thật bị bẻ cong'],
    image:
      'Bàn tay từ mây nắm thanh kiếm dựng thẳng, mũi kiếm xuyên qua vương miện kết vòng lá. Trí tuệ ở khoảnh khắc sắc nhất: cắt xuyên mọi lớp nhiễu.',
    up: 'Át Kiếm là khoảnh khắc đầu óc bừng rõ: gọi đúng tên vấn đề sau bao ngày lờ mờ, nhìn xuyên một chuyện rối, hoặc một ý tưởng sắc đến mức mọi thứ quanh nó tự xếp hàng. Lá này khuyên dùng độ sắc ấy ngay — viết xuống, nói ra, quyết định — vì sự trong trẻo của tâm trí cũng có hạn dùng như mọi món tươi.',
    rev: 'Ngược chiều: lưỡi kiếm cùn hoặc bị bẻ — nghĩ mãi không ra đầu mối, thông tin nhiễu, hoặc ai đó (kể cả chính mình) đang uốn sự thật cho vừa ý muốn. Lúc này đừng quyết lớn; hãy đi tìm thêm một dữ kiện thật thay vì thêm một ý kiến.',
    love: 'Trong tình cảm: một sự thật cần được nói rõ — càng nói sớm bằng lời tử tế, càng đỡ phải nói muộn bằng lời sắc.',
    work: 'Trong công việc: hợp lúc phân tích, đặt lại vấn đề, viết đề xuất. Câu hỏi đúng đáng giá hơn mười câu trả lời nhanh.',
    reflect: [
      'Vấn đề bạn đang gặp — gọi tên nó trong MỘT câu, được không?',
      'Sự thật nào bạn đã thấy rõ mà còn chần chừ chưa nói?',
    ],
  },
  {
    slug: 'two-of-swords',
    name: 'Two of Swords',
    name_vi: 'Hai Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 2,
    keyUp: ['bế tắc lựa chọn', 'né quyết định', 'đình chiến tạm'],
    keyRev: ['buộc phải mở mắt', 'dữ kiện mới phá thế cân'],
    image:
      'Người phụ nữ bịt mắt ngồi quay lưng ra biển, hai tay bắt chéo ôm hai thanh kiếm. Thế cân bằng — nhưng là thứ cân bằng phải gồng mới giữ được.',
    up: 'Hai Kiếm là thế "chưa chọn được": hai phương án nặng ngang nhau, hoặc một quyết định bạn cố tình bịt mắt để khỏi phải đưa ra. Lá này chỉ ra một sự thật khó chịu: không quyết cũng là một quyết định — và thường là quyết định tốn kém nhất, vì hai tay bạn bận ôm kiếm nên không làm được gì khác. Cái thiếu thường không phải dữ kiện, mà là sự dám chịu cái giá của một bên.',
    rev: 'Ngược chiều: thế cân đang vỡ — một dữ kiện mới, một biến cố, hoặc cảm xúc dồn tới mức không bịt mắt nổi nữa. Khó chịu, nhưng là tin tốt: được buộc phải chọn đôi khi là ơn.',
    love: 'Trong tình cảm: đứng giữa hai người, hoặc giữa đi và ở. Hỏi thật: bạn đang cân nhắc, hay đang trì hoãn nỗi đau của việc chọn?',
    work: 'Trong công việc: hai hướng đều "được" — đặt deadline cho chính mình, liệt kê cái giá của TỪNG bên (kể cả bên "không làm gì"), rồi chọn.',
    reflect: [
      'Quyết định nào bạn đang bịt mắt với nó — và bịt mắt đang tốn của bạn thứ gì mỗi tuần?',
      'Nếu buộc phải chọn trong 24 giờ, bạn sẽ chọn gì? Cảm giác đầu tiên khi nghĩ thế nói lên điều gì?',
    ],
  },
  {
    slug: 'three-of-swords',
    name: 'Three of Swords',
    name_vi: 'Ba Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 3,
    keyUp: ['đau lòng', 'sự thật làm tổn thương', 'nỗi đau có tên'],
    keyRev: ['bắt đầu lành', 'tha thứ', 'rút kiếm ra'],
    image:
      'Trái tim đỏ giữa trời mưa xám, ba thanh kiếm xuyên qua. Một trong những hình ảnh thẳng thắn nhất bộ bài: đau là đau, không né.',
    up: 'Ba Kiếm là nỗi đau do sự thật gây ra: lời nói làm tổn thương, một sự phản bội, một tin không muốn nghe. Lá này không tô hồng — nó thừa nhận vết đâm là thật. Nhưng để ý: kiếm là biểu tượng của trí tuệ; nỗi đau kiểu này luôn kèm một sự thật vừa lộ ra, và sự thật đó — dù đau — thường giải phóng ta khỏi một ảo tưởng đắt đỏ hơn.',
    rev: 'Ngược chiều: giai đoạn rút kiếm — vết thương bắt đầu khép, kể lại chuyện cũ thấy bớt nghẹn, sẵn sàng tha (cho người, hoặc cho mình). Đừng vội ép lành; nhưng cũng đừng giữ kiếm trong tim làm kỷ niệm.',
    love: 'Trong tình cảm: tổn thương cần được gọi tên giữa hai người — vết đau nói ra là vết đau bắt đầu được xử lý. Im lặng nuôi sẹo xấu hơn nói chuyện vụng về.',
    work: 'Trong công việc: phản hồi phũ, dự án tâm huyết bị bác. Cho mình một ngày buồn, rồi tách bạch: phần nào là nỗi đau cái tôi, phần nào là bài học dùng được.',
    reflect: [
      'Nỗi đau này đang dạy bạn sự thật gì mà trước đó bạn không chịu nhìn?',
      'Bạn cần gì để bắt đầu rút kiếm ra — thời gian, lời xin lỗi, hay một quyết định của chính mình?',
    ],
    ease:
      'Lá này trông đáng sợ nhưng không phải "điềm" cho chuyện dữ sắp tới — nó mô tả một nỗi đau đang/đã có, và mở lối nghĩ về nó. Nỗi đau không cần lễ giải; nó cần được thừa nhận và được thời gian.',
  },
  {
    slug: 'four-of-swords',
    name: 'Four of Swords',
    name_vi: 'Bốn Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 4,
    keyUp: ['nghỉ để phục hồi', 'tạm rút lui', 'tĩnh để nghĩ'],
    keyRev: ['ép mình chạy tiếp', 'nghỉ thành trốn'],
    image:
      'Trong nhà nguyện tĩnh, một hiệp sĩ nằm yên như tượng, hai tay chắp; ba thanh kiếm treo trên tường, một thanh nằm dưới thân. Vũ khí treo lên — chưa vứt, chỉ treo.',
    up: 'Bốn Kiếm là lệnh nghỉ có chủ đích: sau (hoặc giữa) một trận chiến dài, tâm trí cần một quãng im — ngủ đủ, tắt thông báo, một ngày không quyết định gì. Lá này phân biệt rõ: nghỉ không phải bỏ cuộc; kiếm treo trên tường chứ không gãy. Người biết nghỉ đúng lúc quay lại trận với lưỡi kiếm sắc hơn kẻ gồng thêm ba tuần bằng dao cùn.',
    rev: 'Ngược chiều: hoặc bạn đang ép mình chạy khi đồng hồ đỏ đèn (cáu vô cớ, ngủ kém, đọc ba lần một đoạn — đó là chuông), hoặc kỳ nghỉ đã dài quá hạn thành nơi trốn việc quay lại. Nghỉ có ngày kết thúc; trốn thì không.',
    love: 'Trong tình cảm: đôi khi hai người cần một nhịp lặng — không phải chiến tranh lạnh, mà là cùng thống nhất "mình nghỉ tranh luận tới cuối tuần rồi nói tiếp bằng cái đầu mát".',
    work: 'Trong công việc: xếp một quãng trắng thật sự vào lịch. Não giải bài toán khó lúc đi dạo giỏi hơn lúc nhìn trừng màn hình.',
    reflect: [
      'Cơ thể bạn đang phát tín hiệu gì mà bạn cứ hẹn "xong đợt này rồi tính"?',
      'Kỳ nghỉ gần nhất của bạn có ngày bắt đầu — nó có ngày kết thúc chưa?',
    ],
  },
  {
    slug: 'five-of-swords',
    name: 'Five of Swords',
    name_vi: 'Năm Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 5,
    keyUp: ['thắng mà mất', 'xung đột tổn thương', 'cái giá của hơn thua'],
    keyRev: ['buông cuộc cãi', 'làm hòa', 'rút bài học'],
    image:
      'Kẻ thắng ôm năm thanh kiếm nhếch mép nhìn hai người thua lặng lẽ bỏ đi về phía biển động. Trận đã xong — và sân chiến trống rỗng hơn trước.',
    up: 'Năm Kiếm hỏi một câu khó: thắng cái này, bạn mất cái gì? Có những cuộc cãi thắng bằng lý mà thua bằng tình; có những ván "đúng" mà xong rồi chẳng ai muốn ngồi cùng bàn. Lá này không cấm bạn thắng — nó bắt bạn nhìn tổng sổ: hơn thua xong, trên sân còn lại ai? Đôi khi rời cuộc chiến không phải vì yếu, mà vì thấy cái giá.',
    rev: 'Ngược chiều: bạn bắt đầu buông — xin lỗi trước, bỏ qua một câu khích, rời một cuộc cãi không lối ra. Nhẹ hẳn. Bài học đắt nhất của Năm Kiếm ngược: có những "trận thắng" cũ đáng được xin lỗi lại.',
    love: 'Trong tình cảm: nếu cãi nhau mà mục tiêu là thắng, cả hai cùng thua. Thử đổi câu hỏi từ "ai đúng" sang "mình đang bảo vệ điều gì, và điều đó có cần kiểu bảo vệ này không".',
    work: 'Trong công việc: cẩn thận chiến thắng đốt cầu — hơn một keo trước mặt sếp mà mất một đồng minh mười năm. Sự nghiệp là trò chơi lặp, không phải ván một lần.',
    reflect: [
      'Cuộc hơn thua nào bạn đang theo mà phần thưởng thật ra chỉ là cảm giác thắng?',
      'Có cây cầu nào bạn đã đốt mà giờ đáng bắc lại — bắt đầu bằng gì?',
    ],
  },
  {
    slug: 'six-of-swords',
    name: 'Six of Swords',
    name_vi: 'Sáu Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 6,
    keyUp: ['chuyển tiếp', 'rời vùng dữ sang vùng lặng', 'đi về phía bình yên'],
    keyRev: ['hành lý cũ kéo lại', 'chưa dứt được'],
    image:
      'Người lái đò chở người phụ nữ trùm khăn và đứa trẻ qua sông; sáu thanh kiếm cắm ở mũi thuyền cùng sang sông. Nước phía sau gợn, nước phía trước lặng.',
    up: 'Sáu Kiếm là chuyến đò sang trang: rời một giai đoạn sóng gió — đổi chỗ ở, đổi việc, ra khỏi một mối quan hệ bào mòn — về phía nước lặng hơn. Lá này thật thà ở chi tiết sáu thanh kiếm vẫn trên thuyền: ta mang theo bài học (và cả vết xước) của chuyện cũ, không xóa được — nhưng chở chúng sang sông như hành lý, khác hẳn để chúng dìm thuyền.',
    rev: 'Ngược chiều: chuyến đi bị neo — lý trí biết phải sang sông mà tay chưa buông bến cũ; hoặc thân đã đi xa mà đầu vẫn mở "căn phòng cũ" mỗi đêm. Đi mà chưa dứt thì chưa phải là đi.',
    love: 'Trong tình cảm: giai đoạn sau giông — cùng nhau (hoặc một mình) chèo về phía êm. Đừng đòi hết buồn ngay; nước lặng dần theo từng nhịp chèo.',
    work: 'Trong công việc: chuyển việc/chuyển nhóm để thoát môi trường độc hại là chính đáng. Mang theo bài học, để lại sự cay đắng — công ty mới không nợ bạn lời xin lỗi của công ty cũ.',
    reflect: [
      'Bạn đang ở khúc nào của chuyến đò: chưa xuống thuyền, đang giữa sông, hay đã cập mà chưa chịu lên bờ?',
      'Trong "sáu thanh kiếm" mang theo, thanh nào là bài học, thanh nào chỉ là oán cũ vô dụng?',
    ],
  },
  {
    slug: 'seven-of-swords',
    name: 'Seven of Swords',
    name_vi: 'Bảy Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 7,
    keyUp: ['mưu lược', 'đi đường vòng', 'hành động một mình'],
    keyRev: ['lộ bài', 'tự lừa mình', 'trả giá cho đường tắt'],
    image:
      'Một người ôm năm thanh kiếm rón rén rời trại địch lúc ban ngày, ngoái nhìn sau lưng; hai thanh kiếm còn cắm lại. Khôn — và đang đi bằng đầu ngón chân.',
    up: 'Bảy Kiếm là nước đi khôn khéo: không đối đầu trực diện mà đi vòng — đàm phán riêng, giữ bài kín, rút êm khỏi cuộc không đáng. Có lúc đó là chiến lược hợp lệ (không phải trận nào cũng cần kèn trống). Nhưng lá này luôn kèm câu kiểm tra: nếu việc này bị nhìn thấy toàn cảnh, bạn còn thấy ổn không? Khéo léo và gian dối chỉ cách nhau đúng câu đó.',
    rev: 'Ngược chiều: nước đi vụng lộ ra — kế hoạch bị nhìn thấu, đường tắt bắt đầu tính lãi; hoặc người bị lừa khéo nhất hóa ra là chính mình ("chỉ lần này", "ai chẳng thế"). Trung thực muộn vẫn rẻ hơn bị phát hiện.',
    love: 'Trong tình cảm: có gì đó đang được giấu "cho yên" — bí mật nhỏ trả góp thành khoảng cách lớn. Úp mở lâu ngày chính là một dạng nói dối.',
    work: 'Trong công việc: giữ chiến lược kín là quyền; nhận công người khác, đi đêm sau lưng đội — là khoản vay lãi cao. Danh tiếng là tài sản gây dựng chậm, mất nhanh.',
    reflect: [
      'Nước đi nào bạn đang giấu — nếu mọi người thấy hết, bạn có còn đi nước đó?',
      'Đường tắt nào bạn đang đi mà sâu trong lòng biết là sẽ phải quay lại trả?',
    ],
  },
  {
    slug: 'eight-of-swords',
    name: 'Eight of Swords',
    name_vi: 'Tám Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 8,
    keyUp: ['tự trói bằng niềm tin', 'cảm giác hết đường', 'nhà tù trong đầu'],
    keyRev: ['cởi trói', 'nhìn ra lựa chọn', 'bước ra'],
    image:
      'Người phụ nữ bịt mắt, thân quấn vải, đứng giữa tám thanh kiếm cắm xuống đất. Nhìn kỹ: dây trói lỏng, chân không bị buộc, và giữa các thanh kiếm có lối đi.',
    up: 'Tám Kiếm là nhà tù xây bằng ý nghĩ: "tôi không thể nghỉ việc", "nói ra cũng vô ích", "giờ này còn làm lại sao kịp". Tình huống thật có ràng buộc thật — nhưng lá này chỉ vào phần trói LỎNG: bao nhiêu phần của bức tường là sự thật đã kiểm chứng, bao nhiêu phần là câu niệm lâu năm chưa từng thử lại? Người bịt mắt không thấy lối đi không có nghĩa là lối đi không có.',
    rev: 'Ngược chiều: dải bịt mắt đang tuột — bạn thử cái "không thể" và nó… được; hỏi câu "ai bảo thế?" và không tìm ra tác giả nào ngoài mình. Tự do đôi khi chỉ cách một cú thử nhỏ.',
    love: 'Trong tình cảm: cảm giác "mắc kẹt" trong quan hệ đáng được tách đôi — phần ràng buộc thật (con cái, cam kết) và phần tự trói ("không ai khác chịu nổi tôi"). Phần hai gỡ được.',
    work: 'Trong công việc: "không thể" nào của bạn đã hơn một năm chưa kiểm chứng lại? Thị trường đổi, kỹ năng bạn đổi — bức tường cũ có khi đã thành cửa.',
    reflect: [
      'Niềm tin nào đang trói bạn mà bạn chưa từng đem ra kiểm chứng?',
      'Nếu một người bạn kể đúng tình huống của bạn, bạn sẽ chỉ cho họ lối ra nào? Sao lối đó không áp dụng cho mình?',
    ],
  },
  {
    slug: 'nine-of-swords',
    name: 'Nine of Swords',
    name_vi: 'Chín Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 9,
    keyUp: ['lo âu đêm', 'vòng nghĩ xoáy', 'nỗi sợ phình to trong bóng tối'],
    keyRev: ['sáng dần', 'nói ra nỗi sợ', 'tách lo thật khỏi lo ảo'],
    image:
      'Người ngồi bật dậy giữa đêm, hai tay ôm mặt; chín thanh kiếm treo ngang tường tối. Trên chăn thêu hoa hồng và ký hiệu chiêm tinh — đời thật bên dưới vẫn nguyên, chỉ tâm trí đang gào.',
    up: 'Chín Kiếm là ba giờ sáng của tâm trí: lo âu xoáy vòng, kịch bản xấu tự nhân bản, một nỗi xấu hổ cũ phát lại không ai yêu cầu. Lá này tách bạch giúp bạn: chín thanh kiếm treo TRÊN TƯỜNG, không đâm vào người — phần lớn khổ lúc này là khổ trong đầu, to hơn nhiều so với chuyện ngoài đời. Không phải chuyện không có thật; là kích thước bị đêm phóng đại.',
    rev: 'Ngược chiều: trời đang sáng — nói được nỗi sợ ra miệng với một người, viết nó xuống giấy và thấy nó… ngắn hơn tưởng. Lo âu sợ nhất ánh sáng và giấy bút: thứ mơ hồ thì khổng lồ, thứ được viết ra thì có kích thước.',
    love: 'Trong tình cảm: kịch bản ghen tuông/lo mất tự dựng lúc đêm — đem ra hỏi thẳng vào ban ngày. Người thương không đọc được suy nghĩ; nỗi lo không nói là nỗi lo tự nuôi.',
    work: 'Trong công việc: lo về deadline/sai sót — đổi "lo" thành "danh sách": việc gì làm được ngay mai, việc gì ngoài tầm. Não thôi gào khi tay có việc.',
    reflect: [
      'Nỗi lo to nhất đêm qua: viết nó thành MỘT câu trên giấy — nó còn to thế không?',
      'Trong các kịch bản xấu đang chạy trong đầu, cái nào từng thật sự xảy ra?',
    ],
    ease:
      'Nếu lo âu mất ngủ kéo dài nhiều tuần và lấn vào ban ngày, đó là chuyện sức khỏe đáng được hỗ trợ chuyên môn (bác sĩ, chuyên gia tâm lý) — một lá bài không chẩn đoán được điều đó, và không nghi thức nào thay được một cuộc hẹn đúng người.',
  },
  {
    slug: 'ten-of-swords',
    name: 'Ten of Swords',
    name_vi: 'Mười Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 10,
    keyUp: ['chạm đáy', 'kết thúc hẳn', 'không còn gì để mất — và rạng đông'],
    keyRev: ['hồi phục', 'đứng dậy', 'thôi kịch tính hóa'],
    image:
      'Người nằm sấp bên bờ nước, mười thanh kiếm cắm dọc lưng — và phía chân trời, mặt trời đang mọc, vàng rực dưới mây đen. Tối nhất của bộ Kiếm, kèm bình minh trong cùng một khung hình.',
    up: 'Mười Kiếm là cú kết không thể chối: dự án sập hẳn, mối quan hệ chấm dứt hẳn, một giai đoạn bị đóng dấu "hết". Đau — nhưng lá này có một món quà lạnh lùng: sự RÕ RÀNG. Hết thật rồi, nghĩa là thôi hy vọng vớt vát, thôi chết dần — và mọi năng lượng được trả về cho ngày mai. Mặt trời trong tranh không phải trang trí: đáy là nơi duy nhất mà mọi hướng còn lại đều là đi lên.',
    rev: 'Ngược chiều: bạn đang gượng dậy — vết thương khép, bài học rút, và bắt đầu kể lại chuyện cũ như chuyện đã qua. Cũng có khi lá nhắc nhẹ: tình huống chưa đến mức "mười kiếm" như cảm giác — bớt một nửa kịch tính, còn lại dễ xử hơn nhiều.',
    love: 'Trong tình cảm: nếu đã thật sự kết thúc, điều tử tế nhất với chính mình là thừa nhận nó kết thúc. Đóng cửa hẳn thì cửa khác mới có chỗ mở.',
    work: 'Trong công việc: thất bại trọn vẹn — làm "khám nghiệm" tử tế: nguyên nhân, bài học, thứ giữ lại. Nhiều sự nghiệp đẹp xây trên nền một lần sập hẳn.',
    reflect: [
      'Điều gì trong đời bạn cần được thừa nhận là "đã hết" để bạn được tự do?',
      'Nhìn lại lần chạm đáy cũ: nó đã mở ra điều gì mà lúc đó bạn không thấy?',
    ],
    ease:
      'Hình ảnh lá này dữ dội nhưng nghĩa của nó là "một kết thúc dứt điểm + khởi đầu phía sau" — không phải điềm tai họa thể xác. Ai dùng lá này để dọa bạn về "đại nạn" rồi gợi ý lễ giải, nơi đó đang kinh doanh nỗi sợ.',
  },
  {
    slug: 'page-of-swords',
    name: 'Page of Swords',
    name_vi: 'Thị Đồng Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 11,
    keyUp: ['tò mò thông tin', 'óc quan sát', 'học hỏi nhanh'],
    keyRev: ['lời vội', 'soi mói', 'nói trước nghĩ sau'],
    image:
      'Người trẻ cầm kiếm dựng đứng trên gò cao, gió thổi tóc và cây nghiêng, mắt ngoái quan sát xung quanh. Tâm trí trẻ giữa trời nhiều gió — nhạy và động.',
    up: 'Thị Đồng Kiếm là cái đầu háo hức: thích hỏi, thích tra, bắt tín hiệu nhanh, nói chuyện gì cũng muốn hiểu tới gốc. Lá này hợp giai đoạn thu thập — học kỹ năng mới, tìm hiểu trước khi quyết, lắng nghe các bên. Sự tỉnh táo non trẻ có cái hay: chưa đủ định kiến để bỏ sót điều người "biết rồi" hay bỏ sót.',
    rev: 'Ngược chiều: năng lượng ấy đổ vào chỗ rẻ — hóng chuyện, bắt lỗi vặt, tranh luận để tỏ ra sắc, nói trước nghĩ sau làm đứt tay người (và mình). Thông minh chưa kèm tử tế thì mới chỉ là nhanh.',
    love: 'Trong tình cảm: tò mò về nhau là tốt — soi điện thoại, kiểm tra ngầm là phá. Câu hỏi thẳng thắn xây niềm tin nhanh hơn cuộc điều tra giỏi nhất.',
    work: 'Trong công việc: hợp nghiên cứu, kiểm chứng, đặt câu hỏi trong họp. Trước khi gửi tin nhắn sắc, đọc lại một lần bằng mắt người nhận.',
    reflect: [
      'Bạn đang tò mò điều gì — và sự tò mò đó đang phục vụ việc gì lớn hơn?',
      'Lời nhanh nào gần đây của bạn đã cứa ai đó — có đáng một lời đính chính?',
    ],
  },
  {
    slug: 'knight-of-swords',
    name: 'Knight of Swords',
    name_vi: 'Hiệp Sĩ Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 12,
    keyUp: ['lao thẳng vào mục tiêu', 'quyết liệt', 'nói thẳng làm nhanh'],
    keyRev: ['hấp tấp', 'cãi thắng bằng mọi giá', 'lao không nhìn đường'],
    image:
      'Hiệp sĩ thúc ngựa phi nước đại ngược chiều gió, kiếm giơ cao, mây rách thành vệt. Tốc độ tối đa của tâm trí biến thành hành động.',
    up: 'Hiệp Sĩ Kiếm là cú xung phong của lý trí: thấy rõ việc phải làm và làm ngay, nói rõ điều phải nói và nói thẳng. Khi cần ai đó phá vỡ trì trệ, đặt vấn đề gai góc lên bàn, đẩy một việc kẹt lâu — đây là năng lượng đúng. Trì hoãn có chi phí; có những cánh cửa chỉ mở khi bị đạp.',
    rev: 'Ngược chiều: tốc độ thiếu vô lăng — quyết khi chưa đủ dữ kiện, gửi tin nhắn lúc đang sôi, cãi để thắng chứ không để đúng, và để lại sau lưng một loạt đổ vỡ "không cố ý". Chậm 24 giờ hiếm khi hỏng việc; nhanh 5 phút thì hỏng được khối thứ.',
    love: 'Trong tình cảm: thẳng thắn là quý — nhưng nói thẳng KHÔNG đồng nghĩa nói phũ. Cùng một nội dung, cách nói quyết định người kia nghe được hay chỉ đỡ đòn.',
    work: 'Trong công việc: hợp xử lý khủng hoảng, chốt việc tồn đọng. Luật tự đặt: email/tin nhắn viết lúc giận — để ngăn nháp tới sáng mai.',
    reflect: [
      'Việc gì đáng được bạn "xung phong" ngay tuần này — và việc gì bạn đang xung phong chỉ vì sốt ruột?',
      'Lần gần nhất sự nhanh của bạn phải trả giá — bài học còn nhớ không?',
    ],
  },
  {
    slug: 'queen-of-swords',
    name: 'Queen of Swords',
    name_vi: 'Hoàng Hậu Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 13,
    keyUp: ['nhìn rõ', 'ranh giới sắc', 'hỏi thẳng đáp thật'],
    keyRev: ['lạnh thành giáp', 'phán xét', 'cô lập bằng lý trí'],
    image:
      'Hoàng hậu ngồi nghiêng, kiếm dựng thẳng một tay, tay kia chìa ra như nói "trình bày đi — sự thật thôi". Gương mặt đã đi qua nhiều chuyện, không còn dễ bị ru.',
    up: 'Hoàng Hậu Kiếm là sự tỉnh táo có học phí: từng đau nên nhìn rõ, từng bị ngọt lừa nên quý sự thật hơn lời êm. Bà đại diện cho kiểu giao tiếp đáng tin nhất — hỏi thẳng, đáp thật, ranh giới rõ, không úp mở. Quanh người như vậy, ai cũng biết mình đứng ở đâu; sự rõ ràng là một dạng tử tế bị đánh giá thấp.',
    rev: 'Ngược chiều: sự sắc thành giáp — chữ "không" buông trước khi nghe hết, lý trí dùng làm hào nước cách người, mọi mềm yếu (của mình lẫn của người) bị xử như lỗi hệ thống. Kiếm để cắt sự dối, không phải cắt sự gần.',
    love: 'Trong tình cảm: tiêu chuẩn rõ và ranh giới sắc giúp bạn không sa vào quan hệ rẻ; chỉ canh đừng để hàng rào cao tới mức người thật lòng cũng không trèo nổi.',
    work: 'Trong công việc: hợp vai phản biện, rà soát, đàm phán. Một câu góp ý thật mà tử tế đáng giá hơn mười câu khen xã giao.',
    reflect: [
      'Ranh giới nào của bạn đang bảo vệ bạn — ranh giới nào đang giam bạn?',
      'Bạn đòi sự thật từ người khác — bạn có cho người khác sự thật về cảm xúc của mình không?',
    ],
  },
  {
    slug: 'king-of-swords',
    name: 'King of Swords',
    name_vi: 'Vua Kiếm',
    arcana: 'minor',
    suit_vi: 'Kiếm',
    number: 14,
    keyUp: ['phán đoán khách quan', 'nguyên tắc', 'quyết bằng tiêu chí'],
    keyRev: ['cứng lý bỏ tình', 'lạm dụng lập luận', 'lạnh quyền uy'],
    image:
      'Vị vua ngồi chính diện — hiếm hoi trong bộ bài — kiếm hơi nghiêng, mắt nhìn thẳng người đối diện. Tư thế của người ra phán quyết và chịu trách nhiệm về nó.',
    up: 'Vua Kiếm là chuẩn mực của quyết định lý trí: đặt tiêu chí trước khi nhìn phương án, nghe đủ các bên, quyết theo nguyên tắc chứ không theo người quen. Lá này gợi lúc cần bạn đứng vai trọng tài cho chính đời mình — tiền bạc, pháp lý, chọn hướng lớn: cảm xúc được lắng nghe, nhưng không được cầm bút ký.',
    rev: 'Ngược chiều: nguyên tắc thành nhà đá — đúng quy trình mà mất con người, thắng lý mà thua sạch tình; hoặc trí tuệ bị dùng để áp đảo ("nói không lại tôi nghĩa là tôi đúng"). Người giỏi lập luận nhất phòng họp chưa chắc là người đúng nhất — chỉ là người khó bị cãi nhất.',
    love: 'Trong tình cảm: sự vững và rạch ròi của bạn là chỗ dựa; nhưng người thương cần được nghe bằng tim trước khi được phân xử bằng đầu. Có những cuộc nói chuyện không cần phán quyết, chỉ cần ngồi cạnh.',
    work: 'Trong công việc: hợp vai quyết định lớn, xử tranh chấp, đặt chuẩn. Công khai tiêu chí trước — quyền lực minh bạch thì bền.',
    reflect: [
      'Quyết định nào bạn sắp đưa ra — tiêu chí của nó đã được viết xuống trước, hay đang được nắn theo kết quả muốn có?',
      'Ở đâu bạn đang "đúng quy trình" mà lạnh dần với người?',
    ],
  },

// ============ TIỀN (Pentacles) — đất: công việc, vật chất, sức khỏe ============
  {
    slug: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    name_vi: 'Át Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 1,
    keyUp: ['cơ hội thật', 'hạt giống vật chất', 'khởi đầu vững'],
    keyRev: ['cơ hội vuột', 'kế hoạch thiếu rễ'],
    image:
      'Bàn tay từ mây nâng đồng tiền vàng trên khu vườn xanh, lối đi xuyên cổng hoa dẫn về phía núi. Cơ hội ở dạng cụ thể nhất — cầm được, trồng được.',
    up: 'Át Tiền là hạt giống của thế giới vật chất: một lời mời việc, một khoản để dành đầu tiên, một khách hàng đầu tiên, một nền móng sức khỏe mới (giấc ngủ, buổi tập đầu). Khác Át Gậy bốc lửa, Át Tiền nói giọng của đất: cơ hội này THẬT — và như mọi hạt giống thật, nó cần được trồng xuống chứ không phải được ngắm. Một bước cụ thể tuần này đáng giá hơn một kế hoạch đẹp tháng sau.',
    rev: 'Ngược chiều: hạt giống nằm mãi trên bàn — cơ hội đến rồi nguội vì chần chừ, hoặc kế hoạch tài chính/sự nghiệp nghe hay mà không bám đất (số liệu đâu, khách đâu, ai trả tiền?). Mơ không có rễ thì gió nhẹ cũng bay.',
    love: 'Trong tình cảm: giai đoạn xây nền thực tế — minh bạch chuyện tiền, thói quen sống, nhịp sinh hoạt. Lãng mạn bền đứng trên nền móng chứ không thay nền móng.',
    work: 'Trong công việc: lời mời/dự án/nguồn thu mới đáng nắm. Trước khi gật: viết ra con số thật và bước đầu tiên cụ thể.',
    reflect: [
      'Cơ hội cụ thể nào đang nằm trên bàn bạn — bước "trồng xuống" nhỏ nhất là gì?',
      'Trong các dự định, cái nào có rễ (số liệu, người thật, tiền thật) — cái nào mới chỉ có lá?',
    ],
  },
  {
    slug: 'two-of-pentacles',
    name: 'Two of Pentacles',
    name_vi: 'Hai Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 2,
    keyUp: ['tung hứng nhiều vai', 'linh hoạt', 'giữ nhịp dòng tiền'],
    keyRev: ['quá tải đa nhiệm', 'rơi bóng', 'cần chọn ưu tiên'],
    image:
      'Người trẻ nhún nhảy tung hứng hai đồng tiền nối nhau bằng dải lụa hình số 8 vô cực; sau lưng, hai con thuyền cưỡi sóng lớn. Giữ thăng bằng — trong chuyển động, không phải trong đứng yên.',
    up: 'Hai Tiền là nghệ thuật tung hứng của đời thường: việc chính và việc phụ, công việc và gia đình, khoản thu và khoản chi. Lá này công nhận: bận kiểu này là bình thường, và thăng bằng không phải trạng thái tĩnh mà là điều chỉnh liên tục — như người trên thuyền giữa sóng. Bí quyết của nó: đừng cố giữ mọi quả bóng cùng độ cao; biết quả nào bằng thủy tinh, quả nào bằng cao su.',
    rev: 'Ngược chiều: số quả bóng đã vượt số tay — deadline chồng, hẹn quên, tiền lệch sổ. Đây không phải lỗi đạo đức, chỉ là toán học: thứ gì cũng ưu tiên nghĩa là không thứ gì ưu tiên. Hạ một quả bóng xuống một cách CÓ CHỦ ĐÍCH trước khi nó tự rơi.',
    love: 'Trong tình cảm: người yêu/bạn đời không nên thường trực là "quả bóng cao su" — thứ luôn bị hoãn vì "đợt này bận". Vài đợt-này nối nhau là một năm.',
    work: 'Trong công việc: viết hết các vai đang gánh ra giấy, đánh dấu 2 quả thủy tinh. Lịch của tuần phải nhìn thấy 2 quả đó trước.',
    reflect: [
      'Quả bóng nào của bạn là thủy tinh mà đang bị tung như cao su?',
      'Việc gì bạn nên CHỦ ĐỘNG đặt xuống tuần này, trước khi nó tự rơi?',
    ],
  },
  {
    slug: 'three-of-pentacles',
    name: 'Three of Pentacles',
    name_vi: 'Ba Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 3,
    keyUp: ['tay nghề được nhìn nhận', 'cộng tác chất lượng', 'mỗi người một vai'],
    keyRev: ['lệch vai', 'ôm hết một mình', 'làm cho xong'],
    image:
      'Trong nhà thờ đang xây, người thợ trẻ đứng trên ghế trao đổi với tu sĩ và kiến trúc sư cầm bản vẽ. Ba người ba nghề — cùng một công trình.',
    up: 'Ba Tiền là khoảnh khắc tay nghề gặp đúng sân: việc bạn làm tốt được người khác cần đến, và công trình lớn hơn sức một người bắt đầu thành hình nhờ mỗi người giữ đúng vai. Lá này đề cao một thứ ít được khen: sự chuyên nghiệp — đến đúng giờ, làm đúng cam kết, hỏi khi chưa rõ. Đội tốt không phải đội toàn sao; là đội mà bản vẽ, viên gạch và lời cầu nguyện chịu nói chuyện với nhau.',
    rev: 'Ngược chiều: công trình trục trặc vì vai lệch — người giỏi bị xếp sai chỗ, kẻ ôm hết việc vì "không tin ai", phối hợp toàn hiểu lầm vì chẳng ai chịu hỏi lại. Hoặc chính bạn đang làm-cho-xong một việc xứng đáng được làm-cho-tới.',
    love: 'Trong tình cảm: một mái nhà cũng là công trình ba bên — hai người và bản vẽ chung. Phân vai theo sở trường, đừng theo khuôn "việc này phải của ai".',
    work: 'Trong công việc: thời điểm tốt để nhận dự án chung, xin phản hồi từ người giỏi hơn, hoặc đứng ra điều phối. Tay nghề + phối hợp = hơn cả tài năng đơn lẻ.',
    reflect: [
      'Trong "công trình" hiện tại của bạn, ai đang giữ vai gì — có vai nào đang lệch?',
      'Kỹ năng nào của bạn đáng được mang ra "công trình" lớn hơn thay vì chỉ dùng một mình?',
    ],
  },
  {
    slug: 'four-of-pentacles',
    name: 'Four of Pentacles',
    name_vi: 'Bốn Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 4,
    keyUp: ['giữ chắc', 'an toàn tài chính', 'ổn định có kiểm soát'],
    keyRev: ['khư khư', 'sợ mất đến tê liệt', 'nới tay'],
    image:
      'Người đàn ông ngồi ôm khư một đồng tiền trước ngực, một đồng đội trên đầu, hai đồng đè dưới hai bàn chân — phía sau là thành phố ông không còn bước vào được, vì tay chân đều bận giữ.',
    up: 'Bốn Tiền là bản năng giữ: tiết kiệm, phòng thân, không tiêu hoang, giữ việc ổn định. Trong chừng mực, đây là trí khôn của đất — ai từng thiếu sẽ hiểu giá trị của một khoản đệm. Lá này xuất hiện để xác nhận nhu cầu an toàn của bạn là chính đáng… và để hỏi nhỏ một câu: giữ đến mức nào thì sự an toàn bắt đầu giữ ngược lại bạn?',
    rev: 'Ngược chiều có hai cửa: hoặc bạn đang nới tay đúng lúc — dám chi cho học hành, sức khỏe, trải nghiệm, dám rời "việc ổn định" đã hết chỗ lớn; hoặc cơn sợ mất đang siết thêm — kiểm soát tiền của người thân, đếm đi đếm lại thứ không ai lấy. Tiền là công cụ; công cụ ôm trước ngực thì không dùng được.',
    love: 'Trong tình cảm: giữ người quá chặt — kiểm soát, ghen, "không cho đi đâu" — là cách chắc nhất để bóp nghẹt thứ mình sợ mất. Bàn tay mở giữ được nhiều hơn nắm đấm.',
    work: 'Trong công việc: phòng thủ tài chính tốt rồi thì câu hỏi kế tiếp là sinh lời và phát triển — tiền đứng yên là tiền teo dần theo trượt giá.',
    reflect: [
      'Bạn đang GIỮ thứ gì chặt nhất — và việc giữ đó đang tốn của bạn cơ hội nào?',
      'Khoản chi nào bạn luôn tiếc nhưng sâu xa biết là đáng (sức khỏe, học, quan hệ)?',
    ],
  },
  {
    slug: 'five-of-pentacles',
    name: 'Five of Pentacles',
    name_vi: 'Năm Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 5,
    keyUp: ['thiếu hụt', 'cảm giác bị bỏ ngoài', 'giai đoạn khó khăn'],
    keyRev: ['hồi phục', 'dám nhận giúp đỡ', 'cửa gần hơn mình nghĩ'],
    image:
      'Hai người rách rưới dắt nhau đi trong tuyết — một người chống nạng — ngang qua ô cửa kính nhà thờ sáng đèn ấm. Họ không nhìn thấy: cửa vào ở ngay gần.',
    up: 'Năm Tiền là mùa đông của vật chất: kẹt tiền, mất việc, sức khỏe xuống — và thứ buốt hơn cả là cảm giác bị bỏ lại bên ngoài, một mình. Lá này không phủ nhận cái khó; nó chỉ vào ô cửa sáng trong tranh: sự giúp đỡ thường gần hơn ta tưởng — người thân, bạn cũ, cộng đồng, chính sách — nhưng cửa không tự mở cho người nhất quyết đi qua trong im lặng. Nghèo một mùa không định nghĩa một đời.',
    rev: 'Ngược chiều: tuyết đang tan — việc mới ló, nợ vơi dần, sức khỏe nhích lên; hoặc chính bạn vừa làm điều khó nhất: mở miệng nhờ. Hồi phục vật chất luôn chậm hơn mong muốn — nhưng đường cong đã đổi hướng là điều đáng ghi nhận.',
    love: 'Trong tình cảm: khó khăn vật chất thử độ thật của một mối quan hệ — và cũng dễ sinh tự ti, xa cách. Nói thật tình cảnh với người bên cạnh; nghèo không nhục, giấu mới mệt.',
    work: 'Trong công việc: giai đoạn hụt — đừng rút lui khỏi các mối quan hệ nghề nghiệp vì ngại; đa số việc mới đến qua một người quen biết mình đang cần.',
    reflect: [
      '"Ô cửa sáng" nào đang ở gần mà bạn chưa gõ — vì ngại, vì sĩ diện, hay vì nghĩ mình không xứng?',
      'Nếu bạn của bạn ở đúng tình cảnh này, bạn sẽ bảo họ làm gì đầu tiên?',
    ],
    ease:
      'Lá này mô tả một GIAI ĐOẠN thiếu hụt, không phải lời phán "số nghèo". Không có nghi lễ nào đổi được dòng tiền; thứ đổi được nó là thời gian, sự giúp đỡ và vài quyết định — và cả ba đều ở phía cửa, không ở phía tuyết.',
  },
  {
    slug: 'six-of-pentacles',
    name: 'Six of Pentacles',
    name_vi: 'Sáu Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 6,
    keyUp: ['cho và nhận', 'hào phóng có cân', 'dòng chảy công bằng'],
    keyRev: ['cho kèm dây trói', 'nhận kèm ơn nặng', 'lệch quyền lực'],
    image:
      'Thương nhân một tay cầm cân, tay kia thả tiền cho một trong hai người quỳ xin. Lòng tốt — được đặt cạnh một chiếc cân.',
    up: 'Sáu Tiền là dòng chảy cho–nhận: lúc dư giúp người, lúc ngặt được giúp — và cả hai vai đều cần học. Cho đúng cách (đúng người, đúng lúc, không kể công) là một kỹ năng; nhận một cách đàng hoàng (biết ơn mà không quỵ lụy) là kỹ năng khó hơn. Lá này nhắc: hôm nay bạn ở đầu nào của dòng chảy không quan trọng bằng việc dòng chảy còn thông.',
    rev: 'Ngược chiều: chiếc cân lệch — món quà kèm dây điều khiển ("tôi cho anh thì anh phải…"), khoản giúp thành món nợ ơn trả mãi không hết, hoặc cho để được thấy mình cao hơn. Cũng có khi là phía bạn: cho đi để mua sự công nhận, hoặc nhận mãi thành quen. Lòng tốt có điều kiện là một hợp đồng trá hình.',
    love: 'Trong tình cảm: để ý cán cân quyền lực — ai luôn là người "ban", ai luôn là người "chịu ơn"? Quan hệ khỏe là nơi cả hai thay phiên được yếu.',
    work: 'Trong công việc: trả công xứng đáng, chia quyền lợi rõ, mentor người sau. Sự hào phóng đúng chỗ là khoản đầu tư lãi dài nhất.',
    reflect: [
      'Bạn cho đi dễ hơn hay nhận về dễ hơn — và điều đó nói gì về bạn?',
      'Món "quà" nào bạn từng cho/nhận mà kèm dây — giờ gỡ được không?',
    ],
  },
  {
    slug: 'seven-of-pentacles',
    name: 'Seven of Pentacles',
    name_vi: 'Bảy Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 7,
    keyUp: ['chờ vụ chín', 'đánh giá lại đầu tư', 'kiên nhẫn có tính toán'],
    keyRev: ['sốt ruột nhổ cây', 'tưới chỗ không ra quả'],
    image:
      'Người làm vườn tựa cằm lên cán cuốc, đứng lặng nhìn giàn cây trĩu bảy đồng tiền. Không hái, không cuốc — đang ĐÁNH GIÁ.',
    up: 'Bảy Tiền là phút đứng lặng của nhà đầu tư (tiền, công sức, năm tháng): cây đã trồng, quả đang lớn — giờ là lúc hỏi câu lạnh lùng: vụ này có đáng tiếp không? Lá này quý ở sự trung thực giữa chừng: kiên nhẫn là đức tính, nhưng kiên nhẫn với đúng cây; còn đứng đợi quả ở cây không ra quả thì gọi là lãng phí có kỷ luật. Nhìn số liệu, không nhìn hy vọng.',
    rev: 'Ngược chiều: hoặc sốt ruột nhổ cây lên xem rễ (kiểm tra liên tục, đổi kế hoạch mỗi tuần — cây nào sống nổi), hoặc nhận ra mình đã tưới quá lâu một mảnh đất cằn vì tiếc công đã đổ. Công đã đổ không quay lại được; chỉ chọn được nơi đổ công tiếp theo.',
    love: 'Trong tình cảm: mối quan hệ cũng có mùa vụ — có giai đoạn chỉ thấy chăm mà chưa thấy ngọt. Đánh giá bằng hướng đi (có lớn dần không) chứ không bằng một tuần xấu trời.',
    work: 'Trong công việc: dự án/kỹ năng/kênh nào đầu tư mãi chưa ra số? Đặt một mốc kiểm: thêm X tháng với tiêu chí Y — đạt thì tiếp, không thì dồn đất cho cây khác.',
    reflect: [
      'Khoản đầu tư công sức nào của bạn đáng một buổi "đứng tựa cuốc" đánh giá thật lạnh?',
      'Bạn đang kiên nhẫn với cây có quả non — hay đang tiếc công với đất cằn?',
    ],
  },
  {
    slug: 'eight-of-pentacles',
    name: 'Eight of Pentacles',
    name_vi: 'Tám Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 8,
    keyUp: ['mài giũa tay nghề', 'chuyên tâm', 'lặp lại có chủ đích'],
    keyRev: ['làm máy móc mất hồn', 'đứt mạch rèn luyện'],
    image:
      'Người thợ trẻ ngồi khắc đồng tiền thứ tám, bảy đồng đã xong treo thẳng hàng; thành phố mờ phía xa — anh quay lưng lại với nó để ngồi đây khắc.',
    up: 'Tám Tiền là lá của giờ-bay: tay nghề không đến từ tài năng trời cho mà từ con số lần lặp có chủ đích — khắc xong một đồng, treo lên, khắc tiếp đồng sau tốt hơn một li. Lá này gợi giai đoạn cúi đầu luyện: học sâu một kỹ năng, làm đi làm lại một dạng việc tới mức thành phản xạ. Thành phố (danh tiếng, cơ hội) ở phía xa kia sẽ tự tìm đến người có tám đồng tiền khắc đẹp treo trên cột.',
    rev: 'Ngược chiều: sự lặp mất chữ "chủ đích" — làm như máy, mười năm kinh nghiệm thực ra là một năm lặp mười lần; hoặc mạch rèn đứt giữa chừng vì hết kiên nhẫn với đoạn "chưa giỏi". Đoạn xấu hổ giữa người-mới và người-giỏi là đoạn ai cũng phải bò qua — không có đường vòng.',
    love: 'Trong tình cảm: yêu lâu cũng là một tay nghề — lắng nghe, xin lỗi, làm lành đều giỏi lên nhờ luyện. Đừng mong "tự nhiên hợp"; hãy luyện thành hợp.',
    work: 'Trong công việc: chọn MỘT kỹ năng đòn bẩy và đặt lịch luyện đều (30–60 phút/ngày thắng 8 tiếng/cuối tuần). Giỏi một thứ sâu mở nhiều cửa hơn biết mười thứ nông.',
    reflect: [
      'Kỹ năng nào nếu giỏi hơn 2 bậc sẽ đổi hẳn đời bạn — và lịch luyện nó đâu?',
      'Việc lặp lại hằng ngày của bạn: đang là luyện có chủ đích, hay là chạy máy?',
    ],
  },
  {
    slug: 'nine-of-pentacles',
    name: 'Nine of Pentacles',
    name_vi: 'Chín Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 9,
    keyUp: ['tự chủ', 'thành quả tự thân', 'tận hưởng một mình đàng hoàng'],
    keyRev: ['thành quả mà cô lập', 'phụ thuộc dán mác tự do'],
    image:
      'Người phụ nữ áo thêu hoa đứng giữa vườn nho trĩu quả của chính mình, chim ưng đậu trên găng tay — biểu tượng của bản năng đã được thuần. Sự sung túc — và một mình — mà đầy đặn.',
    up: 'Chín Tiền là phần thưởng của kỷ luật dài hạn: cuộc sống tự chủ — tiền mình kiếm, vườn mình trồng, thời gian mình quyết — và khả năng tận hưởng nó một mình mà không thấy thiếu. Lá này tôn vinh một dạng giàu ít được nói tới: không cần ai chống lưng, không cần ai vỗ tay, vẫn sống đầy. Trước khi là "một nửa" của bất kỳ ai, hãy là một-người-nguyên-vẹn như thế này.',
    rev: 'Ngược chiều: hoặc vườn đẹp mà chủ vườn cô đơn — thành công xây bằng cách cắt hết kết nối; hoặc vẻ "tự chủ" bên ngoài đang đứng trên nền phụ thuộc (tiêu trước trả sau, sống bằng hình ảnh). Tự do tài chính giả mạo là loại nợ đắt nhất.',
    love: 'Trong tình cảm: người hấp dẫn nhất là người không CẦN ai cứu — đến với nhau vì muốn, không vì thiếu. Nhưng tự chủ không có nghĩa là không cho ai vào vườn.',
    work: 'Trong công việc: hái thành quả đã chín — và bảo vệ thứ làm ra nó: kỷ luật, chuẩn mực, lòng tự trọng nghề. Đừng hạ giá mình lúc đang được giá.',
    reflect: [
      '"Khu vườn" bạn đang xây: mười năm nữa nó nuôi bạn được không, hay vẫn cần bạn còng lưng tưới?',
      'Bạn có dám tận hưởng một mình — một bữa ngon, một chuyến đi — mà không thấy cần ai chứng kiến?',
    ],
  },
  {
    slug: 'ten-of-pentacles',
    name: 'Ten of Pentacles',
    name_vi: 'Mười Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 10,
    keyUp: ['bền vững dài hạn', 'tài sản truyền đời', 'gốc rễ gia tộc'],
    keyRev: ['tranh chấp tài sản', 'bền ngoài rạn trong'],
    image:
      'Cụ già khoác áo thêu nho ngồi cùng đôi chó, đôi vợ chồng trẻ và đứa cháu dưới cổng vòm khắc gia huy; mười đồng tiền xếp thành Cây Sự Sống phủ lên toàn cảnh. Ba thế hệ trong một khung hình.',
    up: 'Mười Tiền là tầm nhìn dài hơn một đời: tài sản, nghề, nếp nhà, giá trị — những thứ được xây để truyền lại. Lá này kéo câu hỏi từ "tháng này dư bao nhiêu" lên "mình đang xây cái gì còn lại sau mình": căn nhà cho con, nghề truyền cho trò, quỹ học cho cháu, hay đơn giản là nếp sống tử tế mà thế hệ sau nhìn vào. Giàu một đời là giỏi; để lại nền cho nhiều đời là khôn.',
    rev: 'Ngược chiều: chính thứ "của để dành" thành mồi lửa — tranh chấp thừa kế, anh em sứt mẻ vì đất, hôn nhân tính bằng tài sản; hoặc gia tộc bề thế mà bên trong lạnh tanh. Của cải không có người tử tế đi kèm thì chỉ là kho thuốc nổ có sổ đỏ.',
    love: 'Trong tình cảm: cưới nhau cũng là nhập hai "hệ gia đình" — nói chuyện sớm về tiền chung, trách nhiệm hai bên nội ngoại, kỳ vọng con cái. Không lãng mạn, nhưng cứu được rất nhiều lãng mạn về sau.',
    work: 'Trong công việc: nghĩ hạ tầng — quỹ dự phòng, bảo hiểm, di chúc, hệ thống làm việc không phụ thuộc một người. Thứ bền là thứ chạy được khi bạn vắng mặt.',
    reflect: [
      'Sau bạn, thứ gì còn lại — và bạn có đang xây nó một cách có chủ đích?',
      'Trong nhà bạn, chuyện tiền – đất – thừa kế: đã nói rõ với nhau, hay đang để "sau này tính"?',
    ],
  },
  {
    slug: 'page-of-pentacles',
    name: 'Page of Pentacles',
    name_vi: 'Thị Đồng Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 11,
    keyUp: ['ham học thực tế', 'mầm kế hoạch', 'bắt đầu từ việc nhỏ'],
    keyRev: ['mơ kế hoạch không bước đầu', 'học mãi không hành'],
    image:
      'Người trẻ đứng giữa đồng cỏ, nâng đồng tiền ngang tầm mắt ngắm nghía như ngắm một thế giới — phía xa là luống đất mới cày. Sự nghiêm túc đáng yêu của người mới bắt đầu.',
    up: 'Thị Đồng Tiền là tinh thần học-để-làm: đăng ký khóa học và làm bài tập thật, đọc sách kèm áp dụng, tập tành khoản đầu tư đầu tiên bằng số tiền nhỏ. Lá này gợi sự khởi đầu khiêm tốn mà chắc: ai cũng phải có "đồng tiền đầu tiên" — dự án đầu tay, khách đầu tiên, tháng lương đầu — và cách cầm đồng đầu tiên định hình cách cầm những đồng sau.',
    rev: 'Ngược chiều: học thành trốn — sưu tầm khóa học, đánh dấu bài "để dành đọc", kế hoạch chi tiết tới mức không bao giờ tới ngày bắt đầu. Kiến thức chưa hành là hàng tồn kho; thêm nữa chỉ thêm chật.',
    love: 'Trong tình cảm: giai đoạn tìm hiểu nghiêm túc, chậm mà thật. Đừng coi nhẹ những "bài học nhỏ": cách người ta đối xử với phục vụ bàn, cách giữ lời hứa vặt.',
    work: 'Trong công việc: nhận việc nhỏ làm thật kỹ — người mới nổi bật bằng độ tin cậy trước khi nổi bật bằng tài. Hỏi nhiều, ghi chép, làm lại.',
    reflect: [
      'Thứ bạn đang học: bài tập THỰC HÀNH gần nhất bạn làm là gì, bao giờ?',
      '"Đồng tiền đầu tiên" nào bạn có thể kiếm/làm ra trong 30 ngày tới — nhỏ thôi, nhưng thật?',
    ],
  },
  {
    slug: 'knight-of-pentacles',
    name: 'Knight of Pentacles',
    name_vi: 'Hiệp Sĩ Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 12,
    keyUp: ['bền bỉ', 'chậm mà chắc', 'đáng tin cậy'],
    keyRev: ['ì trệ', 'cầu toàn hóa trì hoãn', 'chán việc lặp'],
    image:
      'Hiệp sĩ ngồi trên con ngựa cày đứng yên giữa ruộng đã vỡ luống, ngắm đồng tiền trên tay. Con ngựa duy nhất KHÔNG phi trong cả bộ bài — vì việc của anh không cần phi, cần cày.',
    up: 'Hiệp Sĩ Tiền là người về đích kiểu nông dân: không cú nước rút nào ngoạn mục, chỉ là sáng nào cũng ra ruộng. Lá này tôn vinh thứ năng lực bị mạng xã hội bỏ quên: làm việc nhàm một cách xuất sắc, giữ lời một cách buồn tẻ, tiến 1% một ngày trong im lặng. Khi mọi người mải tìm đường tắt, người đi đường dài thẳng lại thành nhanh nhất.',
    rev: 'Ngược chiều: chậm-mà-chắc rơi mất vế "chắc", còn lại chậm — quy trình thành lối mòn, cẩn thận thành lề mề, cầu toàn thành cớ hoãn ("chưa hoàn hảo nên chưa ra mắt"). Cũng có khi là cơn chán chính đáng của người làm mãi việc lặp: cày giỏi cũng cần thấy mùa gặt.',
    love: 'Trong tình cảm: kiểu người không lãng mạn ồn ào nhưng có mặt mỗi-lần-cần. Nếu bạn đang được yêu kiểu này — đừng nhầm sự ổn định với sự nhạt; nếu bạn đang yêu kiểu này — thỉnh thoảng tặng một bất ngờ, ngựa cày cũng biết vui.',
    work: 'Trong công việc: hợp các việc cần độ tin tưởng dài — vận hành, chất lượng, tài chính. Đặt mốc "đủ tốt để giao" rõ ràng, kẻo cầu toàn ăn mất deadline.',
    reflect: [
      'Việc "nhàm mà quan trọng" nào bạn đang làm đều — và đã bao giờ tự ghi nhận mình vì nó?',
      'Ở đâu sự cẩn thận của bạn đang thành cái cớ để chưa bắt đầu/chưa ra mắt?',
    ],
  },
  {
    slug: 'queen-of-pentacles',
    name: 'Queen of Pentacles',
    name_vi: 'Hoàng Hậu Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 13,
    keyUp: ['chăm lo thiết thực', 'vun vén', 'ấm no có bàn tay người giữ'],
    keyRev: ['ôm việc nhà quên mình', 'lo vật chất quên hơi ấm'],
    image:
      'Hoàng hậu ngồi giữa vòm hoa trái, cúi nhìn đồng tiền trên lòng như nhìn một sinh linh cần chăm; chú thỏ nâu nhảy ở góc tranh. Sung túc ở đây có mùi cơm chín, không phải mùi két sắt.',
    up: 'Hoàng Hậu Tiền là người giữ ấm cả một hệ sinh thái: nhà có cơm nóng, sổ chi tiêu cân, người ốm có thuốc, khách đến có chỗ ngồi tử tế — và thường kiêm luôn việc kiếm ra tiền cho tất cả những thứ đó. Lá này gọi tên đúng một dạng tài năng hay bị gọi sai là "đảm đang vặt": biến nguồn lực hữu hạn thành đời sống đầy đặn là một nghề thực thụ, dù chẳng ai trao chức danh.',
    rev: 'Ngược chiều: người giữ ấm cho cả nhà là người duy nhất không ai hỏi có lạnh không — chăm tất cả trừ chính mình, oán thầm tích dần dưới sự chu toàn; hoặc sự chăm lo trượt thành đo đếm vật chất ("đủ ăn đủ mặc là được") mà quên mất nhà cần cả hơi ấm phi vật chất. Tự chăm mình không phải ích kỷ; là bảo trì cái máy đang nuôi cả hệ.',
    love: 'Trong tình cảm: đừng để một người mãi đóng vai "hậu cần" — thỉnh thoảng đổi vai: người được chăm đi chợ, người hay chăm được ngồi không một bữa.',
    work: 'Trong công việc: hợp vai quản trị nguồn lực — ngân sách, vận hành, văn hóa "có người lo cho mình" trong nhóm. Định giá đúng công việc chăm sóc, của người khác và của chính mình.',
    reflect: [
      'Ai đang là "Hoàng Hậu Tiền" trong nhà/nhóm của bạn — họ được chăm lại bằng gì?',
      'Nếu là bạn: tuần này bạn tự vun cho mình thứ gì — như cách bạn vẫn vun cho người khác?',
    ],
  },
  {
    slug: 'king-of-pentacles',
    name: 'King of Pentacles',
    name_vi: 'Vua Tiền',
    arcana: 'minor',
    suit_vi: 'Tiền',
    number: 14,
    keyUp: ['vững vàng vật chất', 'Midas có kiểm soát', 'bảo trợ rộng tay'],
    keyRev: ['đo mọi thứ bằng tiền', 'bảo thủ', 'giàu mà kẹt'],
    image:
      'Vị vua ngồi giữa vườn nho trĩu quả, áo choàng thêu kín chùm nho, tay đặt hờ lên đồng tiền lớn, chân gác lên đầu heo rừng tạc đá — sau lưng là tòa lâu đài ông đã xây xong. Người không cần chứng minh gì thêm.',
    up: 'Vua Tiền là điểm chín của bộ Tiền: làm ra của cải một cách đều đặn, giữ được nó một cách khôn ngoan, và — dấu hiệu của sự chín thật — dùng nó để che chở người khác: trả lương tử tế, đầu tư cho người trẻ, làm chỗ dựa cho gia đình. Lá này gợi tư duy "người làm vườn giàu": không chạy theo cơn sốt, trồng thứ hợp đất mình, để lãi kép và uy tín làm việc của chúng.',
    rev: 'Ngược chiều: chiếc thước đo duy nhất còn lại là tiền — quan hệ tính bằng lợi, lời khuyên nào không ra số đều bị gạt, con cái nghe "ba bận" nhiều hơn "ba nghe đây"; hoặc sự vững thành sự kẹt: từ chối mọi cái mới vì "xưa nay vẫn ổn". Giàu nhất phòng họp mà nghèo nhất bàn ăn là một kết cục có thật.',
    love: 'Trong tình cảm: sự bảo bọc vật chất là một ngôn ngữ yêu — nhưng đừng để nó là ngôn ngữ duy nhất. Người thân cần ông vua bước ra khỏi ngai, không cần thêm một khoản chu cấp.',
    work: 'Trong công việc: thời điểm nghĩ như chủ — xây hệ thống sinh lời bền, đa dạng nguồn thu, nâng người dưới mình lên. Của bền nhất ông vua này có không phải vàng, là chữ tín.',
    reflect: [
      'Ngoài tiền, bạn đang giàu thứ gì — và thứ đó có đang được đầu tư tiếp?',
      'Ai từng nâng bạn lúc bạn chưa có gì — giờ bạn đang nâng ai?',
    ],
  },
];
